### PR TITLE
Crossentropy backend API consistency cleanup

### PR DESCRIPTION
**Pull request by fchollet**
This PR inverts the order of the `output` and `target` arguments in backend crossentropy methods, to make them consistent with the functions in `losses` and the functions in TF.

This is a breaking change. We believe it is an acceptable breakage because:
- API consistency is important
- the "official" API is definitely the one in `losses`, not the backend functions. The backend functions are meant as a cross-backend layer that is not used if an equivalent function exists in the higher-level Keras API.
- we don't expect that more than a handful of users were using these backend methods directly.

Also: some backend style cleanups.

### CODE REVIEW

**Comment by fchollet** [comment]
@bstriner you appear to a user who will be affected by this change: https://github.com/bstriner/keras-seq2seq/blob/master/seq2seq/s2s_loss.py

@yhenon as well: https://github.com/yhenon/keras-frcnn

@transcranial as well: https://github.com/transcranial/kaggle-ultrasound-nerve-segmentation/blob/master/notebooks/lib/segmentation.py

**Comment by 0x00b1** [comment]
I really like this change, but keras-rcnn was impacted: 

https://github.com/broadinstitute/keras-rcnn/pull/92

I would have expected a change like this would have been part of a major release (i.e. 3.0.0).

**Comment by fchollet** [comment]
I have updated the release notes of 2.0.7 to highlight this breaking change.

**Comment by 0x00b1** [comment]
Thanks, @fchollet. 👍

**Pull request merged**
