### PR TITLE
Add model saving functionality

### PR DESCRIPTION
**Pull request by fchollet**
Comments welcome.

This introduces the ability to save at the same time:
- the model structure
- the weights
- the training configuration (including the state of the optimizer)

Thus it allows to resume training exactly where you left off, which wasn't previously possible.

We'll need to add a couple callbacks to go with it.

### CODE REVIEW

**Comment by EderSantana** [comment]
is it backward compatible? can we still ship just the model weights for feedforward passes?

also, we may need a test like run one step, save, load, run another step vs run two steps. both starting from the same random weights.

**Comment by fchollet** [comment]
> is it backward compatible? can we still ship just the model weights for feedforward passes?

Yes, of course. This only adds functionality, and does not modify existing functionality.

> also, we may need a test like run one step, save, load, run another step vs run two steps. both starting from the same random weights.

That's a good point.

**Comment by cmyr** [comment]
ah I'm a little late.

I was thinking it might be useful to get a `user_info` param that allows the user to pass arbitrary metadata to be stored in the saved model. This could be used to save (for example) information about the training dataset.

**Comment by fchollet** [comment]
I think this can be handled by the user themselves, via a metadata file or something similar.

**Comment by RaffEdwardBAH** [comment]
I agree with @cmyr a meta info field built in would be helpful. When training lots of different models and configurations and sharing models with coworkers its nice if it can all be in one file rather than having to keep pairs of files.

**Pull request merged**
