### PR TITLE
added smape loss

### PR DESCRIPTION
**Pull request by armando-fandango**

### CODE REVIEW

**Comment by fchollet** [comment]
What applications would this loss be relevant to, and how many users would benefit?

**Comment by armando-fandango** [comment]
SMAPE is useful for Time Series Applications. I see plenty of TimeSeries users for Keras, hence it would be beneficial to them.

**Comment by fchollet** [comment]
Any interest party, feel free to chime in. I'll be waiting to see community consensus in order to include a new loss/metric.

**Comment by kashif** [comment]
There are quite a number of measures of time series forecast accuracy... and according to this paper: https://robjhyndman.com/papers/mase.pdf these measures like smape are not generally applicable and can produce misleading results... 

The MASE measure is in their paper is the best available measure so I would propose to include that instead of SMAPE.

**Comment by Dandandan** [comment]
SMAPE is used as score for this Kaggle competition: https://www.kaggle.com/c/web-traffic-time-series-forecasting/leaderboard

**Comment by armando-fandango** [comment]
@Dandandan that is true, although SMAPE has its own share of criticism as pointed by @kashif, but it is still a widely used metric. With respect to adding more metrics/losses/activations, what direction should Keras take philosophically? Adding plenty of metrics for the user to chose from? or to provide a minimal set and let the user extend it when needed?

**Comment by fchollet** [comment]
> Adding plenty of metrics for the user to chose from? or to provide a minimal set and let the user extend it when needed?

It's more the latter. We provide commonly used features that correspond to best practices, and provide the ability to support any number of more advanced features easily (e.g. in this case using a new metric is as simple as passing your custom metric function to a model).

**Comment by ahundt** [comment]
@armando-fandango I suggest submitting to [keras-contrib](https://github.com/farizrahman4u/keras-contrib)

**Pull request closed without merging**
