### PR TITLE
don't print backend name

### PR DESCRIPTION
**Pull request by rajpurkar**

### CODE REVIEW

**Comment by farizrahman4u** [comment]
Why?

**Comment by erfannoury** [comment]
https://t.co/a5qT5ETKnm






Sent from Windows Mail





From: Fariz Rahman
Sent: ‎Wednesday‎, ‎December‎ ‎2‎, ‎2015 ‎11‎:‎35‎ ‎PM
To: fchollet/keras





Why?

**Comment by fchollet** [comment]
Um what's going on here?

**Comment by erfannoury** [comment]
@fchollet I'm sincerely sorry for this mess. I literally have no idea how did it happen. I've deleted the comment. Feel free to delete this one as well.

**Comment by fchollet** [comment]
In any case: I believe it is useful to print the name of the backend, which is why this line was included in the first place. 

If we ever want to stop displaying the name of backend, I'm sure we'll figure out how to do that fairly easily.

**Pull request closed without merging**
