### PR TITLE
make data file configurable

### PR DESCRIPTION
**Pull request by DjangoPeng**
Reference: [TensorFlow PR#13917](https://github.com/tensorflow/tensorflow/pull/13917), [TensorFlow issue#13876](https://github.com/tensorflow/tensorflow/issues/13876).

@fchollet Please review the PR.

### CODE REVIEW

**Comment by uZeroJ** [comment]
Hi @DjangoPeng, 
Would it be better that we just pass the parameters to `get_file`, as get_file does not only download and extract data but also do validation on it? 

Thanks and best regards.

**Comment by DjangoPeng** [comment]
I got your point. But I have no idea how to set the `origin` argument when using the local data files.

**Comment by fchollet** [comment]
Thanks for the PR. Looking at it:
- This keyword argument would be mismatched with the API of every other built-in dataset.
- The use case is not clear; it seems this is for users who already have downloaded the dataset somewhere themselves. In that case, why would these users need the built-in Keras method to load/preprocess the data? All we do besides downloading/caching the data, is repeatedly calling `load_batch`, which you can use in your own code as a standalone method. So if you have already downloaded the data, you don't need to use `cifar.load_data` at all.

Overall: we won't merge it.

**Comment by DjangoPeng** [comment]
@fchollet  Agree with you. It seems like there is  already a  function when using local data files.

**Comment by uZeroJ** [comment]
@fchollet For the reason that I make a propose for this is just a enhance for flexibility or maybe a lazy way to get cheap data by calling `loda_data`, like do not repeat the procedures(validation or download) that had already implemented in it.
In my opinion, this is not just for who had downloaded data alreay, but the workflow would be 'check if extracted file exist' -> 'if archived file exist' -> 'download it'. In this way, we won't care where the data come from.
But maybe for archive is the usual state of data, when we use it.
Anyway that is really a trivial issue. And for a new fresh like me, really learnt a lot when look into the source.
Thanks a lot for you time.
@DjangoPeng Thanks for you effort and time.

**Pull request closed without merging**
