### PR TITLE
Add a "compile" argument to 'load_model'

### PR DESCRIPTION
**Pull request by MoyanZitto**
If user use their own custom optimizer or loss function/metrics, load_model will fail to recover these configurations, because model.save cannot save these custom functions.

However, load_model should at least return the uncompiled model, instead of just raise an exception. Adding a boolean argument 'compile' to `load_model` will make it possible for users to compile it with any custom optimizers or loss functions later. For example, without this argument, the following code will raise an exception.
```python

def my_optimizer():
    pass
    # some code

model.comiple(loss='mse', optimizer=my_optimizer)
model.fit(...)
model.save('some_path')

new_model = load_model('some_path')

```

### CODE REVIEW

**Comment by fchollet** [comment]
> If user use their own custom optimizer or loss function/metrics, load_model will fail to recover these configurations, because model.save cannot save these custom functions.

In that case a warning should be throw and no compilation should be done.

We should not need a new keyword argument to handle that case...

**Comment by MoyanZitto** [comment]
@fchollet 

> In that case a warning should be throw and no compilation should be done.

In what case? It turns out in Keras 1.1.1, no warning was threw out in `model.save` when I passed my own optimizer to `.compile`, and when I tried to recover my model from the h5 file, an exception was raised, saying that keras cannot find the optimizer. The program was stopped because of this exception and I didn't get a chance to compile it with the custom optimizer. So my point is, in this case, users would like to use an keyword argument here to indicate keras that returning the uncompiled model is just ok. 

Did keras 1.1.2 fix this problem?

**Comment by fchollet** [comment]
> In what case?

In the case you describe: when no optimizer can be found.

**Comment by MoyanZitto** [comment]
@fchollet 
So, how can I use my custom optimizer if load_model fail to return the in-compiled model?
Perhaps the following example will demonstrate what I mean:

Suppose I have defined the model, then I will compile it, train it and finally save it. I want to train it with my custom optimizer, like this:
```python
class my_opt(SGD):
    def __init__(self, some_argument):
        self.some_argument = some_argument
        super(my_opt, self).__init__()

opt = my_opt('some argument')
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])

model.fit(X_train, Y_train,
          batch_size=batch_size,
          nb_epoch=nb_epoch,
          validation_data=(X_test, Y_test),
          shuffle=True)

model.save('my_model')
```
Good, no problems at all. Now I want to use this model to do prediction, or I want to continue my training process with any other optimizer(anyway, I just want to load the model):
```python
new_model = load_model('my_model', compile=True)
```
Note that I have modified my source code, here compile=True is exactly what the original source code does. And here an exception is raised.
```python
ValueError: ('Optimizer class not found:', u'my_opt')
```
Which is reasonable, I totally understand. My point is, I actually don't have the chance to tell keras that "I know you cannot restore my model, but just give me the structure and let me do the rest."

Adding an `compile` keyword argument will make it possible:
```python
new_model = load_model('my_model', compile=False)
```
Now I can do anything to the new_model, if I want to train it, then keras will tell me that this model has not been compiled, so I know I should compile it by hand.

I think this process is more reasonable.

All experiments were conducted on Keras 1.1.1

**Comment by fchollet** [comment]
This has been recently fixed. You should now use the `custom_objects` dictionary argument.

**Pull request closed without merging**
