### PR TITLE
Added LRN, Convolution with Strides and ZeroPadding2D

### PR DESCRIPTION
**Pull request by pranv**

### CODE REVIEW

**Comment by gnuchoi** [comment]
Hi @pranv, thanks for your contribution. Could you possibly add something about how to use LRN in the code? I tried to use it by simply adding it to the model as below and it gave me an error. However I wasn't sure how to use it and found out it's not included in the documentation perhaps because it was added quite recently. I would appreciate if I could get some information on the usage of it. 

```
    model.add(Convolution2D(num_stacks[0], 1, image_patch_sizes[0][0], image_patch_sizes[0][1], border_mode='same', activation = 'relu'))
    model.add(MaxPooling2D(poolsize=pool_sizes[0]))
    model.add(normalization.LRN2D())
```

**Comment by pranv** [comment]
@gnuchoi, this works on my system

```python
from keras.models import Sequential
from keras.layers.normalization import LRN2D
from keras.layers.convolutional import Convolution2D, MaxPooling2D

import numpy as np

model = Sequential()
model.add(Convolution2D(32, 1, 3,3))
model.add(MaxPooling2D(poolsize=(2,2)))
model.add(LRN2D())

model.compile('sgd','mse')

input = np.random.random((1,1,32,32))
model.predict(input)
model.predict(input).shape

>>> (1, 32, 15, 15)
```

**Comment by gnuchoi** [comment]
@pranv Thanks. I tried it again and it's working! There may be another error, now it works.

**Comment by ndawe** [comment]
Why was LRN2D removed in 82353da?

**Comment by ndawe** [comment]
I now see this: https://groups.google.com/forum/#!topic/keras-users/8Ncd0dpuPNE

**Pull request merged**
