### PR TITLE
Deep Averaging Networks

### PR DESCRIPTION
**Pull request by jmhessel**
Added a new layer "TimeDistributedMerge" which is capable of merging time distributed outputs. Previously, the merge layer could only merge named layers, which is problematic if you want to implement something like the "Deep Averaging Network" which is detailed here:

http://cs.umd.edu/~miyyer/pubs/2015_acl_dan.pdf

This implementation of the deep averaging network outperforms the imdb cnn/lstm by a bit, and only takes 4 seconsd to train per epoch on a titan X GPU.

Sorry if there are formatting issues, this is the first time I have made a PR for keras .

### CODE REVIEW

**Comment by jmhessel** [comment]
Oh, and by the way --- the way I implemented sum/ave differently in the merge and timedistributedmerge cases was because I wasn't sure which way would be preferred. My suspicion is that keeping it consistent is a good idea.

**Comment by jmhessel** [comment]
(and apologies for not having unit tests set up. I am unfamiliar with what standards are applied to the code base)

**Comment by fchollet** [comment]
There are 3 things going on in this PR. The average mode in `Merge` and the new layer `TimeDistributedMerge` can be considered together, but the example should definitely be submitted as a separate PR.

**Comment by jmhessel** [comment]
I can definitely make a separate PR for the example -- is there anything in particular that I can do to clean up TimeDistributedMerge/Merge?

**Comment by jmhessel** [comment]
(I will submit a PR for the demo if/when time distributed merge is pulled)

**Comment by jmhessel** [comment]
@fchollet Sorry to bother you, I know you're very busy -- is there something I can do for this PR? What would you like to see?

**Comment by fchollet** [comment]
@jmhessel you can simply remove the example for now. I will review the PR within a couple days.

**Comment by jmhessel** [comment]
See #684 for the merge updates only.

**Pull request closed without merging**
