### PR TITLE
Simple scipy.sparse input

### PR DESCRIPTION
**Pull request by richard27950**
This adds scipy.sparse input functionality. Test included (adapted from test_sequential), all passing.
#2061

### CODE REVIEW

**Comment by EderSantana** [comment]
So basically this runs .toarray() before calling fit? Is there anything else that I'm missing? I mean, those are a lot of line to just transform sparse matrix to array, right? Maybe a `utils` method would be better than hard code it to `models.py`

**Comment by richard27950** [comment]
The problem is that I can't just transform the whole matrix to a dense array: in many cases it would be too big to hold in memory (that's why I'm using a sparse matrix in the first place). So I need to convert each mini batch to dense one at a time. It would be nice if Keras handled sparse matrices for all of the methods that might take in sparse data (fit, train_on_batch, predict, etc), hence all the lines of code.

**Comment by EderSantana** [comment]
I see, have you checkout the data generator shown in the Cifar10 example?
https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py

They also have a generator that does data transformation on the go and they do that without adding edge cases to `models.py`. I'm just thinking about what would make the solution scalable for more edge cases. At one point we won't be able to add them all to `models.py`

Let us get @fchollet here to hear what he thinks.

**Comment by richard27950** [comment]
Ah nice! No I hadn't seen that but I see what you mean now. Something like that could be a better solution, I agree.

**Comment by fchollet** [comment]
Won't merge it, because all of this code was already rewritten for Keras 1.0. But I will try to add sparse support there as well.

**Pull request closed without merging**
