### PR TITLE
Add HSV data augmentation in preprocessing/image.py

### PR DESCRIPTION
**Pull request by MartinThoma**
This commit was originaly made by Clara Eng (cengh) as Pull Request #4806

### CODE REVIEW

**Comment by MartinThoma** [comment]
I've tried it with

```
#!/usr/bin/env python

from keras.datasets import cifar10
import matplotlib.pyplot as plt
from keras.preprocessing.image import ImageDataGenerator

(X_train_raw, y_train_raw), (X_test, y_test) = cifar10.load_data()

n = 3
X_train = X_train_raw[:n] / 255.
y_train = y_train_raw[:n]

datagen = ImageDataGenerator(hsv_augmentation=(0.2, 0.5, 0.2, 0.5, 0.2))

generator = datagen.flow(X_train, y_train, batch_size=n, shuffle=False)
batch = next(generator)

fig = plt.figure(figsize=(4, 2))
for i in range(n):
    a = fig.add_subplot(n, 2, 2 * i + 1)
    a.imshow(X_train[i])  # non-augmented
    a = fig.add_subplot(n, 2, 2 * i + 2)
    a.imshow(batch[0][i])  # augmented
plt.show()
```

Imgur

Seems to work

**Comment by MartinThoma** [comment]
Besides one minor bug, I didn't change the pull request. I'm not sure where this needed to be "updated for the Keras 2.0 API."

**Comment by cengh** [comment]
I've updated my original pull request for the Keras 2.0 API in #6454. All checks are currently passing.

**Comment by fchollet** [comment]
Closing to due to lack of an appropriate API. Feel free to submit an API design proposal in the future, in case you are still interested in developing this feature.

**Pull request closed without merging**
