### PR TITLE
Caffe Conversion

### PR DESCRIPTION
**Pull request by pranv**
I was able to finally get some time to work on this. It turns out that Caffe does correlation rather than convolution like Theano. So the filters had to be flipped. With that in, I think it should all work just fine.

Here are the changes:

1. Started clean and fresh from current master branch. This removes all the unnecessary merge conflicts, and builds on the current layer APIs
2. Initial implementation used its own dimensional inference code. Since that is provided by the API now, I have used that. Some improvement in readability is seen.
3. Added extra comments in difficult parts. I know the code could be a lot simpler if we just chose a subset of models, like chainer, but this has to be so otherwise. This will probably be the messiest part of Keras.
4. Reduced generality for simpler use case that covers most of the general use cases. I think the original PR tried to do a *lot*. Both `caffemodel` and `prototext` are mandatory now. Network configuration is loaded form `prototext` and weights are loaded onto them from buffers stored in `caffemodel`. This can be used to generate modified networks also, by modifying the `prototext`. The weight conversion code could also be used in embedding models (like the one shown in ReadME), since that part is separate now.
5. Finally, probably the largest (by size) and controversial change was to include the `caffe.proto` file *IN* in this repo. This was motivated by recent changes in the caffe repo that broke some things. This cannot happen and it is only logical to have our own version on it somewhere (as suggested before, @fchollet's S3 storage maybe)

I think this should do it. Unfortunately, I don't have much time, so it'd be great if you tried it out soon and give me proper feedback so I can fix/improve anything. 

[@asampat3090, @phreeza, @EderSantana, @matsuyamax]

Cheers,
Pranav

### CODE REVIEW

**Comment by pranv** [comment]
anyone knows why build is failing? I did not touch any part of core codebase

**Comment by fchollet** [comment]
We had one flaky test. It's fixed now.

I will review this within the next two weeks.

**Comment by EderSantana** [comment]
This is really promising @pranv!!!

Yeah, a test might help indeed. Even if not a proper test (in the `unittest` sense) at least a sequence of steps that we can "manually" run to quickly get started validating the code.

**Comment by pranv** [comment]
I have a minimal inception net, probably with just 2 inception modules. It includes LRN, Pooling, Conv, and Dense layers. Since it is a graph, it encompass almost eveything.

But how what you recommend for splitting it up into simpler stage wise steps? The results in a couple of steps are really huge dictionaries!

**Comment by EderSantana** [comment]
@pranv it can a super small, something that Travis could download, build, classify and assert is in the precalculated output. Doesn't need to be fully trained and working, we just need to know it matches the output calculated with original caffe model.

**Comment by fchollet** [comment]
So are there any tests for this PR, even just a data-heavy test that cannot be turned into a unit test?

**Comment by pranv** [comment]
I have been and will be busy over the next few weeks with academic stuff and other things. Also, I recently updated my OS X which screwed up my caffe installation. Getting caffe to work on OS X is a real pain and takes a lot of time. So it is unlikely that I can get some tests setup for this in next few weeks.

**Comment by MarcBS** [comment]
Great work @pranv! This modification will be very useful for reusing any Caffe model.

I have been trying your code and it worked pretty well when converting the AlexNet model. But then I tried converting the GoogLeNet provided in the master branch of Caffe and it crashed:

```
model = caffe_to_keras('/media/HDD_2TB/CNN_MODELS/GoogleNet/train_val.prototxt', '/media/HDD_2TB/CNN_MODELS/GoogleNet/bvlc_googlenet.caffemodel', phase='test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lifelogging/code/keras/keras/caffe/convert.py", line 39, in caffe_to_keras
    config.input_dim[1:])
  File "/home/lifelogging/code/keras/keras/caffe/convert.py", line 146, in create_model
    model.add_node(Activation('linear'), name=name, inputs=input_layer_names, concat_axis=axis)
  File "/home/lifelogging/code/keras/keras/layers/containers.py", line 264, in add_node
    merge = Merge(to_merge, mode=merge_mode, concat_axis=concat_axis, dot_axes=dot_axes)
  File "/home/lifelogging/code/keras/keras/layers/core.py", line 309, in __init__
    raise Exception("'concat' mode can only merge layers with matching output shapes except for the concat axis")
Exception: 'concat' mode can only merge layers with matching output shapes except for the concat axis
```

Have you got any hint about which could be the problem?

**Comment by pranv** [comment]
Are you trying with the old keras? If I recall correctly, the way keras concatenated back then was along one fixed axis, although that was about to change. But I think this PR and branch are rather old and outdated.

**Comment by MarcBS** [comment]
So, you recommend using your PR on the older version of keras? Which version is it exactly?

**Comment by EderSantana** [comment]
did we give up trying to support caffe?

**Comment by MarcBS** [comment]
@EderSantana I have been working on @pranv 's code for converting Caffe models to Keras.
Adding again the LRN2D layer into Keras and applying some modifications on this PR it seems that now all the existent problems about converting Caffe's V2 models into Keras' Graph models have been solved. 

Although I do not know which would be the best way to proceed for publishing the code. @fchollet could you tell me what would be better?

**Comment by EderSantana** [comment]
Nice @MarcBS!!! Did you test the model? Can you submit a PR to Keras with tests here so we can review it?

**Comment by pranv** [comment]
I can't dedicate any time in this right now, but would be happy to clear any doubts you have with the code @MarcBS

**Comment by MarcBS** [comment]
I have just created a pull request #1669. And have also added a test for revision in /tests/keras/caffe/test_convert.py.

**Pull request closed without merging**
