### PR TITLE
CropImages to maintain sizes in CNN

### PR DESCRIPTION
**Pull request by pjadzinsky**
Convolution2D only has border_mode='Full' or 'valid' and the image size changes upon convolution. I added a layer that allows to shrink the image after using Convolution2D with border_mode='Full' back to the original size (before the Convolution2D)

Example, assume images are 28x28 as in the mnist example

model.add(Convolution2D(32, 1, 3, 3, border_mode='full'))   # images are now 30x30 
model.add(Activation('relu'))
model.add(CropImage(1))                                     # images are now 28x28

Thanks for a great package

### CODE REVIEW

**Comment by fchollet** [comment]
What would you think of adding support for `border_mode = same` instead?

**Comment by pjadzinsky** [comment]
I'd love to, but don't know how to do it. Can you help me figure it out?

**Comment by fchollet** [comment]
I believe Lasagne supports it. Looking at the source, this seems to be the relevant bit: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/conv.py#L441

Basically, setting border_mode to full and resizing the output after the fact. Very simple and straightforward.

**Comment by pjadzinsky** [comment]
Thanks, I've looked at the code. Is not very elegant but does the trick. Thanks for the help.

**Comment by pjadzinsky** [comment]
Ok, thanks for the help. This is basically what the CropImage function did. Let me know what you think now and if you would do anything differently

**Comment by fchollet** [comment]
Looks good, I updated the doc and the standardized the style. It's merged.

**Comment by jonilaserson** [comment]
Thanks for the change!
Wouldn't it be less computationally intensive to pad with zeros before
calling conv2d and then use a *valid* border_mode (perhaps by using the
newly ZeroPadding2D Layer?

**Pull request merged**
