### PR TITLE
Leverage native channels_first support when a GPU is available in TF.

### PR DESCRIPTION
**Pull request by fchollet**
This PR tries to check if a GPU device is available, and if so, works under the assumption that conv and pooling ops will be executed on GPU, thus allowing the native use of NCHW layout when using the channels_first data format, in TensorFlow.

This is not a fully reliable way to check for GPU execution, but I believe this is the best we have now.

@TimZaman maybe you have thoughts about how to improve it?

### CODE REVIEW

**Comment by TimZaman** [comment]
Ah you could have pinged me and I would have gladly done this for you. I thought there was a better implementation that was coming from TF. Anyway, I reviewed your code, and you're not capturing when ops have been placed explicitly on cpu: then, it should still do your transpose roundtrip, in the way it always has.

**Comment by TimZaman** [comment]
I.e. in your `conv2d` I've got this:
`nhwc_roundtrip = not has_nchw_support() and tf_data_format == 'NCHW'`

where:

```python
def has_nchw_support():
    """Check whether the current scope supports NCHW ops.

    Tensorflow does not support NCHW on CPU. Therefore we check if we are not explicitly put on
    CPU, and have GPUs available. In this case we will be soft-place on the GPU. The case that
    we're currently explicitly on GPU would also allow NCHW.

    Returns:
        bool: if the current scope device placement would support nchw
    """
    explicitly_on_cpu = maglev.framework.tensorflow_backend.is_current_explicit_device('CPU')
    gpus_available = len(maglev.framework.tensorflow_backend.get_available_gpus()) > 0
    return (not explicitly_on_cpu and gpus_available)
```

where:

```python
def is_current_explicit_device(device_type):
    """
    Check if the current device is explicitly set on the device type.

    Args:
        device_type (str): 'GPU' or 'CPU'
    Returns:
        bool: if the current device scope is explicitly set on the device type.
    """
    device_type = device_type.upper()
    if device_type not in ['CPU', 'GPU']:
        raise ValueError('device_type should be either "CPU" or "GPU".')
    device = get_current_tf_device()
    return (device is not None and device.device_type == device_type.upper())


def get_current_tf_device():
    """Return device string of current graph context that's explicitly, otherwise returns `None`."""
    g = tf.get_default_graph()
    op = _TfDeviceCaptureOp()
    g._apply_device_functions(op)
    return op.device


def get_available_gpus():
    """Get a list of available gpu devices (formatted as strings)."""
    return [x.name for x in LOCAL_DEVICES if x.device_type == 'GPU']
```

**Comment by fchollet** [comment]
Oh cool, this looks much better! Would you like to open a PR? If so, I'll close this one and merge yours.

**Comment by TimZaman** [comment]
Aye, aye! Will give it a shot tomorrow. Question: would you mind having the boolean flag `nhwc_roundtrip` here and there?  (ex: `conv2d`, `conv2d_transpose`) and also `bias_add` uses `has_nchw_support()`.

**Comment by fchollet** [comment]
Yes, that sounds fine. Thank you!

**Comment by TimZaman** [comment]
By the way, here's the speed up you can expect with a ResNet50-like network:
nchw-patches_bn-not-patched
vanilla

**Pull request closed without merging**
