### PR TITLE
Update imdb_cnn.py to use GlobalMaxPooling1D

### PR DESCRIPTION
**Pull request by jtdoepke**
The imdb_cnn.py example is uses `MaxPooling1D(pool_length=model.output_shape[1])` for pooling. Changed it to use GlobalMaxPooling1D instead.

### CODE REVIEW

**Comment by carlthome** [comment]
Why?

**Comment by fchollet** [comment]
LGTM

> Why?

It's simpler.

**Comment by farizrahman4u** [comment]
> Why?
And faster.

**Comment by carlthome** [comment]
Cool

**Pull request merged**
