### PR TITLE
Stateful RNN example with the functional model

### PR DESCRIPTION
**Pull request by jpeg729**
I had trouble figuring out what parameters to pass to Input in order to make my stateful LSTM layer work.

Here I propose a working example to add to the guide.

### CODE REVIEW

**Comment by carlthome** [comment]
Woudn't it be better if Input() with the Functional API was more similar to the Sequential API and vice versa? See this discussion https://github.com/fchollet/keras/issues/4130

**Comment by jpeg729** [comment]
I consider myself lucky to have found the answer so quickly. I would have liked to find a working example. For those who prefer examples to sifting through documentation, it would be useful.

The error message complained about the first lstm layer not getting the right shape input. Maybe the error message could suggest this issue which is probably fairly common among those who try making stateful RNNs using the functional model.

A quick review of the state of the docs.
The page on [recurrent layers](https://keras.io/layers/recurrent/) has the info I wanted. Dunno why I didn't look there.
The section of the FAQ on [using stateful RNNs](https://keras.io/getting-started/faq/#how-can-i-use-stateful-rnns) mentions only `batch_input_shape` for the Sequential model. Maybe I could add that for you.

**Comment by fchollet** [comment]
> I had trouble figuring out what parameters to pass to Input in order to make my stateful LSTM layer work.

What was your issue, specifically?

**Comment by jpeg729** [comment]
Well I started by reading the guide to the functional model.
And I copied the examples 
```python
input = Input(shape=(input_size,))
```
Then I tried
```python
input = Input(shape=(batch_size,tsteps,input_size,))
```
Then I tried the Sequential model's way of doing it.
```python
input = Input(shape=(input_size,), batch_input_shape=(batch_size,tsteps,input_size,))
```
And I tried various variants of these.

I didn't think to re-read the docs because I am already reasonably conversant in keras, but I did look for an example, and not finding one I searched the github issues for clues.

**Comment by fchollet** [comment]
Closing outdated PR. If you still care about the content of the PR, please submit a new PR to `master`, updated for the Keras 2.0 API.

**Comment by jpeg729** [comment]
This PR wasn't going anywhere anyway.

**Pull request closed without merging**
