### PR TITLE
Create Gaussian Noise layer

### PR DESCRIPTION
**Pull request by Reddine**
Reference : `Vincent, Pascal, et al. "Stacked denoising autoencoders: Learning useful representations in a deep network with a local denoising criterion." The Journal of Machine Learning Research 11 (2010): 3371-3408.`

### CODE REVIEW

**Comment by fchollet** [comment]
Cool! I'm wondering if this belongs among the core layers, though. I remember that at some point we discussed the possibility of introducing a "noise" module. If there was such a module, what other layers would be in it? (I like having Dropout in core, though).

**Comment by Reddine** [comment]
may be as mentioned in the Reference article: Masking Noise (same principle of Dropout) and Salt-and-pepper Noise.

**Comment by pranv** [comment]
Neat!
I think that Noise can have its own module. The paper - [Deep Learning with Noise] (http://www.andrew.cmu.edu/user/fanyang1/DLWN.pdf) has many versions of noise - not just Gaussian. Having the entire family might be useful.

**Comment by fchollet** [comment]
I put it in a noise module.

**Pull request merged**
