### PR TITLE
added the ability to have frozen layers in models

### PR DESCRIPTION
**Pull request by iamtrask**
Disclaimer, I'm new to the library but I think it's great. Based on what I know of Theano, this technically does the job.

### CODE REVIEW

**Comment by EderSantana** [comment]
@iamtrask you can do that by deleting `layer.params` before compiling the model. How is your solution different from that?

**Comment by fchollet** [comment]
Yes, precisely you could set `layer.params = []` before calling `.add(layer)`. The effect would be the same.

**Comment by iamtrask** [comment]
I like your deletion solution better. Any objections to parameterizing it? Seems like it would be more intuitive.

**Comment by fchollet** [comment]
> Any objections to parameterizing it?

The fact that it would require modifying every single layer to support it. It's a fairly niche use case.

**Comment by iamtrask** [comment]
In order for this library to be useful for NLP, it needs to be able to support pre-trained embeddings that it doesn't alter. If that's not a priority, I understand, but neural networks are quite ineffective without pre-trained embeddings for processing natural language.

**Comment by iamtrask** [comment]
(maybe just the embedding layer?)

**Comment by EderSantana** [comment]
that's not what we mean. What we mean is you CAN already do what you are suggesting. You just have to make the list `layers.params` empty and none of its weights will be updated. This way, you don't have to change the API and break the layers of several people out there.

**Comment by EderSantana** [comment]
ex 
```python 
fixed_layer = Dense(10, 10)
fixed_layer.params = [] # this layer's parameters won't change

model.add(layer_fixed)
model.add(Dense(10, 10)) # this one will be updated
model.compile ...
```

**Comment by iamtrask** [comment]
Very good. Thank you sir!

**Pull request closed without merging**
