### PR TITLE
Fixed ProgBar-Logger by removing \b call

### PR DESCRIPTION
**Pull request by apacha**
See https://github.com/fchollet/keras/issues/5906 for more details.

### CODE REVIEW

**Comment by fchollet** [comment]
`\b` is the ASCII backspace character: https://docs.python.org/2/reference/lexical_analysis.html#grammar-token-stringliteral

It clears the remainder of the line, which is necessary because the current line maybe be shorter than the previous line. It is unfortunate that Windows terminals do not know how to handle backspaces, but that does not change the fact that it should be printed.

**Comment by apacha** [comment]
I am well aware what the `\b` character is! Did you read the description in the issue? There is another `\r` call, coming right after the `\b`s that clears the line anyway. So what exactly is the use of the `\b`s apart from breaking the expected behavior of the progress bar? 

Actually removing the `\b`s fixed the behavior on Linux and Windows. 

See http://stackoverflow.com/a/3249684/448357 and https://stackoverflow.com/questions/5598181/python-print-on-same-line for printing in the same line ... maybe we should switch to print instead of sys.stdout.write anyway.

**Comment by apacha** [comment]
I've just double-checked: `\b` is not required at all. If the line printed before was longer, it will be erased anyway with `\r`. Run this snippet to check it out:

```
import time
import sys

for i in range(0,50):
    sys.stdout.write('\r')
    sys.stdout.write(str(i) + (50-i)*'*')
    sys.stdout.flush()
    time.sleep(0.5)
```

**Comment by fchollet** [comment]
@apacha your own snippet fails on my side (constant line of 50 characters being displayed), which confirms the need of the backslash character on Unix systems (95% of Keras users).

**Comment by titu1994** [comment]
Since it is a problem for just Windows users, why not simply check whether the Windows OS is being used, and if so, do not print the \b line ? 

That's seems like a good enough compromise for Windows users, and doesn't harm Linux / MacOSX users.

**Comment by apacha** [comment]
@fchollet: what kind of Unix are you using? I've tested it with Ubuntu 16.04 inside of PyCharm 2016.3.3 and I experienced the described problem. After removing that line, it was fixed on Ubuntu and Windows.

**Comment by juharris** [comment]
Even on Windows (tested in MinGW), with a narrow terminal, this change causes the line to be re-written every time.

**Comment by apacha** [comment]
@juharris indicating that this PR fixes the issue?

**Comment by juharris** [comment]
@apacha No this PR will not fix the issue for a terminal that is too narrow.  For example, the result of running your code:
```
0*******************************
1*******************************
2*******************************
3*******************************
**************
```

Tested in MinGW and cmd.

**Comment by apacha** [comment]
Then the question is, whether there is any way, that works for all
operating systems and conditions...

**Comment by juharris** [comment]
I usually use [tqdm](https://github.com/tqdm/tqdm) to do this type of thing.  We could try using that here but it might not be able to handle some of the custom stuff done in here.

**Comment by ramadawn** [comment]
This problem can be fixed simply by making your terminal window wider.

**Comment by apacha** [comment]
@ramadawn Nope. And why are you Copy-Posting the same text to related threads?

**Pull request closed without merging**
