### PR TITLE
Speed up Theano tests

### PR DESCRIPTION
**Pull request by taehoonlee**

### CODE REVIEW

**Comment by taehoonlee** [comment]
There is no intention to steal the contribution of #6934. After seeing the failed tests, I just wondered how effective the idea will work. With the flag (`THEANO_FLAGS=optimizer=fast_compile`), the Theano tests are about [twice](https://travis-ci.org/fchollet/keras/builds/243667172) as fast as [before](https://travis-ci.org/fchollet/keras/builds/243049817). Why don't you commit again like this, @Dref360?

**Comment by taehoonlee** [comment]
Two tests in `backend_test.py` were temporarily blocked due to errors that can not be solved immediately.

**Comment by Dref360** [comment]
Reopen your PR :P I really don't mind about Github points. :P You manage to fix it. 
This is GREAT!

**Comment by taehoonlee** [comment]
This PR modifies #6934 slightly (`mode=FAST_COMPILE` to `optimizer=fast_compile`). The idea was proposed by Bob and looks very cool!

**Comment by taehoonlee** [comment]
This PR modifies #6934 slightly (mode=FAST_COMPILE to optimizer=fast_compile). The idea was proposed by @Dref360 and looks very cool!

**Comment by fchollet** [comment]
Sounds great. LGTM

**Pull request merged**
