### PR TITLE
Api conversions/zeropadding cropping

### PR DESCRIPTION
**Pull request by fredtony**

### CODE REVIEW

**Comment by fchollet** [comment]
Great job, thanks! Are there any remaining layers that we are missing?

**Comment by fredtony** [comment]
@fchollet There are still a few stragglers. I messed around for awhile with trying to get ZeroPadding1D to work with a conversion interface because there is only one case in which it will cause an error when the `mapping` argument is a dictionary. I could not find any way to get it to pass through the legacy conversion function since the argument names are all the same.

Other than that, there are a few layers left in core.py: all 3 SpatialDropout layers and Lambda. I'm thinking I can get through those tonight.

The Merge layer does not look like anyone has created a conversion yet and will probably be a bit more messy since it looks a bit different in Keras 2 from what I can tell.

**Comment by fchollet** [comment]
The legacy `Merge` layer is supported simply by having it live in `legacy/layers.py`.

> SpatialDropout

There was only the `rate` argument IIRC. Since it inherits from dropout we may not have to do anything --but let's add a test.

**Comment by fredtony** [comment]
It failed a test when I checked, so added the conversion functions in and works now. I'll submit the pull request shortly.

**Pull request merged**
