### PR TITLE
Tensorflow backend Function class __init__() and __call__() error handling + fetches + feed_dict

### PR DESCRIPTION
**Pull request by ahundt**
The TF backend Function now checks the None values present, puts them in the appropriate input, and raises a ValueError if there is a problem.
small part of #6928 and #7046

 - Feed dict and fetches can be passed to the backend
 - Error messages are clearer
 - This is necessary to sort placeholders from ops.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
@ahundt, could you squash/remove commits into a clean history on top of master? It is a bit difficult to review these commits when some of them reverse others.

E.g. I would separate typo fixes from cleanup from semantic modifications.

If rebasing is not ok for you on a public branch, I would create a new branch with the rebased commits, and create a new PR it.

**Comment by ahundt** [comment]
@jorgecarleitao Thanks for taking a look! https://github.com/fchollet/keras/pull/7064/files shows everything as a single diff. I merged with master at least, don't have the free cycles for squash/rebase process at the moment. Sorry about that!

**Comment by ahundt** [comment]
Improvements made based on https://github.com/fchollet/keras/pull/8286

**Comment by ahundt** [comment]
@fchollet updated for consideration due to #8286

**Comment by TimZaman** [comment]
I think this one can be closed now #8286 is merged.

**Comment by ahundt** [comment]
Closing because equivalent functionality was merged in #8286

**Pull request closed without merging**
