### PR TITLE
deconvolution2d with @yaringal

### PR DESCRIPTION
**Pull request by EderSantana**
a version of #3251 (hopefully) without conflicts

### CODE REVIEW

**Comment by EderSantana** [comment]
what is done:
Deconvolution2D with example tested under theano and tensorflow

what is not done:
Tensorflow verion forces batch_shape (just like RNNs), but I didn't add a warning yet
didn't change subsample to stride
didn't find a way to do automatic shape inference for the deconv operation

**Comment by fchollet** [comment]
@yaringal do you want Github credits for your part of the code? If so, we should decompose it into commits that we can assign to you. It can be done a posteriori.

**Comment by EderSantana** [comment]
@yaringal you could also just paste all these diffs to a PR of yours, my own modifications were pretty minor and only in the TF side.

**Comment by yaringal** [comment]
Apologies for not answering - I've been travelling the past few days with no internet access. How should we proceed? adapt code on this PR, on #3251 merged with latest, or open a new PR with latest code?

**Comment by EderSantana** [comment]
Moving all operations to #3251

**Comment by yaringal** [comment]
@EderSantana yep!

**Pull request closed without merging**
