### PR TITLE
Some more testing of Siamese layer

### PR DESCRIPTION
**Pull request by phreeza**
I noticed that some of the core layers are being tested from test_models.py, and the tests actually look more like integration tests. This PR is a start to addressing this.

### CODE REVIEW

**Comment by phreeza** [comment]
Failing for some weird reason, seems like a glitch. Not related to my changes.

**Comment by fchollet** [comment]
> Not equal to tolerance rtol=1e-07, atol=0

Only partially a glitch, since rtol should always be set to 1e-5 in tests (since we use float32 and most comparisons require some margin of error). Just fixed it.

**Comment by fchollet** [comment]
Looks good to me.

**Comment by fchollet** [comment]
On OSX, the tests for Siamese are failing with TensorFlow:

```
        for i in range(1, n):
            s += self.get_output_at(i, train)
>       s /= n
E       TypeError: unsupported operand type(s) for /=: 'Tensor' and 'int'

keras/layers/core.py:1591: TypeError
```

The issue does not seem to occur with the Linux version of TensorFlow.

**Comment by farizrahman4u** [comment]
@fchollet Are you not getting any errors for `Merge avg` on your mac? If that operator isn't defined then `Merge avg` should also not work..Mine is a PC so can not reproduce.

**Pull request merged**
