### PR TITLE
Remove "Using TensorFlow backend." message

### PR DESCRIPTION
**Pull request by wh0**
I've encountered an inconvenience with the automatic printout of the backend, and I find the suggestions on how to work around it (e.g. redirect stderr) to be unsatisfactory.

This PR (somewhat boldly) proposes something that can be done. Please treat it as a starting point.

Argument for the outright removal of these lines: this information seems not very useful and easily accessible through other means.

### CODE REVIEW

**Comment by ahundt** [comment]
perhaps just read an env variable to check if the user wants it printed or not?

**Comment by bdwyer2** [comment]
I think you should add a note somewhere in the documentation about this, maybe in the FAQ.

**Comment by ahundt** [comment]
I suggest making it consistent with the other backend settings, and reading it from the keras json file

**Comment by fchollet** [comment]
The backend logging is useful and innocuous. We'll keep it for now.

**Comment by wh0** [comment]
The current PR does keep the backend logging.

**Pull request closed without merging**
