### PR TITLE
Use `type()` and `isinstance()` instead of `obj.__class__.__name__`

### PR DESCRIPTION
**Pull request by lgautier**
Use `type(obj)` and `isinstance(obj, SomeClass)` to test if objects are of a specific class rather than use equality with `obj.__class__.__name__`.

The use of `isinstance` is arguably better for modularity because is also users to implement child classes and use them seamlessly.

### CODE REVIEW

**Comment by fchollet** [comment]
Some of these are arguably cleaner with string comparison, especially if you look at their context (it wouldn't provide added generality or robustness to do an instance check). I disagree with the changes in `keras/engine/training.py` and `keras/engine/topology.py`. The others seem reasonable.

**Comment by lgautier** [comment]
@fchollet : Thanks for looking that patch. I understand that there are many ways check for the validity of input, and all can have their respective merits.  I am suggesting the change because of the following. 

Checking for instances rather than string equality on class names would provide:

- added generality by allowing users to have child classes. For example the following class `MyConvolution1D` would not work well with keras (while it would with the pull request).

```python
class MyConvolution1D(Convolution1D):
    def __repr__(self):
        print('Override default representation of the object')
    def to_html(self):
        # for example for jupyter notebook
        pass

```

- added robustness. The following class would pass the test `__class__.__name__ == 'Convolution1D'`, but it really should not. If inheritance is believed to create more harm than good, `type(obj) is Convolution1D` would be more robust.

```python

class Convolution1D(object):
    # do nothing this is just a class that happens to be called Convolution1D
    pass

```

The change in training is somewhat unorthodox (the definition of a nested class `Graph`) because I wanted to keep the important part of the change (check for instances, not string equality) simple.

**Comment by carlthome** [comment]
👍

**Comment by fchollet** [comment]
Closing outdated PR. These issues have been fixed since.

**Comment by lgautier** [comment]
@fchollet :
> These issues have been fixed since.

May be not all the case: "branch has unmerged commits" (confirmed by a visual check of master).

As time passed the PR grew in size by including a number of upstream fixes in `fchollet/keras` (without which GitHub complained about the PR being out-of-sync with upstream repos).

I can put the relevant changes in a fresh PR if making areview of the PR easier.

**Pull request closed without merging**
