### PR TITLE
Added output from intermediate layer to FAQ

### PR DESCRIPTION
**Pull request by kilotaras**

### CODE REVIEW

**Comment by kilotaras** [comment]
I'm pretty sure that I answered this question at least twice in gitter, #4351 is the same question

**Comment by longma307** [comment]
I used this for training
    
    model = Model(input=[input_a, input_b], output=distance)
    model.fit([x1,x2],y)

and I used the following for predicting the output of input:

    extraction = Model(input=[input_a, input_b], output=[processed_a,processed_b])
    extraction.predict([x1,x2])

Are they correct? From my understanding, they are different models, is it meaning that we got the output without training?

**Comment by kilotaras** [comment]
Model is an abstraction over underlying computation graph. Because the graph is shared between both models the second one will use trained weights form first model (which are just variable nodes somewhere in  the graph).

**Comment by longma307** [comment]
@kilotaras Thanks, that makes sense.

**Comment by fchollet** [comment]
This is already part of the FAQ and has been there for over a year.

**Pull request closed without merging**
