### PR TITLE
Callback <-> Model message passing

### PR DESCRIPTION
**Pull request by tdhd**
Hi,

this is the PR I mentioned in #213.

A brief summary of what I did:
- make https://github.com/ReactiveX/RxPY a dependency of keras (lightweight reactive extensions for python)
- with `rx` I added a communication channel to every callback and the model class
- these channels replace the callback logic which was implemented earlier
- every object can now subscribe to certain events either from the callbacks or the model (or basically any object which has such a channel)
- ported all existing callbacks to use the channel to subscribe and to publish messages

To describe in a little more detail:

`Model` now has `self.pub_stream` to which callbacks can subscribe, to receive messages like `TrainBegin` and so on. As before the `Model.fit` receives a list of callbacks. Inside `fit`, all passed callbacks are notified of the event source (which is `self.pub_stream` of `Model`) and in turn the model subscribes to events like `StopTraining` and `SaveModel`. These are currently the only events we had to include.
To subscribe, take `callback.pub_stream` (the output channel of the callback), filter all messages down to a single type, for instance `StopTraining`, and then subscribe to the filtered stream of messages. All messages received are now of instance `StopTraining`.
During the training the model emits the newly added messages from `messages.py` to it own channel by calling `on_next`. Since the callbacks are all subscribed to the messages they are interested in, they will be notified when the model publishes a message. In turn the model receives all events it needs to know about from the callbacks.
In a GUI, events can be received and sent in the same manner as they are with the callbacks at the moment.

With this, the model is decoupled a lot better from the callbacks than it was before. All of the callbacks, except for the `DrawActivations` one in `test_callbacks.py` (which I will probably fix) don't have a copy of the model object anymore. No methods of the model are called directly but are accessed through passed messages.

In this PR I had to remove the performance measurements of the callbacks which were done by `CallbackList`, sorry. :) Maybe there is way to measure it with the streams too.

About the docs: It would be a good idea to avoid referring to this as callbacks. They are not callbacks anymore. :) I can write up documentation for the current implementation.

If you have any questions, please let me know.

### CODE REVIEW

**Comment by fchollet** [comment]
There's a lot going on, so this will take some time to review. But here are a few initial comments:

> make https://github.com/ReactiveX/RxPY a dependency of keras (lightweight reactive extensions for python)
> with rx I added a communication channel to every callback and the model class
these channels replace the callback logic which was implemented earlier
> every object can now subscribe to certain events either from the callbacks or the model (or basically any object which has such a channel)
> ported all existing callbacks to use the channel to subscribe and to publish messages

What do you think Rx brings compared to the previous callback system? The use case for Rx seems to be high-throughput event-based concurrent applications, whereas training a Keras model only a few event types (unlikely to increase) which are not called that frequently, and are not called concurrently. Couldn't we achieve the same result while avoiding introducing a new dependency and new code conventions? 

Concretely, isn't the existing callback system good enough (while being simple and explicit), and wouldn't adding 2-way communication just be a matter of having callback methods return messages, and these messages being then read and acted upon by the model?

>  Since the callbacks are all subscribed to the messages they are interested in, they will be notified when the model publishes a message.

Under the hood, isn't this implemented in fundamentally the same way as the previous system? 

> All of the callbacks, except for the DrawActivations one in test_callbacks.py (which I will probably fix) don't have a copy of the model object anymore. No methods of the model are called directly but are accessed through passed messages.

It seemed to me that letting callbacks have a pointer to the original model offered the maximum flexibility, which I assume we are going to need when building visualization UIs. The DrawActivations callback was a great example of that. We don't what we are going to need, so we might as well reserve ourselves the possibility to do absolutely anything. Unless there is a solid reason not to.

**Comment by tdhd** [comment]
Thank you for taking the time to review this. I know it's quite some change but I think it is worth to look into it.

> What do you think Rx brings compared to the previous callback system? The use case for Rx seems to be high-throughput event-based concurrent applications, whereas training a Keras model involves only a few event types (unlikely to increase) which are not called that frequently, and are not called concurrently. Couldn't we achieve the same result while avoiding introducing a new dependency and new code conventions?

One of the main reasons I think it would be useful is its decoupling nature. The model and it's attached listeners are only communicating via streams of messages which makes sense even in a single threaded application. It much cleaner also.
Another reason is symmetry. With the streams the model and callbacks are equally involved in the process of sending/receiving. In the current implementation, as it is right now in keras, only the model receives via return values and the callbacks receive their 'messages' via their function parameters.
Third reason is ease of extensibility. With this approach, message passing to and from a GUI can be as easily implemented as with the callbacks/listeners. This depends on the GUI you want to use of course.
I don't like introducing a new code convention much, but ultimately I think it makes sense to do so because of the reasons above. The new dependency is really lightweight, `rx` does not have dependencies itself.

> Concretely, isn't the existing callback system good enough (while being simple and explicit, which are good things), and wouldn't adding 2-way communication just be a matter of having callback methods return messages, and these messages being then read and acted upon by the model?

While I agree to a certain degree that the current system is good enough for the functionality it has to cover right now, I would not agree that this approach is suitable if it should handle GUI events also.

> Under the hood, isn't this implemented in fundamentally the same way as the previous system? 

The difference is that the listeners are notified and not called directly. They explicitly tell you what messages they are going to react to. In that manner you can only communicate with them via those messages, which makes their behaviour more expressive. Another difference is that responses are handled also via messages and the model does not have to parse through, possibly, a list of commands to execute and take action immediately.

> It seemed to me that letting callbacks have a pointer to the original model offered the maximum flexibility, which I assume we are going to need when building visualization UIs. The DrawActivations callback was a great example of that. We don't know what we are going to need, so we might as well reserve ourselves the possibility to do absolutely anything. Unless there is a solid reason not to.

Keeping the model reference in the callbacks allows for the most flexibility, that is true. If the model would not be kept, every time a new member or method would need to be invoked by the listeners would basically require a new message. This sounds bad at first and makes more code for the same effect. But I also think it makes the code more robust and explicit about its intentions.

---

I am coming from a reactive programming background and therefore think using `rx` would be a good choice, design-wise. When I think about event based programming, like the callbacks and GUI is, I think about streams of messages and how to handle them.

You can achieve 100% of what you said in the current, callback based, implementation. Basically it just comes down to how you want to handle it for this project. :)

**Comment by fchollet** [comment]
I see how the approach is valuable. However, I also believe that new dependencies should only be introduced if they absolutely must.

> The new dependency is really lightweight, rx does not have dependencies itself.

If rx is pure Python, then couldn't we isolate the subset of its functionality that we are going to use, and introduce that bit of code as a Keras util? Just an idea.

**Comment by tdhd** [comment]
Yes rx, is pure python and it would be possible. If you plan to include the reactive extensions as a keras util, the included code would have an extra overhead of maintaining. As it turns out, the subset of code required to include subjects is quite large: about 1200 LOC would have to be added to the codebase. I don't think that it should be done.

Introducing the rx dependency is not an absolute must, using the callback semantics + return values serves it current purpose quite good. However, including rx would give keras a clean abstraction for message passing.

As I said earlier, I see your point and understand it. After all, it can be done both ways.

**Comment by fchollet** [comment]
> As it turns out, the subset of code required to include subjects is quite large: about 1200 LOC would have to be added to the codebase. I don't think that it should be done.

Indeed, 1200 LOC (or an even larger dependency) is not a reasonable amount of complexity to add to the project in order to handle 2-ways message passing between models and callbacks. 

For comparison, the existing callback system is ~220 LOC. I believe we can achieve message passing with minimal changes to the current setup. Again, the core value of Keras is simplicity, and minimizing the size of the codebase and the amount of dependencies is part of that.

Two things we could potentially do:
- have callbacks set flags on the model object, such as `model.stop_training`. The main training loop would then check these flags at every loop, possibly even every batch, and take action
- have callback methods return a list of string flags, such as `['STOP_TRAINING']` (not the most elegant, we can think about something better). The main training loop would then go through the result of the callback method and take action.  

I would favor the first method.

**Comment by phreeza** [comment]
Can someone explain to me how this all makes sense in python, in the light of the GIL? Since python has no multithreading, how can the callback set a flag on an object (o a message be emitted, or anything really) while a different part of the code is running (ie the training loop is running)?

**Comment by tdhd** [comment]
> For comparison, the existing callback system is ~220 LOC. I believe we can achieve message passing with minimal changes to the current setup. Again, the core value of Keras is simplicity, and minimizing the size of the codebase and the amount of dependencies is part of that.

Yes, agreed. Also I would prefer using setting variables in the model which would have to be checked inside the model functions.

> Can someone explain to me how this all makes sense in python, in the light of the GIL? Since python has no multithreading, how can the callback set a flag on an object (o a message be emitted, or anything really) while a different part of the code is running (ie the training loop is running)? 

Yes, the GIL prevents python from running multiple threads. For that reason setting a flag in the model would only be checked after the callback has finished running. The same applies for message passing via subjects in rx. They are all processed sequentially.

**Comment by fchollet** [comment]
I have added an `EarlyStopping` callback that works by way of setting a `model.stop_training` flag. In the future, I suggest we keep working under this (extremely simple) model, at least until issues arise (you never know). Then we will be able to use our experience to figure out a better way.

**Comment by tdhd** [comment]
Yes, I agree. Keeping it simple is good.

**Pull request closed without merging**
