### PR TITLE
Make tensorflow backend fully mimic theano.dot

### PR DESCRIPTION
**Pull request by the-moliver**
This should make the Tensorflow backend fully mimic the broadcasting semantics of the theano.dot function. Hopefully passing all tests now.

### CODE REVIEW

**Comment by fchollet** [comment]
There's one test that appears to be failing. Most likely related. Unclear why.

**Comment by the-moliver** [comment]
Seems to be due to differences in ```None``` handling between Python2 and Python3. Ugh

**Comment by the-moliver** [comment]
Fixed! This issue was during the recursion test ```ndim(x)``` was returning ```None``` due to a placeholder variable, and ```None```doesn't like to be compared to integers in Python3.

**Comment by fchollet** [comment]
Cool! LGTM.

**Pull request merged**
