### PR TITLE
Set theano as default backend for windows users

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by carlthome** [comment]
I assume this is because TensorFlow doesn't exist for Windows (yet?)?

**Comment by farizrahman4u** [comment]
yes

**Comment by carlthome** [comment]
Perhaps add a comment with that information around the if switching, in case TensorFlow ever becomes available? :+1:

**Comment by farizrahman4u** [comment]
ok

**Comment by fchollet** [comment]
LGTM

**Comment by Deepak-** [comment]
I'm using TensorFlow. I changed theano to tensorflow in the if switch, however, when trying to import keras it still defaults to theano?

**Pull request merged**
