### PR TITLE
Modification of ModelCheckpoint to allow monitoring of increasing metrics

### PR DESCRIPTION
**Pull request by jeanpijon**
added keyword argument `monitor_direction` to allow increasing metrics be used along with `ModelCheckpoint`

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks, but we already have a PR out for this feature: https://github.com/fchollet/keras/pull/674

**Comment by jeanpijon** [comment]
Hi, I've just checked out that PR, but my code is not for early stopping - it is for model saving. More, it is unclear to me, how to achieve same behavior with PR you mentioned.

**Comment by fchollet** [comment]
It's the same feature, applied to a different callback. We definitely want the same API for the same feature on these two callbacks, for consistency. You could resubmit a PR for this feature with a unified API.

**Comment by jeanpijon** [comment]
OK, new version with new API in #860

**Pull request closed without merging**
