### PR TITLE
Highway Network for 3D data.

### PR DESCRIPTION
**Pull request by farizrahman4u**
A hybrid of TimeDistributedDense and Highway.

### CODE REVIEW

**Comment by fchollet** [comment]
I think what we should do is develop wrapper layers `TimeDistributed` and `Highway` (and also `Residual`). So that you could implement the layer in this PR as:

```python
model.add(TimeDistributed(Highway(Dense(32))))
```

**Comment by lukedeo** [comment]
@fchollet just so I know what you're getting at, doing (for example) `Highway(Highway(Dense(32)))` would simply add two highway layers?

**Comment by farizrahman4u** [comment]
@fchollet @lukedeo Checkout #1456

**Comment by farizrahman4u** [comment]
Closing this. I will be working on the more general `Highway` wrapper.

**Pull request closed without merging**
