### PR TITLE
A first trial of input layer

### PR DESCRIPTION
**Pull request by ipod825**
A first trial for #1980
Not fully done yet. Many layers' __init__ should be checked if #1980 is to be done.

### CODE REVIEW

**Comment by ipod825** [comment]
I don't quite understand the mechanism and the purpose of `__call__` of `Layer`

**Comment by ipod825** [comment]
@fchollet , this PR will be a big one. It will take much effort for me to solve all the problems, so please check if you agree with my idea.

**Comment by NasenSpray** [comment]
Why do we need an input layer?!

> I don't quite understand the mechanism and the purpose of __call__ of Layer

It returns the computational graph of the layer applied on the passed input. It's mostly for advanced users.

**Comment by fchollet** [comment]
Keras is currently undergoing a rewrite which would make this PR obsolete.
There is no need to work on it further.

Input layers will be coming in Keras 1.0 (scheduled for release early
April).

**Comment by NasenSpray** [comment]
@fchollet: will there still be something like `__call__`? please say yes :D

**Comment by ipod825** [comment]
Well, good to hear the news.

**Pull request closed without merging**
