### PR TITLE
New LSTM Layer, TimeStepLSTM

### PR DESCRIPTION
**Pull request by slaterb1**
This PR is adds a new layer to Keras to allow people to build more complicated LSTM networks where someone may want to adjust the input to the network at a later step and/or act on the states returned by the LSTM immediately. With this layer it is possible to build more types of RNN architectures (one-to-many, many-to-one, many-to-many, etc) Examples of networks can be found here: https://deeplearning4j.org/usingrnns

This PR includes documentation to describe the Layer's usage (above function in recurrent.py), an example to illustrate its usage, and a test case file to make sure that the compatibility does not get broken in the future.

Hope this Layer helps the community, I needed this for a very particular network that I was working on based on one found in literature.

### CODE REVIEW

**Comment by fchollet** [comment]
@farizrahman4u this may be of interest to you.

In general we are considering adding new features to increase the flexibility of Keras RNNs. We will come up with a roadmap and API design shortly. We will check out your PR in detail, but we are not likely to merge it.

**Comment by slaterb1** [comment]
@fchollet Just let me know if you would like any help incorporating some of my stuff into your new API design! I appreciate you going through my code.

**Comment by fchollet** [comment]
@slaterb1 sure, it would be great if you could contribute to the upcoming design and implementation. We'll keep you posted. Thanks!

**Comment by Imorton-zd** [comment]
@slaterb1  Hi, I am very interested in this `TimeStepLSTM`. Where can I read the full type of code about these complicated LSTM networks? Thanks！

**Comment by slaterb1** [comment]
@Imorton-zd if you go to my forked branch of keras, in the examples folder I've included a "timesteplstm.py" to show how you can call and interact with this layer. The particular example does not do anything spectacular but if you look at the comments in the for loop that calls the TimeStepLayer, that's where you can use a Lambda function to update the input sequence going into the LSTM, and where you can put in say a Dense Layer to act on the current states. There is also a quickish example above the TimeStepLSTM Layer in recurrent.py in my branch. 

I can't go into the specific details (or the code) of what I used the network for (due to the fact that I built the network for work...) but I was "inspired" by this paper: [https://arxiv.org/pdf/1603.07252v3.pdf](https://arxiv.org/pdf/1603.07252v3.pdf). The TimeStepLSTM can allow you to build something along these lines.

In terms of the other "types" of RNNs that can be built, that just requires you to attend to some states and ignore others. I don't have code for that worked out but it should follow closely to what should be done to replicate a model like the paper I just posted.

**Comment by Imorton-zd** [comment]
@slaterb1 Thanks for your replay. In fact, recently I encounter some problems about the modified LSTM. #6390
I don't know if you can spend your valuable time to help me solve this problem. Thanks!

**Comment by fchollet** [comment]
Please sync with @farizrahman4u on a plan for RNNs, if you are interested (see this issue https://github.com/fchollet/keras/issues/6328)

**Pull request closed without merging**
