### PR TITLE
add `eye` to backened

### PR DESCRIPTION
**Pull request by EderSantana**
that is pretty handy, let me know if useful for everybody

### CODE REVIEW

**Comment by EderSantana** [comment]
I hope you can auto squash that T_T

**Comment by TommeyChang** [comment]
In my code, some unit vectors are needed, I have tried two methods as follows:                  
1.mask = K.eye(self.input_length, pre_steps, dtype='floatX')
2.mask = K.eye((self.input_length, pre_steps), dtype='floatX')
Then I got two errors:
1.TypeError: eye() got multiple values for keyword argument 'dtype'
2.TypeError: an integer is required
 
I looked up the implements of eye function both in theano and tensorflow, they are as follows:
def eye(size, dtype=_FLOATX, name=None):
     '''Instantiates an identity matrix.
     '''
    return variable(np.eye(size), dtype, name)
 
At last, I turn to the numpy. In eye function of numpy, there are four parameters, which are N,  M, k, dtype. And a tuple of parameters is rejected. 

I think we can modify this method as follows:
def eye(N, M=None, k=0, dtype=_FLOATX, name=None):
    '''Instantiates an identity matrix.
    '''
    return variable(np.eye(N, M, k), dtype, name)

**Comment by EderSantana** [comment]
tkx for the review!

I wrote eye assuming a square matrix. I think you could try mask = K.eye(self.input_length, dtype='floatX')[:, : pre_steps] or mask = K.variable(np.eye(N, M, k), dtype, name).

Still, if you want to make a PR I can review it :)

**Comment by TommeyChang** [comment]
Thanks for your review. @EderSantana 
I think the two methods your proposed are proper for me. But, I used T.eye(pre_steps, self.input_length) instead.
However, I think if your can change the implement to variable(np.eye(N, M, k), dtype, name), it will be consistent with the numpy and the theano.

**Pull request merged**
