### PR TITLE
Remove unneeded steps_per_epoch

### PR DESCRIPTION
**Pull request by ozabluda**
`ImageDataGenerator.flow()` returns an instance of `Sequence` for which `steps_per_epoch` is determined automatically.

### CODE REVIEW

**Comment by ozabluda** [comment]
Made possible after PR https://github.com/fchollet/keras/pull/8509

**Comment by tundo91** [comment]
Seems Keras 2.1.1 complains about the required `steps_per_epoch` argument in the [cifar10_cnn](https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py) example:

```
model.fit_generator(datagen.flow(x_train, y_train,
                                 batch_size=32),
                    epochs=100,
                    validation_data=(x_test, y_test))
```

Fails:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-81e373fed2f8> in <module>()
     16                                  batch_size=32),
     17                     epochs=100,
---> 18                     validation_data=(x_test, y_test))

~/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

TypeError: fit_generator() missing 1 required positional argument: 'steps_per_epoch'
```

**Comment by ozabluda** [comment]
PR in the second comment is not in 2.1.1

**Comment by DNXie** [comment]
I've had the problem exactly like @tundo91

**Comment by wihl** [comment]
@tundo91 @DNXie  Keras 2.1.2 no longer requires `steps_per_epoch`

**Pull request merged**
