### PR TITLE
fix non-trainable embedding bug

### PR DESCRIPTION
**Pull request by xingdi-eric-yuan**
fix bug, when embedding layer is untrainable, the weights should be added into self.non_trainable_weights

### CODE REVIEW

**Comment by fchollet** [comment]
Actually no, that's not how it works. Were you having an issue related to this?

**Comment by xingdi-eric-yuan** [comment]
@fchollet Yes, when calling topology.Layer.count_params() with embedding layer, regardless what's the input 'trainable' parameter, the amount of params are the same.

**Comment by xingdi-eric-yuan** [comment]
@fchollet then how could I use a pre-trained embedding, and keep it fixed?

**Comment by fchollet** [comment]
That's not a bug, that's a feature. There's a reason it's called "params"
(count) and not "trainable params".

To get the count of trainable params only, iterate over layers, only select
those that are trainable, and call count_params on those.

**Comment by xingdi-eric-yuan** [comment]
yeah I get it, but still, how to keep the embedding layer weights fixed?

**Comment by fchollet** [comment]
That's what the trainable=False argument is for. You can use it to keep the
weights of a layer fixed (including Embedding, of course).

**Comment by xingdi-eric-yuan** [comment]
https://github.com/fchollet/keras/blob/keras-1/keras/layers/embeddings.py#L95
here you add self.W into self.trainable_weights regardless if it is trainable, then 
https://github.com/fchollet/keras/blob/keras-1/keras/engine/training.py#L628
here you do updates. 
I can't find anywhere you prevent untrainable weights from training in your code, could you point it out?

**Comment by fchollet** [comment]
Thanks for pointing this out, this is something that was overlooked. It is
now fixed. You can pull master and reinstall.

**Pull request closed without merging**
