### PR TITLE
ImageDataGenerator thread safe

### PR DESCRIPTION
**Pull request by udibr**

### CODE REVIEW

**Comment by fchollet** [comment]
Tests are failing.

**Comment by fchollet** [comment]
This appears to introduce a bug in which the generator just loops over a small fraction of the data, not the full array. I haven't looked into the details yet. Have you tried to use this code to train something?

**Comment by udibr** [comment]
Ouch! I've started experimenting with it but if this is the case it can explain few things...
I'll write a test unit for it and see whats happening.
Anyway the old version was completely broken with more than one worker was in use

**Comment by udibr** [comment]
mnist_cnn.py works OK with 8 workers got exactly the same test accuracy.
Do you have other examples?

**Comment by fchollet** [comment]
I just tried it on cifar10_cnn. The training accuracy jumps quickly to 0.9+ (one epoch), whereas the test accuracy is around 0.16. What you would expect after one epoch is to see both accuracies around 0.7 or so. Basically the model just sees the same samples over and over.

**Comment by udibr** [comment]
OK. I managed to reach a bug when the number of workers reduced to one. Strange, but that the way with all bugs...

**Comment by udibr** [comment]
P.S. great podcast talk

**Comment by udibr** [comment]
I'm having hard time figuring how to use rebase and I dont know why my commit is not at the bottom...

**Comment by udibr** [comment]
using it without any problems on both graph and sequence models

**Comment by fchollet** [comment]
There seems to be various git issues with this PR. Please sync with master. Maybe create a new PR.

**Pull request closed without merging**
