### PR TITLE
Python3 compatibility changes

### PR DESCRIPTION
**Pull request by untom**
This PR makes Keras work under Python3. Essentially I just ran the whole codebase through [python-modernize](https://github.com/mitsuhiko/python-modernize), and tuned a few things by hand. All examples run through under both Python2 and Python3, so I assume everything is in working order.

### CODE REVIEW

**Comment by untom** [comment]
I fixed the merge conflicts. Let me know if you're interested in these patches at all, BTW :)

**Comment by fchollet** [comment]
I am thinking about it. It's useful to have dual-compatibility, and would definitely be something to have in the longer term. However, for now:

- everybody in the scientific community uses 2.7, so I don't think that's an issue with adoption
- since we are still in a phase of rapid changes and fast iterations, it could be harmful to have to maintain dual-compatibility at every update. People working with Python 2.7 will forget about Python3-specific syntax, and reciprocally. For instance, people developing in Python 3 might use integer divisions that would result in a hard-to-spot issue in 2.7, like you just did : )

So I think the best move right now would be to keep being 2.7-only, until the first "release" (1.0 version), when the library will be more stable and should aim at wider distribution.

**Comment by untom** [comment]
Thanks for your considerations. I understand your reluctance in adding this. I find keras very useful for my own research, and I'm considering switching to it for some of my own research. So thanks for this project, I love how simple you've kept everything!

Since my lab switched to Py3, I will maintain these set of patches on my own (at least for as long as I'll keep using keras). Thus if you want to add Py3 compatibility later on, send me a message and I can send an up-to-date PR.

Also, just as 'food for thought':

* if every file starts with the 'usual' ``from __future__ import absolute_import, division, print_function``, most Py2/Py3 incompatibilities never arise in the first place (admittedly I overlooked this myself in the initialization-PR).... maybe ithink about adding that line to all new files in keras to ease the transition later on.

* I wouldn't be so sure about everybody in the ML community still being stuck on 2.7. Apart from my own lab, I know of several other labs in the process of switching to Py3.


In any case, thanks again for open-sourcing this :)

**Comment by fchollet** [comment]
We have made progress faster than expected, and are we fast approaching a maturity level sufficient for a first release (possibly within the end of April). Having Py3 + 2.7 compatibility would be one of the milestones on our way. Are you still interested in taking care of it?

**Comment by fchollet** [comment]
I went ahead and set it up. There were two possibilities: either use python-modernize, or the more canonical method of specifying use_2to3  in setup.py. I went with python-modernize, mostly to keep full control over the codebase and avoid any surprises at build time.

**Comment by untom** [comment]
Awesome, just seen it!  BTW, `datasets/cifar10.py` might need a bit more work, since the original cf10-pickle files aren't straightforward to load in Py3.

**Pull request closed without merging**
