### PR TITLE
one line fix for TensorBoard callback issue

### PR DESCRIPTION
**Pull request by jingzhehu**
Ref: https://github.com/fchollet/keras/issues/2570

### CODE REVIEW

**Comment by jingzhehu** [comment]
One data point: it seems to work on my local machine with TensorFlow 0.8.

**Comment by fchollet** [comment]
Tests are failing hard. Seems to be more to it.

**Comment by jingzhehu** [comment]
What's the version of tensorflow on the test env ?

**Comment by joelthchao** [comment]
@jingzhehu 0.7.1

**Comment by jingzhehu** [comment]
@joelthchao Thank for the info ! 

@fchollet, Would it be possible to bump up the tensorflow version in the test env and see if the tests fail ?

I will try to run the tests locally after I get back.

**Comment by joelthchao** [comment]
@jingzhehu probably you can use condition on tensorflow version to fix the problem.
I guess tensorflow does the same thing to maintain compatibility.

**Comment by fchollet** [comment]
Are the tests all passing locally for you?

**Comment by jingzhehu** [comment]
One data point: the tests all passed (150 passed, 5 skipped) on a local mac (python 2.7.11 + tensorflow 0.8).

**Comment by jingzhehu** [comment]
```
======================================== test session starts ========================================
platform darwin -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /usr/local/opt/python/bin/python2.7
cachedir: .cache
rootdir: /Users/hujingzhe/Desktop/keras, inifile: pytest.ini
plugins: cov-2.2.1, pep8-1.0.6, xdist-1.14
[gw0] darwin Python 2.7.11 cwd: /Users/hujingzhe/Desktop/keras
[gw1] darwin Python 2.7.11 cwd: /Users/hujingzhe/Desktop/keras
[gw0] Python 2.7.11 (default, Jan 22 2016, 08:29:18)  -- [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
[gw1] Python 2.7.11 (default, Jan 22 2016, 08:29:18)  -- [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
gw0 [155] / gw1 [155]
scheduling tests via LoadScheduling

tests/test_loss_masking.py::test_masking 
tests/test_loss_masking.py::test_loss_masking 
[gw1] PASSED tests/test_loss_masking.py::test_loss_masking 
tests/test_loss_weighting.py::test_sequential_sample_weights 
[gw0] PASSED tests/test_loss_masking.py::test_masking 
tests/test_loss_weighting.py::test_sequential_class_weights 
[gw0] PASSED tests/test_loss_weighting.py::test_sequential_class_weights 
tests/test_loss_weighting.py::test_sequential_temporal_sample_weights 
[gw1] PASSED tests/test_loss_weighting.py::test_sequential_sample_weights 
tests/test_loss_weighting.py::test_graph_class_weights 
[gw1] PASSED tests/test_loss_weighting.py::test_graph_class_weights 
tests/test_loss_weighting.py::test_graph_temporal_sample_weight 
[gw1] PASSED tests/test_loss_weighting.py::test_graph_temporal_sample_weight 
tests/integration_tests/test_temporal_data_tasks.py::test_temporal_classification 
[gw1] PASSED tests/integration_tests/test_temporal_data_tasks.py::test_temporal_classification 
tests/integration_tests/test_temporal_data_tasks.py::test_sequence_to_sequence 
[gw1] PASSED tests/integration_tests/test_temporal_data_tasks.py::test_sequence_to_sequence 
tests/integration_tests/test_temporal_data_tasks.py::test_masked_temporal 
[gw0] PASSED tests/test_loss_weighting.py::test_sequential_temporal_sample_weights 
tests/test_loss_weighting.py::test_graph_sample_weights 
[gw0] PASSED tests/test_loss_weighting.py::test_graph_sample_weights 
tests/integration_tests/test_image_data_tasks.py::test_image_classification 
[gw0] PASSED tests/integration_tests/test_image_data_tasks.py::test_image_classification 
tests/integration_tests/test_temporal_data_tasks.py::test_temporal_regression 
[gw0] PASSED tests/integration_tests/test_temporal_data_tasks.py::test_temporal_regression 
tests/integration_tests/test_temporal_data_tasks.py::test_stacked_lstm_char_prediction 
[gw1] PASSED tests/integration_tests/test_temporal_data_tasks.py::test_masked_temporal 
tests/integration_tests/test_vector_data_tasks.py::test_vector_regression 
[gw1] PASSED tests/integration_tests/test_vector_data_tasks.py::test_vector_regression 
tests/keras/test_activations.py::test_time_distributed_softmax 
[gw1] PASSED tests/keras/test_activations.py::test_time_distributed_softmax 
tests/keras/test_activations.py::test_softsign 
[gw1] PASSED tests/keras/test_activations.py::test_softsign 
tests/keras/test_activations.py::test_hard_sigmoid 
[gw1] PASSED tests/keras/test_activations.py::test_hard_sigmoid 
tests/keras/test_activations.py::test_tanh 
[gw1] PASSED tests/keras/test_activations.py::test_tanh 
tests/keras/test_callbacks.py::test_ModelCheckpoint 
[gw1] PASSED tests/keras/test_callbacks.py::test_ModelCheckpoint 
tests/keras/test_callbacks.py::test_LearningRateScheduler 
[gw1] PASSED tests/keras/test_callbacks.py::test_LearningRateScheduler 
tests/keras/test_constraints.py::test_maxnorm 
[gw1] PASSED tests/keras/test_constraints.py::test_maxnorm 
tests/keras/test_constraints.py::test_unitnorm 
[gw1] PASSED tests/keras/test_constraints.py::test_unitnorm 
tests/keras/test_graph_model.py::test_1o_1i 
[gw1] PASSED tests/keras/test_graph_model.py::test_1o_1i 
tests/keras/test_graph_model.py::test_1o_2i 
[gw1] PASSED tests/keras/test_graph_model.py::test_1o_2i 
tests/keras/test_graph_model.py::test_2o_1i_save_weights 
[gw1] PASSED tests/keras/test_graph_model.py::test_2o_1i_save_weights 
tests/keras/test_graph_model.py::test_2o_1i_sample_weights 
[gw1] PASSED tests/keras/test_graph_model.py::test_2o_1i_sample_weights 
tests/keras/test_graph_model.py::test_recursive 
[gw1] PASSED tests/keras/test_graph_model.py::test_recursive 
tests/keras/test_graph_model.py::test_create_output 
[gw1] PASSED tests/keras/test_graph_model.py::test_create_output 
tests/keras/test_graph_model.py::test_count_params 
[gw1] PASSED tests/keras/test_graph_model.py::test_count_params 
tests/keras/test_initializations.py::test_uniform 
[gw1] PASSED tests/keras/test_initializations.py::test_uniform 
tests/keras/test_initializations.py::test_normal 
[gw1] PASSED tests/keras/test_initializations.py::test_normal 
tests/keras/test_initializations.py::test_lecun_uniform 
[gw1] PASSED tests/keras/test_initializations.py::test_lecun_uniform 
tests/keras/test_initializations.py::test_glorot_uniform 
[gw1] PASSED tests/keras/test_initializations.py::test_glorot_uniform 
tests/keras/test_initializations.py::test_glorot_normal 
[gw1] PASSED tests/keras/test_initializations.py::test_glorot_normal 
tests/keras/test_initializations.py::test_he_uniform 
[gw1] PASSED tests/keras/test_initializations.py::test_he_uniform 
tests/keras/test_initializations.py::test_he_normal 
[gw1] PASSED tests/keras/test_initializations.py::test_he_normal 
tests/keras/test_initializations.py::test_orthogonal 
[gw1] PASSED tests/keras/test_initializations.py::test_orthogonal 
tests/keras/test_initializations.py::test_identity 
[gw1] PASSED tests/keras/test_initializations.py::test_identity 
tests/keras/test_initializations.py::test_zero 
[gw1] PASSED tests/keras/test_initializations.py::test_zero 
tests/keras/test_initializations.py::test_one 
[gw1] PASSED tests/keras/test_initializations.py::test_one 
tests/keras/test_metrics.py::test_metrics 
[gw1] PASSED tests/keras/test_metrics.py::test_metrics 
tests/keras/test_metrics.py::test_sparse_metrics 
[gw1] PASSED tests/keras/test_metrics.py::test_sparse_metrics 
tests/keras/test_objectives.py::test_objective_shapes_3d 
[gw1] PASSED tests/keras/test_objectives.py::test_objective_shapes_3d 
tests/keras/test_objectives.py::test_objective_shapes_2d 
[gw1] PASSED tests/keras/test_objectives.py::test_objective_shapes_2d 
tests/keras/test_objectives.py::test_cce_one_hot 
[gw1] PASSED tests/keras/test_objectives.py::test_cce_one_hot 
tests/keras/test_optimizers.py::test_sgd 
[gw1] PASSED tests/keras/test_optimizers.py::test_sgd 
tests/keras/test_optimizers.py::test_rmsprop 
[gw1] PASSED tests/keras/test_optimizers.py::test_rmsprop 
tests/keras/test_optimizers.py::test_adagrad 
[gw1] PASSED tests/keras/test_optimizers.py::test_adagrad 
tests/keras/test_optimizers.py::test_adadelta 
[gw0] PASSED tests/integration_tests/test_temporal_data_tasks.py::test_stacked_lstm_char_prediction 
tests/integration_tests/test_vector_data_tasks.py::test_vector_classification 
[gw1] PASSED tests/keras/test_optimizers.py::test_adadelta 
tests/keras/test_optimizers.py::test_adam 
[gw0] PASSED tests/integration_tests/test_vector_data_tasks.py::test_vector_classification 
tests/keras/test_activations.py::test_softmax 
[gw0] PASSED tests/keras/test_activations.py::test_softmax 
tests/keras/test_activations.py::test_softplus 
[gw0] PASSED tests/keras/test_activations.py::test_softplus 
tests/keras/test_activations.py::test_sigmoid 
[gw0] PASSED tests/keras/test_activations.py::test_sigmoid 
tests/keras/test_activations.py::test_relu 
[gw0] PASSED tests/keras/test_activations.py::test_relu 
tests/keras/test_activations.py::test_linear 
[gw0] PASSED tests/keras/test_activations.py::test_linear 
tests/keras/test_callbacks.py::test_EarlyStopping 
[gw0] PASSED tests/keras/test_callbacks.py::test_EarlyStopping 
tests/keras/test_callbacks.py::test_TensorBoard 
[gw0] PASSED tests/keras/test_callbacks.py::test_TensorBoard 
tests/keras/test_constraints.py::test_nonneg 
[gw0] PASSED tests/keras/test_constraints.py::test_nonneg 
tests/keras/test_graph_model.py::test_graph_fit_generator 
[gw1] PASSED tests/keras/test_optimizers.py::test_adam 
tests/keras/test_optimizers.py::test_adamax 
[gw0] PASSED tests/keras/test_graph_model.py::test_graph_fit_generator 
tests/keras/test_graph_model.py::test_1o_1i_2 
[gw0] PASSED tests/keras/test_graph_model.py::test_1o_1i_2 
tests/keras/test_graph_model.py::test_siamese_1 
[gw1] PASSED tests/keras/test_optimizers.py::test_adamax 
tests/keras/test_regularizers.py::test_W_reg 
[gw0] PASSED tests/keras/test_graph_model.py::test_siamese_1 
tests/keras/backend/test_backends.py::TestBackend::test_gradient 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_gradient 
tests/keras/backend/test_backends.py::TestBackend::test_function 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_function 
tests/keras/backend/test_backends.py::TestBackend::test_rnn 
[gw1] PASSED tests/keras/test_regularizers.py::test_W_reg 
tests/keras/test_regularizers.py::test_A_reg 
[gw1] PASSED tests/keras/test_regularizers.py::test_A_reg 
tests/keras/test_sequential_model.py::test_sequential_fit_generator 
[gw1] PASSED tests/keras/test_sequential_model.py::test_sequential_fit_generator 
tests/keras/test_sequential_model.py::test_sequential 
[gw1] PASSED tests/keras/test_sequential_model.py::test_sequential 
tests/keras/test_sequential_model.py::test_nested_sequential 
[gw1] PASSED tests/keras/test_sequential_model.py::test_nested_sequential 
tests/keras/test_sequential_model.py::test_merge_sum 
[gw1] PASSED tests/keras/test_sequential_model.py::test_merge_sum 
tests/keras/test_sequential_model.py::test_merge_dot 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_rnn 
tests/keras/backend/test_backends.py::TestBackend::test_switch 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_switch 
tests/keras/backend/test_backends.py::TestBackend::test_nn_operations 
[gw1] PASSED tests/keras/test_sequential_model.py::test_merge_dot 
tests/keras/test_sequential_model.py::test_merge_concat 
[gw1] PASSED tests/keras/test_sequential_model.py::test_merge_concat 
tests/keras/test_sequential_model.py::test_merge_recursivity 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_nn_operations 
tests/keras/backend/test_backends.py::TestBackend::test_conv2d 
[gw1] PASSED tests/keras/test_sequential_model.py::test_merge_recursivity 
tests/keras/test_sequential_model.py::test_merge_overlap 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_conv2d 
tests/keras/backend/test_backends.py::TestBackend::test_pool2d 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_pool2d 
tests/keras/backend/test_backends.py::TestBackend::test_random_normal 
[gw1] PASSED tests/keras/test_sequential_model.py::test_merge_overlap 
tests/keras/test_sequential_model.py::test_sequential_count_params 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_random_normal 
tests/keras/backend/test_backends.py::TestBackend::test_random_uniform 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_random_uniform 
tests/keras/backend/test_backends.py::TestBackend::test_random_binomial 
[gw1] PASSED tests/keras/test_sequential_model.py::test_sequential_count_params 
tests/keras/backend/test_backends.py::TestBackend::test_linear_operations 
[gw0] PASSED tests/keras/backend/test_backends.py::TestBackend::test_random_binomial 
tests/keras/datasets/test_datasets.py::test_cifar 
[gw1] PASSED tests/keras/backend/test_backends.py::TestBackend::test_linear_operations 
tests/keras/backend/test_backends.py::TestBackend::test_shape_operations 
[gw1] PASSED tests/keras/backend/test_backends.py::TestBackend::test_shape_operations 
tests/keras/backend/test_backends.py::TestBackend::test_repeat_elements 
[gw1] PASSED tests/keras/backend/test_backends.py::TestBackend::test_repeat_elements 
tests/keras/backend/test_backends.py::TestBackend::test_value_manipulation 
[gw1] PASSED tests/keras/backend/test_backends.py::TestBackend::test_value_manipulation 
tests/keras/backend/test_backends.py::TestBackend::test_elementwise_operations 
[gw1] PASSED tests/keras/backend/test_backends.py::TestBackend::test_elementwise_operations 
tests/keras/datasets/test_datasets.py::test_mnist 
[gw1] PASSED tests/keras/datasets/test_datasets.py::test_mnist 
tests/keras/datasets/test_datasets.py::test_imdb 
[gw1] PASSED tests/keras/datasets/test_datasets.py::test_imdb 
tests/keras/engine/test_topology.py::test_learning_phase 
[gw1] PASSED tests/keras/engine/test_topology.py::test_learning_phase 
tests/keras/engine/test_topology.py::test_node_construction 
[gw1] PASSED tests/keras/engine/test_topology.py::test_node_construction 
tests/keras/engine/test_topology.py::test_multi_input_layer 
[gw1] PASSED tests/keras/engine/test_topology.py::test_multi_input_layer 
tests/keras/engine/test_topology.py::test_recursion 
[gw1] PASSED tests/keras/engine/test_topology.py::test_recursion 
tests/keras/engine/test_topology.py::test_functional_guide 
[gw1] PASSED tests/keras/engine/test_topology.py::test_functional_guide 
tests/keras/engine/test_topology.py::test_sequential_regression 
[gw1] PASSED tests/keras/engine/test_topology.py::test_sequential_regression 
tests/keras/engine/test_training.py::test_model_methods 
[gw0] PASSED tests/keras/datasets/test_datasets.py::test_cifar 
tests/keras/datasets/test_datasets.py::test_reuters 
[gw0] PASSED tests/keras/datasets/test_datasets.py::test_reuters 
tests/keras/layers/test_advanced_activations.py::test_thresholded_relu 
[gw1] PASSED tests/keras/engine/test_training.py::test_model_methods 
tests/keras/engine/test_training.py::test_trainable_argument 
[gw0] PASSED tests/keras/layers/test_advanced_activations.py::test_thresholded_relu 
tests/keras/layers/test_advanced_activations.py::test_srelu 
[gw1] PASSED tests/keras/engine/test_training.py::test_trainable_argument 
tests/keras/layers/test_advanced_activations.py::test_leaky_relu 
[gw0] PASSED tests/keras/layers/test_advanced_activations.py::test_srelu 
tests/keras/layers/test_convolutional.py::test_convolution_1d 
[gw1] PASSED tests/keras/layers/test_advanced_activations.py::test_leaky_relu 
tests/keras/layers/test_advanced_activations.py::test_prelu 
[gw0] PASSED tests/keras/layers/test_convolutional.py::test_convolution_1d 
tests/keras/layers/test_convolutional.py::test_maxpooling_1d 
[gw1] PASSED tests/keras/layers/test_advanced_activations.py::test_prelu 
tests/keras/layers/test_advanced_activations.py::test_elu 
[gw0] PASSED tests/keras/layers/test_convolutional.py::test_maxpooling_1d 
tests/keras/layers/test_convolutional.py::test_averagepooling_1d 
[gw0] PASSED tests/keras/layers/test_convolutional.py::test_averagepooling_1d 
tests/keras/layers/test_convolutional.py::test_convolution_2d 
[gw1] PASSED tests/keras/layers/test_advanced_activations.py::test_elu 
tests/keras/layers/test_advanced_activations.py::test_parametric_softplus 
[gw0] PASSED tests/keras/layers/test_convolutional.py::test_convolution_2d 
tests/keras/layers/test_convolutional.py::test_maxpooling_2d 
[gw1] PASSED tests/keras/layers/test_advanced_activations.py::test_parametric_softplus 
tests/keras/layers/test_convolutional.py::test_zero_padding_2d 
[gw0] PASSED tests/keras/layers/test_convolutional.py::test_maxpooling_2d 
tests/keras/layers/test_convolutional.py::test_averagepooling_2d 
[gw1] PASSED tests/keras/layers/test_convolutional.py::test_zero_padding_2d 
tests/keras/layers/test_convolutional.py::test_zero_padding_3d 
[gw1] SKIPPED tests/keras/layers/test_convolutional.py::test_zero_padding_3d 
tests/keras/layers/test_convolutional.py::test_upsampling_1d 
[gw1] PASSED tests/keras/layers/test_convolutional.py::test_upsampling_1d 
tests/keras/layers/test_convolutional.py::test_upsampling_2d 
[gw1] PASSED tests/keras/layers/test_convolutional.py::test_upsampling_2d 
tests/keras/layers/test_convolutional.py::test_upsampling_3d 
[gw1] SKIPPED tests/keras/layers/test_convolutional.py::test_upsampling_3d 
tests/keras/layers/test_core.py::test_masking 
[gw1] PASSED tests/keras/layers/test_core.py::test_masking 
tests/keras/layers/test_core.py::test_merge 
[gw1] PASSED tests/keras/layers/test_core.py::test_merge 
tests/keras/layers/test_core.py::test_dropout 
[gw0] PASSED tests/keras/layers/test_convolutional.py::test_averagepooling_2d 
tests/keras/layers/test_convolutional.py::test_convolution_3d 
[gw0] SKIPPED tests/keras/layers/test_convolutional.py::test_convolution_3d 
tests/keras/layers/test_convolutional.py::test_maxpooling_3d 
[gw0] SKIPPED tests/keras/layers/test_convolutional.py::test_maxpooling_3d 
tests/keras/layers/test_convolutional.py::test_averagepooling_3d 
[gw0] SKIPPED tests/keras/layers/test_convolutional.py::test_averagepooling_3d 
tests/keras/layers/test_core.py::test_dense 
[gw1] PASSED tests/keras/layers/test_core.py::test_dropout 
tests/keras/layers/test_core.py::test_activation 
[gw0] PASSED tests/keras/layers/test_core.py::test_dense 
tests/keras/layers/test_core.py::test_activity_regularization 
[gw0] PASSED tests/keras/layers/test_core.py::test_activity_regularization 
tests/keras/layers/test_core.py::test_maxout_dense 
[gw1] PASSED tests/keras/layers/test_core.py::test_activation 
tests/keras/layers/test_core.py::test_reshape 
[gw1] PASSED tests/keras/layers/test_core.py::test_reshape 
tests/keras/layers/test_core.py::test_permute 
[gw1] PASSED tests/keras/layers/test_core.py::test_permute 
tests/keras/layers/test_core.py::test_flatten 
[gw0] PASSED tests/keras/layers/test_core.py::test_maxout_dense 
tests/keras/layers/test_core.py::test_highway 
[gw1] PASSED tests/keras/layers/test_core.py::test_flatten 
tests/keras/layers/test_core.py::test_repeat_vector 
[gw1] PASSED tests/keras/layers/test_core.py::test_repeat_vector 
tests/keras/layers/test_core.py::test_lambda 
[gw0] PASSED tests/keras/layers/test_core.py::test_highway 
tests/keras/layers/test_core.py::test_timedistributeddense 
[gw1] PASSED tests/keras/layers/test_core.py::test_lambda 
tests/keras/layers/test_normalization.py::test_batchnorm_mode_0 
[gw1] PASSED tests/keras/layers/test_normalization.py::test_batchnorm_mode_0 
tests/keras/layers/test_normalization.py::test_batchnorm_mode_0_convnet 
[gw0] PASSED tests/keras/layers/test_core.py::test_timedistributeddense 
tests/keras/layers/test_embeddings.py::test_embedding 
[gw0] PASSED tests/keras/layers/test_embeddings.py::test_embedding 
tests/keras/layers/test_noise.py::test_GaussianNoise 
[gw1] PASSED tests/keras/layers/test_normalization.py::test_batchnorm_mode_0_convnet 
tests/keras/layers/test_normalization.py::test_batchnorm_mode_1 
[gw0] PASSED tests/keras/layers/test_noise.py::test_GaussianNoise 
tests/keras/layers/test_noise.py::test_GaussianDropout 
[gw1] PASSED tests/keras/layers/test_normalization.py::test_batchnorm_mode_1 
tests/keras/layers/test_recurrent.py::test_SimpleRNN 
[gw0] PASSED tests/keras/layers/test_noise.py::test_GaussianDropout 
tests/keras/layers/test_recurrent.py::test_LSTM 
[gw1] PASSED tests/keras/layers/test_recurrent.py::test_SimpleRNN 
tests/keras/layers/test_recurrent.py::test_GRU 
[gw0] PASSED tests/keras/layers/test_recurrent.py::test_LSTM 
tests/keras/layers/test_recurrent.py::test_masking_layer 
[gw0] PASSED tests/keras/layers/test_recurrent.py::test_masking_layer 
tests/keras/preprocessing/test_image.py::TestImage::test_image_data_generator 
[gw0] PASSED tests/keras/preprocessing/test_image.py::TestImage::test_image_data_generator 
tests/keras/preprocessing/test_image.py::TestImage::test_img_flip 
[gw0] PASSED tests/keras/preprocessing/test_image.py::TestImage::test_img_flip 
tests/keras/preprocessing/test_sequence.py::test_pad_sequences 
[gw0] PASSED tests/keras/preprocessing/test_sequence.py::test_pad_sequences 
tests/keras/preprocessing/test_sequence.py::test_pad_sequences_vector 
[gw0] PASSED tests/keras/preprocessing/test_sequence.py::test_pad_sequences_vector 
tests/keras/preprocessing/test_sequence.py::test_make_sampling_table 
[gw0] PASSED tests/keras/preprocessing/test_sequence.py::test_make_sampling_table 
tests/keras/preprocessing/test_sequence.py::test_skipgrams 
[gw0] PASSED tests/keras/preprocessing/test_sequence.py::test_skipgrams 
tests/keras/preprocessing/test_text.py::test_one_hot 
[gw0] PASSED tests/keras/preprocessing/test_text.py::test_one_hot 
[gw1] PASSED tests/keras/layers/test_recurrent.py::test_GRU 
tests/keras/preprocessing/test_text.py::test_tokenizer 
tests/keras/layers/test_wrappers.py::test_TimeDistributed 
[gw0] PASSED tests/keras/preprocessing/test_text.py::test_tokenizer 
[gw1] PASSED tests/keras/layers/test_wrappers.py::test_TimeDistributed Exception AttributeError: AttributeError("'NoneType' object has no attribute 'TF_DeleteStatus'",) in <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x111dcdb10>> ignored
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'TF_DeleteStatus'",) in <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x10c57fbd0>> ignored
Coverage.py warning: No data was collected.

------------------------- coverage: platform darwin, python 2.7.11-final-0 --------------------------
Name                                   Stmts   Miss  Cover   Missing
--------------------------------------------------------------------
keras/__init__.py                         17      0   100%   
keras/activations.py                      28      1    96%   14
keras/backend/__init__.py                 44     11    75%   15, 19, 37-42, 45-47, 50-51, 56
keras/backend/common.py                   23      1    96%   28
keras/backend/tensorflow_backend.py      431     41    90%   26, 44, 49-50, 79-84, 168, 241, 246-247, 250, 278, 322, 422, 456, 462, 474, 512, 542, 573-574, 585, 592, 724, 735, 814-820, 982, 988-989, 1005, 1008, 1028, 1035, 1051, 1055, 1058
keras/backend/theano_backend.py          491    175    64%   19, 35, 37, 54, 62, 74, 80, 86, 90, 106, 143, 146, 149, 163, 192, 203, 249, 258, 270, 274, 313-322, 332-343, 358, 369-370, 379, 400-405, 412-436, 443-471, 475, 482, 492-493, 513-517, 570, 588, 641-642, 678-679, 697-699, 703-705, 730, 745-748, 773, 796, 808, 811, 815-816, 820, 824-827, 830, 833, 842-845, 859-911, 917-919, 923, 926, 929, 936-942, 945-948, 953, 959-1012
keras/callbacks.py                       265     36    86%   20, 49, 56, 64, 256-259, 269-270, 280, 285, 292-293, 297, 324-326, 329-330, 339-340, 345, 354, 372, 375-385, 437, 471-473, 484
keras/constraints.py                      35      3    91%   7, 10, 82
keras/datasets/__init__.py                 0      0   100%   
keras/datasets/cifar.py                   17      4    76%   13-17
keras/datasets/cifar10.py                 22      0   100%   
keras/datasets/cifar100.py                20      1    95%   10
keras/datasets/data_utils.py               3      3     0%   1-4
keras/datasets/imdb.py                    49     12    76%   16, 30-31, 43, 54-61
keras/datasets/mnist.py                   14      2    86%   14, 19
keras/datasets/reuters.py                 48     13    73%   25-26, 46-53, 65-67
keras/engine/__init__.py                   8      0   100%   
keras/engine/topology.py                1168    144    88%   129, 133, 158, 163, 169, 187-193, 322, 330, 356, 371, 378, 385, 393-397, 401, 448-451, 539, 572-577, 606, 609, 674, 681, 685-686, 691, 698-701, 790, 800, 814, 822-824, 843, 852, 908, 945, 1033, 1129, 1131, 1149, 1154, 1162, 1166, 1168, 1170, 1172, 1182, 1188, 1220-1229, 1238, 1241, 1280-1284, 1299-1300, 1304, 1315, 1317-1318, 1324, 1332-1336, 1338-1339, 1345-1349, 1351-1352, 1369, 1371-1372, 1378, 1380-1381, 1546-1547, 1731, 1778-1790, 1828-1831, 1862-1868, 1924, 2015, 2254-2264, 2284, 2308-2318, 2323, 2339, 2367-2370, 2423, 2428
keras/engine/training.py                 773    123    84%   34, 40-54, 65, 72, 92, 100, 120, 133, 159, 163, 167, 170, 175, 189, 205, 228, 254-262, 296-301, 341, 345, 353, 359, 374, 378-381, 405-406, 410-412, 462, 471, 478, 485, 492, 496-502, 520, 529, 536-537, 540-555, 618, 631, 651, 674, 689, 768, 781-782, 791, 846, 897-899, 913, 934-935, 1002, 1109, 1292, 1324-1327, 1353-1354, 1360-1364, 1372, 1383-1385, 1426, 1466, 1469-1470, 1476-1480, 1485-1487, 1492, 1545-1553, 1557-1559, 1562, 1564, 1584
keras/initializations.py                  60      5    92%   17-21, 90
keras/layers/__init__.py                  10      0   100%   
keras/layers/advanced_activations.py     108      4    96%   71-72, 157-158
keras/layers/convolutional.py            517    226    56%   11, 92, 116, 127, 144, 146, 149-150, 264, 292-296, 302, 319, 321, 324-325, 331-335, 344-347, 357-360, 446-473, 476-518, 521-544, 547-561, 564-580, 592, 608, 705-709, 718-721, 725, 809, 814-816, 825-834, 837-860, 864, 867-871, 874-879, 911-914, 919-921, 953-956, 961-963, 1039, 1046-1048, 1077-1084, 1087-1100, 1103, 1107-1109, 1128-1130, 1133-1134, 1139, 1142-1144, 1179-1187, 1219-1226, 1229-1248, 1251, 1255-1257
keras/layers/core.py                     462     55    88%   188-191, 197-199, 201, 217-223, 302, 408, 411, 421-422, 427, 431-439, 445, 453, 458-459, 463, 468-469, 486, 491, 495, 601, 623-624, 759, 774, 796-797, 891, 911, 933-934, 1036, 1083-1093
keras/layers/embeddings.py                59     12    80%   85, 98, 102-103, 106-107, 110, 120, 127-130
keras/layers/noise.py                     32      1    97%   76
keras/layers/normalization.py             57      2    96%   79-80
keras/layers/recurrent.py                378     28    93%   16, 19, 22, 179, 182, 194, 203, 245, 326-327, 333, 350, 360, 495-496, 502, 524, 536-538, 700-701, 707, 738, 752-755
keras/layers/wrappers.py                  62      8    87%   28, 91, 116-122, 129
keras/legacy/__init__.py                   0      0   100%   
keras/legacy/models.py                   319     77    76%   110, 115, 119, 131, 160, 167, 177-180, 232, 237-238, 241, 246-247, 252, 269-286, 323, 329-332, 342, 360, 370, 409-410, 416, 422, 451-452, 458, 490-491, 497, 515-516, 522, 530-531, 592-593, 599-600, 603-604, 607, 616, 628-631, 672-673, 679-680, 682, 694-697, 731-738, 770
keras/metrics.py                          43      0   100%   
keras/models.py                          285     62    78%   12-13, 102, 109, 113, 120, 144, 163, 205-211, 252, 281-284, 292, 328-330, 385, 387-388, 394, 426, 428-429, 435, 455, 461, 482-483, 489, 512-513, 519, 538, 541, 561, 566, 624, 626-627, 633-634, 637-638, 641, 667, 669-670, 676-677, 679, 700, 737-744
keras/objectives.py                       38      0   100%   
keras/optimizers.py                      207     36    83%   9-11, 15, 37, 40-42, 45, 50-51, 53, 69-80, 86-89, 92, 132-133, 180-181, 219-220, 268-269, 328-329, 389-390
keras/preprocessing/__init__.py            0      0   100%   
keras/preprocessing/image.py             252     58    77%   18-26, 31-40, 45-53, 58-73, 78, 82-88, 133, 139, 149-151, 156-162, 166, 222, 237-240, 256, 261-262, 314, 386, 442-443
keras/preprocessing/sequence.py           74      7    91%   36, 49, 55, 60, 68, 129-130
keras/preprocessing/text.py              115      8    93%   16, 177-180, 186, 192, 196, 213
keras/regularizers.py                     57      7    88%   7, 10, 13, 16, 30, 59, 94
keras/utils/__init__.py                    0      0   100%   
keras/utils/data_utils.py                 74     17    77%   36, 42, 45, 69-76, 85-91
keras/utils/generic_utils.py             106     17    84%   13, 18, 27, 33, 90, 106, 127, 131, 136-145
keras/utils/io_utils.py                   54     54     0%   1-71
keras/utils/layer_utils.py                67      3    96%   22, 59-60
keras/utils/np_utils.py                   51     18    65%   21-23, 27-32, 36-38, 42, 46-48, 52, 75
keras/utils/test_utils.py                 64      6    91%   47-48, 62-63, 78, 97
keras/utils/visualize_util.py             45     45     0%   1-64
keras/wrappers/__init__.py                 0      0   100%   
keras/wrappers/scikit_learn.py            83     12    86%   81, 95-97, 109-111, 141, 143, 229, 233, 278
--------------------------------------------------------------------
TOTAL                                   7135   1338    81%   

===================================== slowest 10 test durations =====================================
163.84s call     tests/keras/datasets/test_datasets.py::test_cifar
94.99s call     tests/integration_tests/test_temporal_data_tasks.py::test_stacked_lstm_char_prediction
72.58s call     tests/test_loss_weighting.py::test_sequential_temporal_sample_weights
69.20s call     tests/keras/layers/test_recurrent.py::test_GRU
59.92s call     tests/keras/layers/test_recurrent.py::test_LSTM
55.41s call     tests/keras/backend/test_backends.py::TestBackend::test_rnn
50.74s call     tests/integration_tests/test_temporal_data_tasks.py::test_masked_temporal
42.77s call     tests/keras/backend/test_backends.py::TestBackend::test_elementwise_operations
42.22s call     tests/keras/layers/test_convolutional.py::test_averagepooling_2d
33.75s call     tests/keras/layers/test_recurrent.py::test_SimpleRNN
============================== 150 passed, 5 skipped in 825.70 seconds ==============================
```

**Comment by bnaul** [comment]
@jingzhehu See https://github.com/bnaul/keras/commit/8cd1e18b7a4f2b6b171bf86877798a6eacfdb350.

I also added a `write_graph` flag because I noticed that the log files can get quite large if the graph is included (e.g. ~500MB for a medium-sized LSTM).

**Comment by fchollet** [comment]
We should add a conditional statement based on the TF version.

**Comment by jingzhehu** [comment]
Thanks, @bnaul ! I've merged your code into the PR.

**Comment by bnaul** [comment]
Looks good to me. You'll probably want to squash those commits into one but the code is 👍.

**Comment by fchollet** [comment]
LGTM, thanks!

**Pull request merged**
