### PR TITLE
Fix to_categorical for higher dimensional inputs

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by fchollet** [comment]
Please add a test for `to_categorical` with higher-dimensional inputs.

**Comment by farizrahman4u** [comment]
There seems to be no tests for `np_utils`. Do you want me to create `tests/keras/utils/np_utils.py`? 

P.S I personally dont think small stand alone numpy functions need tests - once proven working, they will work for ever without breaking.

**Comment by fchollet** [comment]
Yes, please do.

> P.S I personally dont think small stand alone numpy functions need tests - once proven working, they will work for ever without breaking.

Only if no one touches them. The purpose of tests is to be able to monitor the impact of all changes at all times, within having to run things manually.

**Comment by farizrahman4u** [comment]
@fchollet Test added.

**Pull request merged**
