### PR TITLE
ImageDataGenerator thread safe

### PR DESCRIPTION
**Pull request by udibr**
replace https://github.com/fchollet/keras/pull/1581

### CODE REVIEW

**Comment by fchollet** [comment]
Great, thanks! I merged it.

By the way, one thing that is problematic with `fit_generator` right now is the inability to interrupt training via `KeyboardInterrupt` due to the use of threading. Is it something you would like to take a look at?

**Comment by udibr** [comment]
I'm not sure what do you mean. I'm killing my processes all the time with
KeyboardInterrupt.
Do you mean that Keras has some recovery mechanism when it receives a
KeyboardInterrupt? (I know in blocks there is such a thing)

**Comment by fchollet** [comment]
This is a Python issue, not a Keras issue. When starting new threads with `Threading`, it becomes impossible to stop the children threads with a KeyboardInterrupt (unless some specific dispositions are taken, I assume).

**Comment by udibr** [comment]
After reading this answer http://stackoverflow.com/a/11436603/209852
I think the right solution is to use multiprocessing interface and not
threads (and my last PR will become unnecessary)
so trying to fix problem with threads is the wrong direction.

I am not an expert at any of this so my only concern is what is the side
effects. Up to now I never had problem killing a process using Keras.
So what problems should I expect?

**Pull request merged**
