### PR TITLE
Test mlp example

### PR DESCRIPTION
**Pull request by olegsinyavskiy**
Test mlp example.

Summary of changes:
 - configure additional entry in the travis matrix for examples
 - wrap example into function and call it from test for 1 training epoch

This is really useful to keep people interested increasing probability that keras would work out of the box.

P.S. Apparently NTP example became obsolete with the new api changes? Hopefully testing examples should help in such cases.

### CODE REVIEW

**Comment by olegsinyavskiy** [comment]
If this makes sense, I'm going to continue with other examples.

**Comment by phreeza** [comment]
I think this is a good idea.

One thing to keep in mind with this is that just as with the manual checks we used to have, these examples are not *unit* tests, so if we break something in them, we should really be simultaneously be breaking a unittest. If we don't, we should add a unittest to make sure the assumption that was violated gets tested in a modular way.

**Comment by olegsinyavskiy** [comment]
@phreeza , you're absolutely right. These are integration tests (I even wanted to rename those, but then thought that examples are fine too). The strategy I usually follow to set up testing for a new project is the following. Actively developing projects rarely have extensive test coverage and for a good reason: code is unstable and its too costly to support bunch of tests if api and core changes frequently. So the good policy is too add small amount IT tests that catch 'large' client-side bugs. However, as you said, when IT test is broken it is necessary to add unit test that catches this error. I found this 'top-down' (IT -> unit) approach work really well for RD projects under heavy use.

**Comment by fchollet** [comment]
I am not a fan of the idea of modifying every example to make them testable.
- examples are supposed to be 100% standalone scripts, they are not expected to follow any specific conventions.
- such tests would take up way more time and computational resources than necessary.

We do in fact already have something analogous to example testing / integration testing, in `test_tasks.py`. It's supposed to be integration tests for all common use cases of Keras. As such, they are already testing the architectures of several scripts from `examples/` (including the MLP), though not all (e.g. not IRNN or MemNN, etc).

The right way to expand example testing / integration testing would thus be do add new tests in `test_tasks.py` (which could also be refactored), covering new architectures, and running in very little time on synthetic data.

**Comment by olegsinyavskiy** [comment]
@fchollet , ok got it. I'm going to take a look at test_tasks then.

**Pull request closed without merging**
