### PR TITLE
adamax optimizer

### PR DESCRIPTION
**Pull request by kashif**
Added adamax optimizer from section 7 of Adam paper.

### CODE REVIEW

**Comment by fchollet** [comment]
Please add a unit test for your code.

**Comment by kashif** [comment]
@fchollet I thought i did, or do you mean a test somewhere else?

**Comment by fchollet** [comment]
Ok, seems reasonable. Please squash your 3 commits into one and I will merge this.

**Comment by kashif** [comment]
thank you @fchollet done!

**Pull request merged**
