### PR TITLE
Add batch_dot to backend

### PR DESCRIPTION
**Pull request by EderSantana**

### CODE REVIEW

**Comment by fchollet** [comment]
Could you also update the `engine.topology.Merge` layer to use `batch_dot` (and thus support dot/cos mode in TF)?

**Comment by EderSantana** [comment]
@fchollet maybe we want to consider adding a small constant to the denominator of `cos` mode to avoid division by zero. Also, my opinion is that `cos_dot` or something should be part of backend instead of reimplement it every time using `batch_dot`. What do you think?

**Comment by fchollet** [comment]
> maybe we want to consider adding a small constant to the denominator of cos mode to avoid division by zero

Indeed.

> Also, my opinion is that cos_dot or something should be part of backend instead of reimplement it every time using batch_dot. What do you think?

Is it used anywhere else? If it is used at least 2 times, then sure it sounds like a good idea to make it part of the backend.

Thanks for the PR.

**Comment by EderSantana** [comment]
`cos_dot` is useful for NLP lookup table and NTM. But indeed, none of those are being used right now. So lets leave a backend `cos_dot` for later.

**Pull request merged**
