### PR TITLE
Fixed multiprocessing in generators.

### PR DESCRIPTION
**Pull request by joeyearsley**
Previously, applying the `multiprocessing.Lock` did not synchronize variables across processes, to ensure files are not duplicated in an epoch we need these variables to be synchronized. 

To ensure they are synchronized the code now creates shared variables which are updated when the lock is applied. Therefore ensuring no duplicates in an epoch and batch. 

I've witnessed no overhead of this lock (due to the processing on the batch and minimal time the lock is actually held by a process. 

Sequences are recommended to keep order when using the prediction function since multiprocessing/threading can not guarantee threads will return in order. However, you can also use generators in your own multiprocessing pool and then use predict.

### CODE REVIEW

**Comment by ahundt** [comment]
General thought: could all processes be given a seed and an integer ID, which they all use to determine generate their batches modulo the total number of processes? 

Specific comment: make sure it is possible for the user to specify the exact seed which is used, so the randomness source used does not change if they change the data size or # of workers

**Comment by joeyearsley** [comment]
@ahundt I looked into it, passing PID's aren't assigned from 0 onwards, they can be 6001-6009 (i.e. 8 workers), how would you then determine the correct modulo? 
You could pass claim to pass it in as an argument through the queue, however you then are only getting pseudo random files, as each part of the list is split into 8. 

Exact seed? I've not altered the seed part from the original code, is it wrong in the original?

**Comment by joeyearsley** [comment]
Closed for now as there is a heisenbug, sometimes the processes all go to sleep with no hint at an error and other times it succeeds. Only happens in the validation stage.

**Comment by joeyearsley** [comment]
Found the issue, will be re-opening once I've cleaned the code up.

**Comment by Dref360** [comment]
First of all great work. I just need some clarification :P 

Maybe I do not understand this PR, but how does it fix the generator?
From what I understand, your PR is for the DirectoryIterator and not every generators right? Would there be an easy interface that we could extract from this to handle "most" generators?

**Comment by joeyearsley** [comment]
@dref We could alter the backend more, but I wanted to alter it as little as possible. 

I wanted to provide a solid example for which people could build off, the problem is that the backend and generators are always going to be coupled in some way. 

The important part is using `RawValue` to create the variables which need sharing across processes, otherwise, they all differ in value.
But, then we need a definite `generator.reset()` in the _evaluate_generator_ otherwise a dead process could hold a lock - since we just terminate without caring what part of the code they are in.

The problem with trying to handle most generators is that you are guessing the unknown, some people might have other types of shared variables they need to keep in sync across processes. If we try and capture all then we will have a problem.

This allows for online augmentations to be applied whilst keeping the file list generally in a set order, assuming all processes take the same amount of computation time, then all the files should be in order.
In the previous preprocessing code the file list was not synchronized hence you could immediately get the same file in the next mini-batch. This should circumvent that issues whilst still allowing for augmentations.

**Comment by ahundt** [comment]
> assuming all processes take the same amount of computation time, then all the files should be in order.

Could you elaborate? In general this is never true, even when executing the exact same static program twice, except on very carefully set up real time systems.

**Comment by joeyearsley** [comment]
The point is they will keep the majority of data not to be duplicated, whilst still allowing online augmentations.

To keep them strictly in order we need to alter the Process to a pool and alter the generators not to continously generate, but to be destroyed and recreated each epoch - so that we can call join and ensure we don't loop around the dataset again.

I can update the code to do this instead, what do you think?

More changes on the backend but would definitely keep order then.

**Comment by ahundt** [comment]
My comment was to point out one of the assumptions since I happened to come across it. I see performance vs repeatability reasons for each. I think users will need different behavior depending on application, networks for research and publication vs running quick experiments on datasets for business. I don't want to prognosticate too much because I'm mostly using tfrecords right now so I don't have a specific need for this feature and would rather not ask you to write code I don't need yet, so I leave the decision up to you. :-)

**Comment by joeyearsley** [comment]
After reviewing it more, I can add the guarantee of no duplicates with a Pool and async map plus callback.

However, for ordering this is not possible due to the process being multiple processes, to get around this we can either expect the user to do it in a `While` loop, therefore allowing strict ordering but negating the multiprocessing.

Expect the user to place multiprocessing into that loop with a Pool which waits for all the processes to finish in order - Maybe we can show some examples for them?

Or finally, make them use the Sequences class - which would not work for a dataset larger than memory. 

@ahundt @Dref360 Please can I have your input if this would be sufficient?
- I can't think of another way whilst ensuring flexibility in the user's generator and entire pipeline.

**Comment by joeyearsley** [comment]
After going down the rabbit hole, I've realised there is no way to do this other than @Dref360 's Sequences.

Even if you synchronize the queue putting, you can't lock easily lock the ordering of which items are returned by calling next on the generators. I.e. P2 can place on after P1 due to a semaphore, however it calls next after P3. Since you can't nicely synchronize inside the generator, it is is out of order. 

Also the sequences are a nicer design, with the important ordering kept in the parent thread instead of being potentially a few function calls down.

**Comment by joeyearsley** [comment]
Closing this issue, even this fix doesn't guarantee ordering, just reduces the likelihood. The proper way is to use sequences.

**Pull request closed without merging**
