### PR TITLE
epoch_offset argument for fit functions

### PR DESCRIPTION
**Pull request by wrongu**
When loading weights to resume training - which is a common use case for me - checkpoints cannot easily be used as-is. This PR introduces an `epoch_offset` argument to the `fit()` functions so that epochs (as seen by the callbacks) start counting at `epoch_offset`

This addresses some of the discussion in #1872

### CODE REVIEW

**Comment by carlthome** [comment]
This could be useful.

**Comment by mtamburrano** [comment]
+1, I'd like something like this, too

**Comment by TimRepke** [comment]
I really like the idea (stumbled upon this PR via the ticket mentioned).
But in the scenario, the actual intention is something different: continue training the model.

One solution would be to utilise `self._fit_loop` which is used internally anyway. If done right, the history and callbacks and settings from the original fit could be used without having to reinitialise all the other stuff. It's not just the epoch number.

So my suggestion is: add a function `continue_fit(nb_epochs)`. This way a developer could just bump this function for a few more epochs without having to copy all parameters + keep the history consistent without having to stitch it manually.
If someone agrees with this idea, I could implement it.

**Comment by wrongu** [comment]
@TimRepke good idea - I am yet to make use of `History` objects myself, so it didn't occur to me. Thinking some more about use cases, it seems that there are two different scenarios:

1. The model and callback objects stay in memory after the first round of training is done
2. The program exits after the first round of training is done

In 1) `continue_fit` works as expected (as long as `on_train_begin()` is skipped inside `_fit_loop()`, and something like this `epoch_offset` is still used)

In 2), which may be the more common use case especially for those training on shared clusters with time-limited jobs, custom 'stitching' is unavoidable in the sense that callbacks can only be resumed if their state was saved to a file and later reloaded

**Comment by robertomest** [comment]
@fchollet could I get the status on this PR? Are there any intentions on merging this? I'd be willing to modify it to comply to any desired changes if the @wrongu is not available.

**Comment by wrongu** [comment]
@robertomest rebased to the latest master branch. If there is more you'd like to add, feel free to take the PR over.

**Comment by robertomest** [comment]
@wrongu This look fine to me. I was just wondering if there was a reason this was not merged. Thank you!

**Comment by igormq** [comment]
@fchollet This PR would be useful to a lot of people. Are you intend to merge?

**Comment by kilotaras** [comment]
Do we need an extra parameter for that? Maybe a simple wrapper would be enough

```python
class EpochShiftedCallbackList(CallbackList):
    def __init__(self, callbacks=[], epoch_shift=0, queue_length=10):
        self.epoch_shift = epoch_shift
        super(EpochShiftedCallbackList, self).__init__(callbacks, queue_length)

    def on_epoch_end(self, epoch, logs={}):
        super(EpochShiftedCallbackList, self).on_epoch_end(epoch + self.epoch_shift, logs)

    def on_epoch_begin(self, epoch, logs={}):
        super(EpochShiftedCallbackList, self).on_epoch_begin(epoch + self.epoch_shift, logs)


```

**Comment by wrongu** [comment]
@kilotaras that would work too, but has an added layer of indirection that I'm not convinced is more simple. The callback list is created inside `_fit_loop`, so something like the `epoch_offset` argument into `_fit_loop` would be necessary regardless, right?

**Comment by kilotaras** [comment]
@wrongu yes, some of the automatically created callbacks won't be wrapped, so parameter is still needed.

**Comment by kencoken** [comment]
@wrongu it seems to me that this PR overcomplicates things – if the intention is to simply bump the epoch number for resuming in the middle of training, it would seem more sensible to simply do so instead of introducing the additional concept of an `epoch_offset`.

The current code breaks, for example, on line 1398 in `fit_generator`:

```
while epoch < nb_epoch:
```

As the offset is not added to the break condition – and there could be other places also.

I'd suggest that instead of adding a `epoch_offset` parameter, a `starting_epoch` parameter is added instead, which defaults to 0. Following this, the two places where the epoch counter is used (in `fit_generator` and the `_fit_loop` function) could be initialised appropriately. i.e.:

1. In `fit_loop`:
```python
797  for epoch in range(nb_epoch):
      [ becomes ]
797  for epoch in range(initial_epoch, nb_epoch):
```

2. in `fit_generator`:
```python
1338 epoch = 0
      [ becomes ]
1338 epoch = initial_epoch
```

@TimRepke – this doesn't directly address your issue with the history, but in any case am not sure whether a replay function such as `continue_fit(epoch)` necessarily can solve this either for the reasons given in (2) by @wrongu . I'd be a strong advocate for keeping things simple here.

**Comment by wrongu** [comment]
Redundant with #4429

**Pull request closed without merging**
