### PR TITLE
TimeDistributed masking(discussion, possible improvement)

### PR DESCRIPTION
**Pull request by DeNeutoy**
This PR is intended as a discussion of the function of masking in the `TimeDistributed` wrapper, with some code to potentially demonstrate a different way it could work. It's certainly possible that we have mis-used `TimeDistributed` in a way that you have not intended - if this is the case, please just say and close this PR. 

We have been using `TimeDistributed` in order to apply generic sequence encoders (eg LSTM, BOW) to a number of inputs across a particular dimension: `(num_samples, num_sentences, num_words, embedding_size) --> (num_samples, num_sentences, embedding_size)`. Specifically, the below problem arises because the function being `TimeDistributed` changes the dimension of its inputs from `(batch_size, num_words, embedding_size) --> (batch_size, embedding_size)`.

In this case, there are two issues: 

1) the mask is not passed to the `K.rnn` function applying the encoder each of the sentence inputs(where the time dimension here is num_sentences)

2) the `TimeDistributed` layer just returns the input mask, which is no longer the correct shape: `(batch_size, num_sentences, num_words)`. Normally, you would assume that after a layer which encodes inputs in such a way, you would no longer need a mask - however, in this case, it is possible that different numbers of sentences are passed for a given input, meaning that we still require a mask of shape `num_samples, num_sentences` to guard against this.

The code in this PR suggests two things:

1) The mask received by `TimeDistributed` should be passed to the `K.rnn` function. 

2) If  the dimension of the inputs is changed by the encoder, create a mask which is all ones unless for a given dimension, the input mask is all zeros (this addresses the fact that an entire sentence might be masked). One issue here is there is no way (I don't think) to check which dimensions have been reduced. This would be a possible reason to not implement this part of the PR, but we think that the first point certainly is relevant. The implementation in the `compute_mask` function of this PR assumes that if the dimension has changed by `n`, the output dimensions are just `input_shape[:-n]`. This is obviously not ideal. I've included it as a discussion point and if others can see a way to specify the dimensions which are reduced, I think this would be a good feature.

Thanks! Keras is great.

@pdasigi

### CODE REVIEW

**Comment by fchollet** [comment]
> The mask received by TimeDistributed should be passed to the K.rnn function.

That sounds reasonable.

> The implementation in the compute_mask function of this PR assumes that if the dimension has changed by n, the output dimensions are just input_shape[:-n]. This is obviously not ideal.

That's not reasonable.

`compute_mask` should use the `compute_mask` method of the underlying layer. Essentially breaking up the input mask into chunks, passing each chunk to the `compute_mask` method of the child layer, and reconstructing the mask using the outputs. I think. Unless you see problems with this idea.

Check should also check if `compute_mask` just returns the input mask, since in that case we can skip mask computation altogether (which could be expensive).

**Comment by matt-gardner** [comment]
@fchollet, I think that breaking the mask up and passing it to the child layer makes sense, but what do you do when the child layer returns `None`?  This is the case with LSTMs and other sentence encoders.

One option would be to just return `None` if the child layer returns `None` at any time step.  However, it's not unlikely that you've done some padding if you're using `TimeDistributed`, to handle variable length sequences, and this padding is what you really need the mask to capture.  How can you handle this?

It could be that it's just too complicated to make a single `TimeDistributed` class handle all possible ways that someone might want to use it for masking, and we should handle this variable-length encoder masking as a subclass of `TimeDistributed` (this is what we already do; I work with @DeNeutoy).  As long as we fix the passing of the input mask to the `K.rnn` function, I think it's fine to leave specific handling of the output mask to a subclass, unless we can come up with a general default that's suitable for most use cases.

**Comment by DeNeutoy** [comment]
Would it be simpler to introduce a new argument to `TimeDistributed`, which is: `reduced_dimensions=None`. This would be a list/tuple of dimensions which your Layer reduces (automatically assumed to be none), which would allow the direct computation of the mask in `TimeDistributed` by computing `K.any(input_mask, reduced_dimensions)`, as this would return a mask value of 0 for that dimension iff there was no input. If there was input, the mask should be 1, as the masking would have already been handled by passing the `input_mask` to `K.rnn`. This would also be more naturally backward compatible. 

Thoughts @matt-gardner, @fchollet?

**Comment by fchollet** [comment]
Closing outdated PR. If you still care about the content of the PR, please submit a new PR to `master`, updated for the Keras 2.0 API.

**Pull request closed without merging**
