### PR TITLE
Add scikit_learn wrapper example

### PR DESCRIPTION
**Pull request by dansbecker**
I created this example for myself while trying to figure out how to use the sklearn wrapper, and I hope it's useful to others as well. Thanks for any feedback.

### CODE REVIEW

**Comment by fchollet** [comment]
Sounds good. I would add a last section instantiating a model with the best configuration, training it and finally testing it on the test data.

**Comment by dansbecker** [comment]
Here's an update where, instead of instantiating a new model and training it, I just pulled the best model from the validator using `best_model = validator.best_estimator_.model`.  

Is the best_estimator trained on less than the full training data (i.e. just a few of the folds)?  If not, this seems to me to be both faster and less complex than instantiating and training a new model.

If best_estimator_ is trained on less than the full training data, so the ideal workflow is indeed to instantiate a new model, then I'll update this to that workflow.

Thanks.

**Comment by fchollet** [comment]
> Is the best_estimator trained on less than the full training data (i.e. just a few of the folds)? If not, this seems to me to be both faster and less complex than instantiating and training a new model.

Yes, `best_estimator` is trained on N-1 folds as I understand. What you would do e.g. in a competition setting is to reinstantiate the model and fit it on 100% of the training data. The benefits are small, but real.

**Comment by dansbecker** [comment]
Hi @fchollet,

I just looked into this in the sklearn docs, and from [this section on GridSearchCV](http://scikit-learn.org/stable/modules/generated/sklearn.grid_search.GridSearchCV.html), it appears best_estimator is already refitting the model on all of the training data.

Specifically, I'm seeing this in the refit argument, which defaults to True.  To mitigate the potential confusion we are discussing, best_estimator_ isn't available unless we've set that argument to refit the model on all of the training data.

**Comment by fchollet** [comment]
Great, good to know.

**Comment by omarcr** [comment]
Thank you for this contribution. Very useful.

**Pull request merged**
