### PR TITLE
Clip value as in Neural Turing Machines paper

### PR DESCRIPTION
**Pull request by EderSantana**
Check this out from Neural Turing Machines paper. Last phrase before Conclusions, almost unnoticed.

clip value

### CODE REVIEW

**Comment by fchollet** [comment]
Ok, looks good. Though I'd be surprised if the effect was significantly different from norm clipping : )

**Comment by EderSantana** [comment]
Yeah... the thing is once I had this RNN whose spectral radius was growing and norm clipping was not fixing it. I want to see if this helps.

**Comment by DingKe** [comment]
Considering clipvalue is positive and the definition of clip (http://deeplearning.net/software/theano/library/tensor/basic.html#theano.tensor.clip), shouldn't it be T.clip(g, -self.clipvalue, self.clipvalue) instead of T.clip(g, self.clipvalue, -self.clipvalue)?

**Comment by EderSantana** [comment]
Thanks @DingKe, PR here https://github.com/fchollet/keras/pull/734

**Pull request merged**
