### PR TITLE
Bug fix: Support multiple outputs in Lambda layer

### PR DESCRIPTION
**Pull request by farizrahman4u**
#7221

### CODE REVIEW

**Comment by fchollet** [comment]
Lambda tests are failing: https://travis-ci.org/fchollet/keras/jobs/249670539

If fixing a bug, please add a unit test that would have failed with master but passes with the new PR.

**Comment by PavlosMelissinos** [comment]
Thanks for the PR!

As for having a unit test, I already have a failing case in the mentioned issue, so would adding something like this to `tests/keras/layers/core_test.py` be a start? I'm not awfully familiar with unit tests, especially on keras.

```
# test layers with multiple outputs
def split(inputs):
    return [inputs, inputs]

def compute_split_output_shape(input_shape):
    return [input_shape, input_shape]

def compute_split_mask(inputs, mask=None):
    return 2 * [None]

layer_test(layers.Lambda,
           kwargs={'function': split,
                   'output_shape': compute_split_output_shape,
                   'mask': compute_split_mask},
           input_shape=(8, 64, 64, 3))
```

**Comment by farizrahman4u** [comment]
@PavlosMelissinos That would work. Change the `split` function to something like:

```python
def func(x):
    return [x * 0.2, x * 0.3]
```

PR to patch-1 of my fork.

**Comment by PavlosMelissinos** [comment]
Done.

**Comment by PavlosMelissinos** [comment]
It fails because of [this](https://github.com/fchollet/keras/blob/master/keras/utils/test_utils.py#L86). 

y is a list of two tensors but K.dtype expects a tensor as input so how should we go about this?

Is there a better way than this?
```
if isinstance(y, list):
    for tensor in y:
        assert K.dtype(tensor) == expected_output_dtype
```

**Comment by fchollet** [comment]
@PavlosMelissinos that sounds reasonable.

**Comment by PavlosMelissinos** [comment]
The test is still failing. It seems that the `layer_test` function assumes that the layer has a single input and a single output.

<pre>Test routine for a layer with a <b>single</b> input tensor and <b>single</b> output tensor.</pre>

Is there a different test for multiple input/multiple output layers? I can't find anything and merge layers implement their own assertions, as you can see [here](https://github.com/fchollet/keras/blob/master/tests/keras/layers/merge_test.py).

Should we maybe create a separate function for multi-input/multi-output layers?

Either way, [here's my proposed fix](https://github.com/farizrahman4u/keras/pull/13). I also changed the description of the test function to more accurately reflect its new role.

**Comment by farizrahman4u** [comment]
@PavlosMelissinos There is one more issue regarding multiple masks I guess.. I am not on my work machine and can't run any tests locally. Please look into it.

**Comment by PavlosMelissinos** [comment]
Sorry for not responding but I've had to beat a deadline at work for yesterday. Unfortunately my pc at home has windows and is old so I can't do proper development and I don't have proper debugging access to my work machine from here.

I need to take a closer look with a proper tool like pycharm which I don't have at the moment but I'll be able to work on the issue on Monday.

**Comment by PavlosMelissinos** [comment]
The issue with the multiple outputs seems to be fixed on python 3.5. Doing a full test run to make sure nothing else has been broken before I submit a PR for review.

**Comment by PavlosMelissinos** [comment]
Question:

In [utils/test_utils.py](https://github.com/fchollet/keras/blob/master/keras/utils/test_utils.py#L113-L140), there's a "test as first layer in Sequential API" block that won't work for layers with multiple outputs (because of Sequential).

I've put it into an if block for the time being that is bypassed when actual_output is not a numpy array. Should it be replaced with a similar test for the Functional API in this case?

**Comment by fchollet** [comment]
Instead of trying to modify the test utils, I suggest you simply write an independent unit test, a one-off. Not everything has to be covered by utils. Their purpose is to avoid redundancy.

**Comment by PavlosMelissinos** [comment]
Oh, that's much simpler than what I did. While the tests seem to pass, the code is ugly so I'll just push a new PR following your suggestion (something like the tests for the merge layers should be enough I guess).

I thought it would be better to go all the way and use the existing infrastructure but the result ended up being worse.

**Comment by farizrahman4u** [comment]
@PavlosMelissinos Hi there. Any updates? Thanks.

**Comment by PavlosMelissinos** [comment]
[Yeah!](https://github.com/farizrahman4u/keras/pull/15). I thought you'd get a notification but I should have pinged you anyway, my mistake.

I followed @fchollet's suggestions and tried to keep the test as minimal as possible. On python 3.5 it passes the tests for all backends (but for their latest binaries; I didn't build them from source).

Sorry for the confusion but initially I couldn't run the tests locally and that led to some awkward errors.

**Comment by PavlosMelissinos** [comment]
More specifically, the clean diff for this PR should be the following two parts:

[keras/layers/core.py](https://github.com/PavlosMelissinos/keras/compare/59cd1c3...patch-1-off#diff-05ec8fc63f0e9bb35f99c0ca76a66d0e)
and
[tests/keras/layers/core_test.py](https://github.com/PavlosMelissinos/keras/compare/59cd1c3...patch-1-off#diff-b76dfb825f06f834acd550a2e625b37d)

**Comment by farizrahman4u** [comment]
@fchollet

**Comment by v1nc3nt27** [comment]
This should be fixed in 2.0.8, correct? Because for my Lambda layer
`attention = Lambda(lambda x: AttentionLayer(x), output_shape=[(20,200), (20, 50)], name='test')(encoder)`
I still get an error:

>   File "/home/anaconda3/envs/python3.6/lib/python3.6/site-packages/Keras-2.0.8-py3.6.egg/keras/engine/topology.py", line 640, in __call__
>   File "/home/anaconda3/envs/python3.6/lib/python3.6/site-packages/Keras-2.0.8-py3.6.egg/keras/engine/topology.py", line 702, in _add_inbound_node
> IndexError: list index out of range

**Pull request merged**
