### PR TITLE
add identity matrix initialization

### PR DESCRIPTION
**Pull request by transcranial**
as an example of its use, see http://arxiv.org/abs/1504.00941

### CODE REVIEW

**Comment by mthrok** [comment]
@fchollet 
Is replacing the initialization of SimpleRNN (https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L12) with this identity matrix turns it to the model discussed in the above paper?

**Comment by fchollet** [comment]
@mthrok assuming we're looking at a square matrix, then yes. In general, I would prefer orthogonal initialization for RNNs since it has the same useful properties as identity, while being random and being generalizable to non-square matrices.

**Comment by mthrok** [comment]
@fchollet 
That completely makes sense.

**Comment by transcranial** [comment]
on my own tests with the IMDB dataset, setting inner_init to identity appears to be better than orthogonal, with ReLU units.

**Comment by mthrok** [comment]
@transcranial That's interesting. Thanks for nice work

**Pull request merged**
