### PR TITLE
Time-Masked RNN

### PR DESCRIPTION
**Pull request by wxs**
This introduces a new mode to the SimpleRNN where it can be
"time-masked" in which case the input shape to the layer becomes doubled along the time
dimension, with X[:,X.shape[1]//2:,0] becoming a mask vector which, when
set to 0, compels the _scan function to simply copy its h_tm1 to the
output.

I've only added this to SimpleRNN. I know there's been some discussion in the issues here about masking so I think this could be helpful to some other people as well. I'm happy to discuss further if there are questions about this!

My test fails sometimes, because depending on the initialization of the RNN it sometimes fails to learn the simple rule (copy input x_0 to get output). I am happy to discuss better testing approaches here, one approach could be to just train the unmasked model several times and ensure at least one converges.

Incidentally I also added an empty `__init__.py` to the tests directory so that I could use it as a module

### CODE REVIEW

**Comment by fchollet** [comment]
As we were discussing, an alternative option would be to stop iterating on a sequence when an all-0 feature vector is encountered. https://github.com/fchollet/keras/issues/176

This would only require minimal changes to the existing layers. The only real issue would be that it would prevent the use of all-0 feature vectors as regular vectors, but as long as this is clarified in the documentation I don't think it would be a significant issue.

**Comment by wxs** [comment]
Hmm, one thing I'm realizing: instead of doubling the size of the time dimension here, I could also increase the dimensionality of the tensor by one, so it becomes (nb_samples, timesteps, nb_dimensions, 2) dimensions, and the mask goes on dimension 1, the data on dimension 0.

That might make things a bit more clear

**Comment by fchollet** [comment]
> Hmm, one thing I'm realizing: instead of doubling the size of the time dimension here, I could also increase the dimensionality of the tensor by one, so it becomes (nb_samples, timesteps, nb_dimensions, 2) dimensions, and the mask goes on dimension 1, the data on dimension 0.

Definitely makes more sense. It would still be rather inefficient (all data x2).

**Comment by wxs** [comment]
Oh actually: here's a solution for that inefficiency. I add the mask along the *dimension* axis. Now there's no wasted data:

(nb_samples, timesteps, nb_dimensions + 1)

 and then X[:,:,-1] is the mask.

**Comment by wxs** [comment]
So I've updated the PR with 2 things:

 - The mask is now concatenated along the dimension axis, removing excess values from data array
 - the Embedding layer can now be given a mask, which it passes along unchanged.

As I mentioned over in the issue #176 I'm worried about simply using the 0 vector as a mask sentinel, since with ReLU activations we can easily "naturally" get 0 vectors.

**Comment by wxs** [comment]
Currently I'm getting an error when I run this on a GPU around a downcast in the scan. I'm investigating, but if you've seen this error before it might help me narrow things down:

```
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 2) has dtype float32, while the result of the inner function (`fn`) has dtype float64. This can happen if the inner function of scan results in an upcast or downcast.
```

**Comment by wxs** [comment]
What do you think of introducing a "Mask" layer that introduces the mask so the user does not need to actually know exactly how the mask is formatted internally? Something like:

    def my_mask(X):
        return X==0

    model = Sequential()
    model.add(Mask(function=my_mask))
    model.add(Embedding(indim, outdim, pass_mask=True))
    model.add(SimpleRNN(outdim, outdim, time_mask=True))

**Comment by fchollet** [comment]
This seems like a solid idea, but also quite a bit verbose / boilerplatey in its usage. The same result can be achieved with:
```python
# assumes pre-padding with '0' as index of non-character.
model = Sequential()
model.add(Embedding(indim, outdim, mask_value=0.)) # replaces index 0 with all-0. vectors
model.add(SimpleRNN(outdim, outdim, mask_value=0.)) # skips all-0. vectors
```

**Comment by wxs** [comment]
Oh that does seem better. But I still propose that that mask_value is inherently unsafe on ReLUs. I prefer 

    # assumes pre-padding with '0' as index of non-character.
    model = Sequential()
    model.add(Embedding(indim, outdim, mask_value=0.)) # masks 0 values
    model.add(SimpleRNN(outdim, outdim, masked_input=True)) # tells it that the input includes a mask

Internally it's safer, and it looks just as easy to the user.

**Comment by wxs** [comment]
Per our discussion I've put up #244 as a replacement to this, and will close this PR

**Pull request closed without merging**
