### PR TITLE
Add #Argument and #Examples in backend/common

### PR DESCRIPTION
**Pull request by keunwoochoi**
Let me know how you think of this style and if this 'syntax' works well for the generated document. 

Also I need some explanation for those four functions below (`get_uid()..`)

### CODE REVIEW

**Comment by fchollet** [comment]
There is unrelated code bundled with the PR.

Please note that the syntax for adding examples would be to put  "```" around code blocks (see other docstrings for examples).

**Comment by keunwoochoi** [comment]
* Formatting: Okay.
* Unrelated code bundled: Could you elaborate? You mean, is the examples too verbose/kind?

**Comment by keunwoochoi** [comment]
The original example style is

```python
        # Crop the input 2D images or feature maps
        model = Sequential()
        model.add(Cropping2D(cropping=((2, 2), (4, 4)), input_shape=(3, 28, 28)))
        # now model.output_shape == (None, 3, 24, 20)
        model.add(Convolution2D(64, 3, 3, border_mode='same))
        model.add(Cropping2D(cropping=((2, 2), (2, 2))))
        # now model.output_shape == (None, 64, 20, 16)

```
in `common.py`, this 'new' style is...
```python
        >>> keras.backend.epsilon()
        1e-07
```
which can be converted like this:
```python
      eps = keras.backend.epsilon()
      # eps is 1e-07
```
.

My opinion is that this new style can be better to read for examples like this:

```python
    >>> keras.backend.epsilon()
    1e-07
    >>> keras.backend.set_epsilon(1e-05)
    >>> keras.backend.epsilon()
    1e-05
```

But it's your call, just let me know.

**Comment by fchollet** [comment]
> Unrelated code bundled: Could you elaborate?

I mean you should pull master and rebase.

> new style

That's fine, but it should be inside a code block, not plain text. Your current code is plaintext.

**Comment by keunwoochoi** [comment]
Rebase is done.

**Comment by keunwoochoi** [comment]
@fchollet PR'ed, but still working on tensorflow backend documentation. So it's not ready to merged (it  would be okay to do though). Please take a look and let me know how do you think of them.

**Comment by fchollet** [comment]
You still appear to have big issues with your Git workflow...

**Comment by fchollet** [comment]
Otherwise I do agree with your points.

**Comment by keunwoochoi** [comment]
Opened new PR #4668

**Pull request closed without merging**
