### PR TITLE
New conv ops

### PR DESCRIPTION
**Pull request by fchollet**
@EderSantana added new function signatures in the backend while abstracting away common functionality on the TF side.

### CODE REVIEW

**Comment by fchollet** [comment]
To be honest it's not fully clear to me how to handle `output_shape` in `deconv`.

**Comment by fchollet** [comment]
I'm done for now. What's left (a huge amount, actually):

- adding `deconv2d`, `atrous_conv2d` in the Theano backend. `separable_conv2d` may be TF-only for the time being. Common parts may be abstracted in helper functions like for the TF implementation.
- adding backend tests for `decond2d`, `atrous_conv2d`, `separable_conv2d`.
- adding layers `Deconv2D`, `AtrousConv2D` and `SeparableConv2D`.
- support for `ZeroPadding3D` in TF.

For easier implementation of all these layers, we may need to abstract common parts in an ancestor class.

**Comment by fchollet** [comment]
Btw, although conv3d, max_pool3d are in the TF docs, they don't seem to be part of the latest version from pip. Anyone knows when they were introduced?

**Comment by fchollet** [comment]
Appears to be from 0.9.0 on. I'll upgrade the Travis config, which was still on 0.7.

**Comment by EderSantana** [comment]
what is the final word? should I close the other PR and work with you on this one instead? yeah, TF deconv output_shape is weird... I thought I could just pass it from the caller

**Comment by fchollet** [comment]
> what is the final word? should I close the other PR and work with you on this one instead? yeah, TF deconv output_shape is weird... I thought I could just pass it from the caller

I'm going to merge the current PR as soon as the tests pass (as far as I can tell it is good to go). So you can work from master! 👍

**Comment by mmmikael** [comment]
I am not seeing a `Deconv2D` layer in the merge. Was this one dropped at some point?

`deconv2d` is implemented in the Tensorflow backend but not called anywhere.

**Comment by EderSantana** [comment]
@mmmikael check this PR #3251

**Pull request merged**
