### PR TITLE
Improvements to Neural Style Transfer

### PR DESCRIPTION
**Pull request by titu1994**
Incorporates the improvements suggested in https://github.com/fchollet/keras/pull/6872

Specifically - 
1) Uses VGG 19 rather than VGG16.
2) Uses block5_conv2 (conv5_2) layer for better results, in contrast to conv4_2 as suggested by the original paper.
3) Image initialization is now done using the content image itself, rather than noise.

### CODE REVIEW

**Comment by fchollet** [comment]
Please provide an example image (or two) generated with the default settings.

**Comment by titu1994** [comment]
Will do. Since it takes quite some time to generate images, will 20 iterations of the algorithm be sufficient?

**Comment by titu1994** [comment]
Here is the output after 20 iterations, on the style image given below : 
Style - "Patterned Leaf"
patterned_leaves

The following images were with default settings, run for 20 iterations each.

Old model (VGG16, noise initialization, conv4_2) - 
old_at_iteration_19

New model (VGG19, content image initialization, conv5_2) - 
new_at_iteration_19

----
The following images are from my repository (using Network.py, which is a replica of the Keras example with variables exposed), with default settings (VGG 19, content initialization, conv5_2, **Total Variation Loss weight of 8.5e-5, some have color preservation post processing (which does not affect style transfer)**). 

Each example has the result in the center, the content in the upper right corner and the style in the bottom right corner. Open and zoom in for finer details which are obtained using conv5_2 and VGG 19, and no noise in the images due to content initialization. 

Please disregard the text, it was for a demonstration - 
lost-grounds

**Comment by fchollet** [comment]
LGTM, thanks

**Pull request merged**
