### PR TITLE
PEP8 style cleanup

### PR DESCRIPTION
**Pull request by iskandr**
I started working on a branch to add bidirectional RNNs but in the process got distracted by the loose and varying style across some of the files in Keras. I'm not sure how welcome nitpicky style PRs are in Keras, but hopefully this is useful or at least tolerated:

* removed unused imports
* deleted assignments to unused variables
* broke up longer lines (not sticking strictly to an 80 character limit but tried to split up anything that I found hard to read)
* add spaces between arithmetic operators
* grouped imports into (1) core library (2) external libraries (3) relative package imports 
* open files using `with` contexts

### CODE REVIEW

**Comment by iskandr** [comment]
@fchollet I'm not sure what you think of big style cleanups or even what level of PEP8 conformance you're aiming for in this project. How does this PR look to you?

**Comment by fchollet** [comment]
> what level of PEP8 conformance you're aiming for in this project

None at all, though I do aim at reasonably clean code. The only upside of strict PEP8 compliance would to prevent complaints about PEP8 and PRs PEP8-ing the codebase... 

PEP8 doesn't make your code better. It's not what you should focus on. Conceptualizing problems and data flows in very simple terms is what makes your code better.

My standard is: the code should be at least readable, and preferably somewhat pretty. Of course it's completely subjective. PEP8 is to beautiful code what Vitruvius' theories of anatomic proportions are to human beauty. 

> How does this PR look to you?

Some of the style changes are reasonable, but most of them seem to be about line size. I don't agree that all lines should be under 79 characters. Lines should be broken down in a reasonable way. Long lines are sometimes justified; we aren't writing code on TI-89s after all.

**Comment by iskandr** [comment]
>None at all, though I do aim at reasonably clean code. The only upside of strict PEP8 compliance...

Sorry, I didn't mean to come off as trying to push strict PEP8 style where it's not wanted -- I don't adhere to it "strictly" either, it's just a useful reference for common style preferences across many different projects (each of which choose their own subset). Since I didn't see a style guide for committers, I chose a few things that make the code seem cleaner to me and wanted to see how that gels with your preferences. 

>Some of the style changes are reasonable, but most of them seem to be about line size. 

What do you think about the changes aside from line length? 

* removed unused imports
* deleted assignments to unused variables
* add spaces between arithmetic operators
* grouped imports into (1) core library (2) external libraries (3) relative package imports
open files using with contexts

I have to admit that some of Keras looks a little messy to me and I'd like to tidy up as much as is welcome.

**Comment by fchollet** [comment]
> I have to admit that some of Keras looks a little messy

To an extent that's right. I'll do some cleaning up myself, and I will consider writing up a short style guide for contributors. In the meantime, please no style-related PRs; feature-related PRs are more valuable.

**Pull request closed without merging**
