### PR TITLE
Use symbolic shape in tensorflow version of batch_flatten

### PR DESCRIPTION
**Pull request by stas-sl**

### CODE REVIEW

**Comment by fchollet** [comment]
Yeah, seems reasonable.

**Comment by srebuffi** [comment]
Hi,

When I created a non sequential model using the Flatten layer with Keras with tensorflow backend, I got an error whereas the old version seems to work (see below).

>>> pool2_bis
<tf.Tensor 'Reshape_894:0' shape=(?, 2048, 1) dtype=float32>
>>> [-1, prod(shape(pool2_bis)[1:])]
[-1, <tf.Tensor 'Prod_5:0' shape=() dtype=int32>]
>>> [-1, np.prod(pool2_bis.get_shape()[1:].as_list())]
[-1, 2048]

This thread reports the same error https://github.com/fchollet/keras/issues/3450

**Comment by stas-sl** [comment]
Hi. The original problem that I was trying to fix was with this code, when using `batch_flatten` in loss function.

```
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

from keras import backend as K
from keras.models import Model
from keras.layers import Convolution2D, Input

def my_loss(y_true, y_pred):
    y_true_f = K.batch_flatten(y_true)
    y_pred_f = K.batch_flatten(y_pred)
    return K.mean(y_true_f * y_pred_f)

K.set_image_dim_ordering('tf')
image_shape = (None, 128, 128, 1)
images = Input(shape=image_shape[1:])

output = Convolution2D(1, 3, 3)(images)

model = Model(input=images, output=output)
model.compile(optimizer='sgd', loss=my_loss)
```
I got the following error:
```
<ipython-input-1-b426c31b42c5> in my_loss(y_true, y_pred)
     11 
     12 def my_loss(y_true, y_pred):
---> 13     y_true_f = K.batch_flatten(y_true)
     14     y_pred_f = K.batch_flatten(y_pred)
     15     return K.mean(y_true_f * y_pred_f)

/Users/stas/.pyenv/versions/anaconda-2.4.0/lib/python2.7/site-packages/keras/backend/tensorflow_backend.pyc in batch_flatten(x)
    776     '''
--> 777     x = tf.reshape(x, [-1, np.prod(x.get_shape()[1:].as_list())])
    778     return x
    779 

/Users/stas/.pyenv/versions/anaconda-2.4.0/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in prod(a, axis, dtype, out, keepdims)
   2490         except AttributeError:
   2491             return _methods._prod(a, axis=axis, dtype=dtype,
-> 2492                                   out=out, keepdims=keepdims)
   2493         return prod(axis=axis, dtype=dtype, out=out)
   2494     else:

/Users/stas/.pyenv/versions/anaconda-2.4.0/lib/python2.7/site-packages/numpy/core/_methods.pyc in _prod(a, axis, dtype, out, keepdims)
     33 
     34 def _prod(a, axis=None, dtype=None, out=None, keepdims=False):
---> 35     return umr_prod(a, axis, dtype, out, keepdims)
     36 
     37 def _any(a, axis=None, dtype=None, out=None, keepdims=False):

TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'
```

It seems, that during compilation loss function doesn't know what are the dimensions of its parameters. But after changes in this PR it successfully compiled.

Also I looked at Theano version of `batch_flatten` that uses dynamic shape (and I didn't have problems while compiling using Theano):
```
...
x = T.reshape(x, (x.shape[0], T.prod(x.shape) // x.shape[0]))
...
```
So, I thought it would be reasonable to use dynamic shapes for TF as well.

BTW, there is a good [explanation](http://stackoverflow.com/questions/37096225/how-to-understand-static-shape-and-dynamic-shape-in-tensorflow) of differences between static and dynamic shape inference in TF.

The TF issue can be seen here:
```
import numpy as np
import tensorflow as tf
shape = (None, 128, 128, 1)
x = tf.placeholder(tf.float32, shape=image_shape)

tf.reshape(x, [-1, np.prod(x.get_shape()[1:].as_list())]).get_shape()
# returns TensorShape([Dimension(None), Dimension(16384)])

tf.reshape(x, [-1, K.prod(K.shape(x))]).get_shape()
# returns TensorShape([Dimension(None), Dimension(None)])
...
```
As seen, in the second case TF can't infer the shape.

Actually, now I'm not sure what would be the correct solution to the issue. And whether it is a TF issue or not (because in Theano same shape arithmetics works OK)

**Comment by ozabluda** [comment]
This PR broke https://github.com/tensorflow/tensorflow/issues/13568

**Comment by ozabluda** [comment]
Maybe PR https://github.com/tensorflow/tensorflow/pull/13561 fixes it. Maybe the problem is/was triggered by -1 in reshape
https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/keras/python/keras/backend.py#L2091

**Pull request merged**
