### PR TITLE
fix tensorflow travis config

### PR DESCRIPTION
**Pull request by transcranial**
ref issue #1103

### CODE REVIEW

**Comment by fchollet** [comment]
Cool, thanks. However, it looks like it doesn't solve the TensorFlow installation issue: https://travis-ci.org/fchollet/keras/jobs/93735270

**Comment by fchollet** [comment]
Cool, thanks!

**Comment by rushter** [comment]
https://github.com/fchollet/keras/pull/1016#issuecomment-156842267
I closed my PR till python 3 version...

**Comment by fchollet** [comment]
A few days ago we decided to release next Tuesday or so, and we will need Travis integration before then. Python 2.7-only it is.

**Pull request merged**
