### PR TITLE
Added Rotate1D and Rotate2D to core.py

### PR DESCRIPTION
**Pull request by pjadzinsky**
Hi,

This layers help solve several border problems when working for example with temporal data and/or images. I'm using them to align or register the outputs of different layers.

### CODE REVIEW

**Comment by fchollet** [comment]
- What are some use cases?
- Could you add a quick test (layer-only, in the same spirit as our existing layer tests) so we can check that it works as advertised?

**Comment by pjadzinsky** [comment]
I apologize for the long message...

* This would be useful for example with a CNN, where each unit in a representation has a specific meaning (i.e., first time point, upper left corner an image). After doing the convolution (border_mode='same'), the representation is rotated due to border issues as described in [#531](https://github.com/fchollet/keras/issues/531#issuecomment-132613462). This layer will allow you to put the 1st unit back in the 1st place. for comparison with for example the same representation prior to the convolution. If using other border modes in convolution, other layers would be needed
  * border_mode='same', requires rotation of the representation (this PR)
  * border_mode='valid', requires adding units at the beginning of the output (I've made ZeroPad that allows for this)
  * border_mode='full', requires deleting units at the end of the output (this would be the Split layer [#531 towards the end](https://github.com/fchollet/keras/issues/531#issuecomment-132613462))

* Before I get into the test let me ask you something else. I think in [#302](https://github.com/fchollet/keras/issues/302) someone suggested that Sequential should be the introductory model for new people but experience users will most likely use Graph models. Do you share this view? If so, keep reading. When developing layers for Sequential models the `input` has to be specified and that's why we end up with the 1D and 2D version of each layer (no current implementation for higher tensors). I think this is not true for Graphs since in there I think I was able to implement a functional Rotate layer that works independently of the tensor dimension. Therefore, is it worth to continue to develop the 1D and 2D version of the layers when we could implement just a generic one, that will also be useful with any tensor? If the sequential model is in there for back compatibility and to show new users how simple it is to use keras (which is awesome) I think there is no need to give new users access to every single layer. The advantages I see for layers that are independent of tensor dimensions are:
* work with any tensor a user might want to use
* easy to develop, just one case
* less clutter in namespace

The only disadvantage I see is lack of support for Sequential models. But again, at least I used the sequential model twice, then realized that needed something more general, try the Graph and never used the Sequential model again.

**Comment by pjadzinsky** [comment]
Are these the tests you wanted me to include?

**Comment by fchollet** [comment]
Tests seem to be failing. Can you check?

**Comment by pjadzinsky** [comment]
I'm sorry about that. I'm really trying to catch up. Thanks for the patience

If I run: `python tests/auto/keras/layers/test_core.py` it says it ran 19 tests and all are ok

**Comment by fchollet** [comment]
I have concerns that the use of `set_subtensor` might be quite inefficient (since it is copying entire tensors). Is there any way to do the same with broadcasting? After all, none of the values your are touching are actually changing.

Otherwise, I find the description of `Rotate1D` to be somewhat unclear. References to the specific meaning of each dimension should be avoided if it isn't relevant to the computation -- the second dimension might not be time. Besides, it is not clear what "rotating" a `(time, features)` tensor actually means (I had to read the code to get it), so that should be clarified. Finally, the choice of the names `1D` / `2D` might be problematic, since they are actually applied to 2D and 3D tensors respectively.

**Comment by pjadzinsky** [comment]
Wait, this is not working with Sequential models although works well with Graph. I don't understand why but let me try to figure it out.

**Comment by fchollet** [comment]
We won't merge this. I think such layers would probably benefit from being listed in a library of Keras extensions.

**Pull request closed without merging**
