### PR TITLE
Layers/Convolution2D: Add input_dim member as a function of image_sha…

### PR DESCRIPTION
**Pull request by osh**
…pe to allow use with AutoEncoder

### CODE REVIEW

**Comment by tdhd** [comment]
In the case of the default argument where `image_shape=None` taking the product will fail.

**Comment by osh** [comment]
With Dense, input_dim is a required argument, image_shape being optionally defined seems somewhat inconsistent

**Comment by fchollet** [comment]
`input_dim` is available on Dense layers and some other layers *as internal parameters* of these layers. They're not part of the standard layer API and are not supposed to be accessed by other layers.

The AutoEncoder class is undergoing refactoring and I would expect that this dependency to disappear.

**Comment by fchollet** [comment]
Autoencoders were refactored recently, and input_dim is no longer used (as it should...). Closing this!

**Pull request closed without merging**
