### PR TITLE
fix race condition when re-using a generator immidiately after training

### PR DESCRIPTION
**Pull request by osh**
without join()'ing generator threads, there is no guarantee they have exited and the generator is safe to use again. 
this patch avoid an unfortunate 'generator already executing' condition

### CODE REVIEW

**Comment by guy4261** [comment]
I submitted this same issue and got my pull request stalled. I pulled your file onto a fresh installation of keras to get my fit_generator working again, worked like a charm! :+1:

**Comment by fchollet** [comment]
This use of threading seems to cause some threads to never terminate on Travis.

**Comment by osh** [comment]
I think the travis-ci fail issue is because this hasn't been tested with pickle-safe / process mode rather than threads, I'll look into that mode shortly when I get a chance -

**Comment by giorgiop** [comment]
Any news on this?

**Comment by fchollet** [comment]
Closing outdated PR. If you still care about the content of the PR, please submit a new PR to `master`, updated for the Keras 2.0 API.

**Pull request closed without merging**
