### PR TITLE
Tensorflow bABi

### PR DESCRIPTION
**Pull request by EderSantana**
Add tensordot to backend
Allow "dot" and "cos" Merge with Tensorflow
Makes bAbI example work with Tensorflow

### CODE REVIEW

**Comment by NasenSpray** [comment]
It should be called `K.batched_dot`, imo. `tf.batch_matmul` is simply no tensordot.

**Comment by fchollet** [comment]
I see you have added a Numpy backend, but a large fraction of it is implemented in TensorFlow. Was that intentional?

The reason we don't have a Numpy backend is that Numpy is not natively a symbolic computation framework and thus isn't a good fit for a backend. You would have to rely on other abstraction layers (autograd), not to mention custom implementations of key ops (convolution, maxpooling).

> It should be called K.batched_dot, imo. tf.batch_matmul is simply no tensordot.

**Comment by EderSantana** [comment]
> I see you have added a Numpy backend, but a large fraction of it is implemented in TensorFlow. Was that intentional?

lol! how did that happend??? Sorry. The Numpy backend is something I'm developing to as a debugging tool and part of a Keras for production idea. Thanks for letting me know your opinions though. 

I'll start a new PR.

**Comment by EderSantana** [comment]
> It should be called K.batched_dot, imo. tf.batch_matmul is simply no tensordot.

Next PR will come with batch_dot instead

**Comment by EderSantana** [comment]
replaced by #2055

**Pull request closed without merging**
