### PR TITLE
Added squeezenet-residual architecture into applications folder

### PR DESCRIPTION
**Pull request by kirk86**
Hi, I've also included the squeezenet-residual architecture into the keras applications folder. At the moment no weights are included. If someone has the compute power maybe can help on this issue. Or maybe someone has already pre-computed them.

### CODE REVIEW

**Comment by reynoldscem** [comment]
It looks as if the tests have failed due to a bug fetching a remote pickle from S3.

If you close and reopen this PR it should hopefully run Travis again & pass.

**Comment by kirk86** [comment]
@reynoldscem thanks...

**Comment by kirk86** [comment]
Hey guys I'm adding some links to download the weights from:
[squeezenet_weights_tf_dim_ordering_tf_kernels.h5](http://www.megafileupload.com/czfS/squeezenet_weights_tf_dim_ordering_tf_kernels.h5)
[squeezenet_weights_th_dim_ordering_th_kernels.h5](http://www.megafileupload.com/czfT/squeezenet_weights_th_dim_ordering_th_kernels.h5)

Notice: In case that you get an error loading them into the model. You should investigate the `fire_module` function in the `merge` function of keras and remove the residual connection, which in that case is the tensor `x`

**Comment by fchollet** [comment]
Closing outdated PR. If you still care about the content of the PR, please submit a new PR to `master`, updated for the Keras 2.0 API.

**Pull request closed without merging**
