### PR TITLE
Loading models with shared layers

### PR DESCRIPTION
**Pull request by javiercorrea**
Fixed a problem that occurs when trying to load a model with shared layers that are connected with themselves in the calling order.

I've also added a test for this case.

This fixes Bug #6481

### CODE REVIEW

**Comment by baregawi** [comment]
FYI, when I run your code, it no longer gives me the ValueError but I get the following index error:

```
/home/baregawi/holocene/lib_py/ai_matcher/models/pretrain.pyc in load_model(model_json, model_h5)
    100         with open(model_json, 'r') as f:
    101             model_config = json.load(f)
--> 102         model = Model.from_config(model_config)
    103         model.load_weights(model_h5)
    104 

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in from_config(cls, config, custom_objects)
   2492                     layer_name, call_number = call
   2493                     layer_data = layer_data_by_name[layer_name]
-> 2494                     process_single_call(layer_data, call_number)
   2495                     built_calls.add(call)
   2496                     to_remove.append(call)

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in process_single_call(layer_data, call_number)
   2466                     raise ValueError('Missing layer: ' + inbound_layer_name)
   2467                 inbound_layer = created_layers[inbound_layer_name]
-> 2468                 inbound_node = inbound_layer.inbound_nodes[inbound_node_index]
   2469                 input_tensors.append(inbound_node.output_tensors[inbound_tensor_index])
   2470             # Call layer on its inputs, thus creating the node

IndexError: list index out of range
```

**Comment by fchollet** [comment]
Sorry, I've completely missed this PR for some reason. I actually implemented a similar fix today, please check it out: https://github.com/fchollet/keras/commit/395a2edfd7741b5cdce7997bf8d4018d0e4b10d9

**Comment by fchollet** [comment]
(presumably the reason why I missed it is because I initially skipped it to due to failing tests, then forgot to check back on it)

**Comment by javiercorrea** [comment]
The problem still persists with some models, see https://github.com/fchollet/keras/issues/6481

**Pull request closed without merging**
