### PR TITLE
remove subgraph compilation/execution step in theano backend conv2d

### PR DESCRIPTION
**Pull request by Philip-Bachman**
This change fixes a problem that occurs when the "kernel" used in a convolution is the result of a symbolic operation elsewhere in the graph. In this case, the `kernel.eval()` step in the current master branch will fail, as the inputs required for compiling and executing the eval are neither available nor provided when calling eval.

I fixed this by changing the code to keep all computations symbolic.

The existing code works for most people because the input kernel is typically a TensorSharedVariable, for which `var.eval()` can just call `var.get_value()`, without requiring any additional inputs.

I've tested that the proposed change works for both odd-width and even-width kernels.

### CODE REVIEW

**Comment by fchollet** [comment]
Is there any performance impact?

**Comment by Philip-Bachman** [comment]
It does require evaluating the `kernel.shape` at run time. When the node is executed this must already be available, as the kernel must be available (non-symbolically) at that time. Accessing this attribute, evaluating the `%` operator, and performing the `ifelse` switch will have non-zero cost. I haven't done any profiling to see what this cost might be, though it should be small relative to computing the actual convolutions.

One place I could see this maybe causing a noticeable slow-down is through its effects on Theano's graph optimizations. I don't know how well these play together with if-else branching.

I'm not sure how else to compute something conditioned on the shape of a fully-symbolic tensor.

**Comment by Philip-Bachman** [comment]
If you think this use case is insufficiently common to merit changes to the core implementation of Keras, I'll just close the pull request.

**Comment by fchollet** [comment]
What's your use case exactly? Are you using backend functions outside of layers?

**Comment by Philip-Bachman** [comment]
I'm using a custom layer in which the convolution kernel is selected for each input batch by slicing the underlying parameter matrix. E.g., in a large convolutional GRU, if we want to drop out half the state dimensions for the full feedforward pass, we (ideally) could accelerate computation significantly by only performing computation for the relevant dimensions, rather than computing a full state update and masking.

**Pull request closed without merging**
