### PR TITLE
[Patch] Fixing issue with dot output shape 

### PR DESCRIPTION
**Pull request by dbonadiman**
This is a patch pull request to fix the issue with the dot output shape. 

From https://github.com/fchollet/keras/issues/936 i opted for this fix.

### CODE REVIEW

**Comment by fchollet** [comment]
Your proposed solution at the time was:

> So a simple solution is an if to deal with that simple case (like doing the dim shuffle when: no axis are presented or all the axis are presented as dot_axes)

It is unclear to me how this patch achieves this. Could you clarify? Keep in mind how `output_shape` is currently computed (via numpy tensordot).

**Comment by dbonadiman** [comment]
I thought about the simple implementation but it may be more problematic then this.
In the simple case the numpy tensor dot outputs `(1)` that is concatenated with the batch size so we have 

`(None, 1)` as output shape.

When the output is computed however the output is `(batch_size, )` with the reshape in this case we obtain  the expected output as `(batch_size, 1)`.

In all the other cases the reshape function serves as identity and do not affect the output.

I tried with a simpler ` if output_shape[1] == 1` but it opens more cases where we want to operate on more dimensions so i thought to this solution to cover the simple case.

**Comment by fchollet** [comment]
> In the simple case the numpy tensor dot outputs (1)

No, in many cases it will output `()`. I believe that is the issue here. `(None,) + () == (None,)`.

**Comment by dbonadiman** [comment]
I agree but our current implementation already deal with this problem

```python
            if len(tensordot_output.shape) == 0:
                shape = (1,)
            else:
                shape = tensordot_output.shape
            return (shape1[0],) + shape
```

Quoting from the code.

**Comment by fchollet** [comment]
Ok, seems reasonable to me.

**Pull request merged**
