### PR TITLE
Tokenizer test

### PR DESCRIPTION
**Pull request by 4d55397500**
Improver tokenizer test by checking outputs are unchanged under additional tokens in text.

### CODE REVIEW

**Comment by fchollet** [comment]
It isn't clear to me what you are testing, from reading the code. It should be clear to any reader of the code, so please add necessary code comments.

**Comment by 4d55397500** [comment]
Comments added. I'm checking that the generated representations are unchanged under text malformations that include vocabulary not in the original text used for fitting.

**Comment by fchollet** [comment]
Why though? Given the algorithm used, there should be no presumption of bug at this level...

**Comment by 4d55397500** [comment]
It's certainly not necessary- up to you. I added the test since I use the keras tokenizer extensively and find myself testing this functionality (extraneous vocabulary not affecting the output) often.

**Comment by fchollet** [comment]
Got it, thanks for the explanation. Overall, I don't think it is necessary here.

**Pull request closed without merging**
