### PR TITLE
Support return_state parameter in ConvRecurrent2D

### PR DESCRIPTION
**Pull request by ericwu09**
Added support for the return_state=True parameter in the ConvRecurrent2D abstract class.

### CODE REVIEW

**Comment by fchollet** [comment]
Please fix PEP8 error: https://travis-ci.org/fchollet/keras/jobs/256547031

**Comment by fchollet** [comment]
Additionally, this change should have a unit test.

**Comment by fchollet** [comment]
Check out the tests: https://travis-ci.org/fchollet/keras/builds/256959711?utm_source=github_status&utm_medium=notification

**Comment by ericwu09** [comment]
Thanks, @fchollet. The unit test is in and passes the checks now.

**Pull request merged**
