### PR TITLE
Resolves issue #4005

### PR DESCRIPTION
**Pull request by icyblade**
Feature requested in issue #4005 is solved.

### CODE REVIEW

**Comment by jocicmarko** [comment]
This feature only makes sense if ```verbose=2``` is used, but if this PR is going to be accepted, I suggest changing at least considering changing the parameter name ```step``` to ```verbose_step```.

**Comment by fchollet** [comment]
I think this is too specialized to become part of core Keras. If `verbose=1` doesn't work for you, then you should use `verbose=2` (for instance). Alternatively, you could also create your own logger callback.

**Comment by icyblade** [comment]
Seems to be a good choice to create a new callback.
Thanks for the reply.

**Comment by icyblade** [comment]
@fchollet For your information, xgboost [provides](http://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.train) such feature by specifying `verbose_eval` parameter.

**Pull request closed without merging**
