### PR TITLE
Fixed transpose/reshape to th/tf dim_ordering

### PR DESCRIPTION
**Pull request by asmith26**
As per comment on [Line 153](https://github.com/asmith26/keras/blob/1a5deb18d38681e1bf8f90e87b675384ce806635/keras/preprocessing/image.py#L153), converting a PIL image to a numpy array creates an image with dim_ordering `(H, W, C)` (if RGB - otherwise `(H, W)` if grayscale).

Thus to create Theano and TensorFlow dim_ordering (as per the [main image doc](https://keras.io/preprocessing/image/), i.e. `(C, W, H)` and `(W, H, C)`, we need to transpose/expand `x` as per this pull request.

### CODE REVIEW

**Comment by fchollet** [comment]
I am worried that this would create issues in any user code that relies on the current implementation. For instance, within the Keras codebase alone, this would affect several example scripts (e.g. style transfer).

**Comment by asmith26** [comment]
It is a risk - I came across the error having taken small crops within images loaded via `load_img()` and `img_to_array()`. Saving them back to disk (via `array_to_img()`) showed incorrect crops.

Running `grep` on all files within the most recent pull of the keras repo:
```
$ grep -r "img_to_array" *
docs/templates/applications.md:x = image.img_to_array(img)
docs/templates/applications.md:x = image.img_to_array(img)
docs/templates/applications.md:x = image.img_to_array(img)
examples/neural_doodle.py:from keras.preprocessing.image import load_img, img_to_array
examples/neural_doodle.py:    img = img_to_array(img)
examples/neural_doodle.py:    target_mask_img = img_to_array(target_mask_img)
examples/neural_doodle.py:    style_mask_img = img_to_array(style_mask_img)
examples/neural_style_transfer.py:from keras.preprocessing.image import load_img, img_to_array
examples/neural_style_transfer.py:    img = img_to_array(img)
keras/preprocessing/image.py:def img_to_array(img, dim_ordering='default'):
keras/preprocessing/image.py:            x = img_to_array(img, dim_ordering=self.dim_ordering)
tests/keras/preprocessing/test_image.py:                img_list.append(img_to_array(im)[None, ...])

$ grep -r "array_to_img" *
Binary file keras/preprocessing/image.pyc matches
keras/preprocessing/image.py:def array_to_img(x, dim_ordering='default', scale=True):
keras/preprocessing/image.py:                img = array_to_img(batch_x[i], self.dim_ordering, scale=True)
keras/preprocessing/image.py:                img = array_to_img(batch_x[i], self.dim_ordering, scale=True)
```

We could go through each such file and try to ensure this change doesn't break anything (of course any independent projects could break) - alternatively, should this fix be applied within a future (major) release?

**Comment by fchollet** [comment]
I suggest that we modify all places that are affected in the Keras codebase and examples (as part of the present PR), and merge the PR.

**Comment by fchollet** [comment]
I've resolved these issues and added a unit test for it.

**Pull request closed without merging**
