### PR TITLE
Add documentation about metrics functions

### PR DESCRIPTION
**Pull request by ramananbalakrishnan**
I have added a section about the metrics functions (using the [objectives](https://github.com/fchollet/keras/blob/master/docs/templates/objectives.md) documentation as a template).

This should help answer questions (like issue #2607) about the `metrics` parameter in `model.compile`

### CODE REVIEW

**Comment by fchollet** [comment]
The documentation for metrics should be generated from the docstrings of the functions in `metrics.py` (and if docstrings are missing they should be added). This is necessary because some metrics have complicated docstrings.

**Comment by ramananbalakrishnan** [comment]
Got it, I understand that the auto-generation is handled using [`docs/autogen.py`](https://github.com/fchollet/keras/blob/master/docs/autogen.py) and the docstrings directly from the files.

Given that currently, [`objectives.py`](https://github.com/fchollet/keras/blob/master/keras/objectives.py) and [`metrics.py`](https://github.com/fchollet/keras/blob/master/keras/metrics.py) are almost identical, I just followed [`docs/templates/objectives.md`](https://github.com/fchollet/keras/blob/master/docs/templates/objectives.md) (which doesn't have any docstring information) as a template for [`docs/templates/metrics.md`](https://github.com/ramananbalakrishnan/keras/blob/ee9d72/docs/templates/metrics.md).

I'll go ahead and document all the functions in `metrics.py` and then update this pull request to generate the documentation.

Similar updates for the `objectives.py` documentation might be better done separately.

**Comment by ramananbalakrishnan** [comment]
@fchollet , updated the pull-request based on your comments

- [x] Auto-generate documentation from docstrings
- [x] Add missing docstring information where required in `metrics.py`

**Comment by fchollet** [comment]
LGTM, thanks!

**Pull request merged**
