### PR TITLE
acgan: use default TF layout i.e. 'channels_first'

### PR DESCRIPTION
**Pull request by ozabluda**
With TF 1.3 cudnn 6, this reduces time per epoch from 112 sec to 97 sec on Titan X Maxwell. This and `mnist_swwae.py` are the only examples which use `K.set_image_data_format()`

### CODE REVIEW

**Comment by fchollet** [comment]
I think you are missing a few references, e.g. lines 51, 166...

**Comment by ozabluda** [comment]
Fixed. Those 2 seems to be the only ones.

**Comment by fchollet** [comment]
It appears that this PR broke the example since it did not update MNIST data loading to reshape the data to channels_last. I fixed it.

Please do not open PRs to example scripts before having run the scripts in full (and do not open PRs to other functionality before having run the corresponding tests).

**Comment by ozabluda** [comment]
Sorry about that. I was about to fix it myself, as I saw your fix. I pulled a small portion of a much larger diff, and missed those 2 lines.

**Comment by ozabluda** [comment]
@fchollet, on the subject of breakage (sorry, again), acgan example is broken since at least 2.0.4 (produces all-black images, Issue https://github.com/fchollet/keras/issues/8373). I fixed it in currently not merged PR https://github.com/fchollet/keras/pull/8383#issuecomment-342237169, which produces better (I think) images than the original example. I am working on a (hopefully) even better fix, but it's on top of   https://github.com/fchollet/keras/pull/8383. 

P.S. cifar10_cnn example is also broken since spring of 2017. Issue https://github.com/fchollet/keras/issues/5239#issuecomment-333193776

**Pull request merged**
