### PR TITLE
Use the pytest tmpdir fixture

### LINKED ISSUE #6881: Race in test_callbacks.py due to shared temporary directories
Several of the tests in tests/keras/test_callbacks.py use the following pattern:
```python
filepath = './logs'
<function that writes to the filepath>
assert os.path.exists(filepath)
shutil.rmtree(filepath)
```
Since they all use the same filepath, when running the tests with the parallel test driver there is always the possibility that one function will delete the directory in between the one writing it and the other checking its existence. It would make more sense to use the pytest builtin `tmpdir` fixture.

https://docs.pytest.org/en/latest/builtin.html#builtin-fixtures-function-arguments

### PR DESCRIPTION
**Pull request by frexvahi**
Fixes #6881

### CODE REVIEW

**Comment by frexvahi** [comment]
For test_data_utils, as an alternative that wouldn't involve large whitespace-only changes, I could write a decorator that runs the function in a temporary directory

**Comment by fchollet** [comment]
Will this work when running the test suite on Windows?

**Comment by frexvahi** [comment]
I haven't tried on Windows, but if pytest is cross-platform then the tmpdir fixture should also work. However, according to the documentation for NamedTemporaryFile the file cannot be re-opened on Windows so those parts will have to be changed.

**Comment by frexvahi** [comment]
OK, I've left the code using `mkstemp` as it is, and changed the tests with hardcoded filenames to run in unique temporary directories.

**Comment by fchollet** [comment]
Please fix the PEP8 issue: https://travis-ci.org/fchollet/keras/jobs/241093631

**Comment by fchollet** [comment]
LGTM, thanks

**Pull request merged**
