### PR TITLE
Generator should use Process Lock when pickle safe instead of Threading Lock

### PR DESCRIPTION
**Pull request by Leoyzen**
When pickle safe is True, using Threading Lock in generator causes problem when generate random index of inputs.

Two way to avoid this:

1. if pickle_safe is True, check generator whether has 'lock' attribute and replace it with multiprocess version
2. always use multiprocess.Lock, this is less efficient of performance

### CODE REVIEW

**Comment by fchollet** [comment]
Could someone please review this PR? @Dref360 maybe this is your domain?

**Comment by Dref360** [comment]
Will look into it tonight. 

I guess the `lock` attribute come from something like [that](https://stackoverflow.com/questions/1131430/are-generators-threadsafe) , is that right?

**Comment by Leoyzen** [comment]
@Dref360 
Indeed,  [Keras Iterotor](https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py#L696)
used the lock to generator thread/process safe index array, which caused the problem that the lock not longer safe in multi process mode.

**Comment by Dref360** [comment]
Great! Maybe just add a comment around this block to specify where the lock comes from. (If Iterator get deprecated and/or Iterator.lock get renamed, it will cause a lot of problems and nobody will know why.)

Otherwise, LGTM.

**Comment by Leoyzen** [comment]
@Dref360 Done, plz check

**Pull request merged**
