### PR TITLE
change ImageDataGenerator print output destination

### PR DESCRIPTION
**Pull request by YusukeSuzuki**
- change ImageDataGenerator output from stdout to stderr

### CODE REVIEW

**Comment by fchollet** [comment]
Why?

**Comment by YusukeSuzuki** [comment]
In situation where I write `find` like program with keras and do `./keras_find_cat_image image_dir | xargs -I {} mv image_dir/{} dst_dir`,  `Found %d images belonging to %d classes.` is only noise for application.

stdout contents should be owned application programmers, not framework programmers. 
All output which is not assumed by application programmers or application users should be written into stderr.

**Comment by fchollet** [comment]
In the TF codebase, which I sometimes use as reference, a cursory search reveals that functions that need to provide feedback to the user do so via `print()` (plenty of occurrences of this pattern). `stderr.write` is never used. So we'll stick to it.

**Comment by YusukeSuzuki** [comment]
I followed keras/backend/__init__.py style.
But OK, I will recreate PR with print() style.

**Pull request closed without merging**
