### PR TITLE
Implement Parametric Exponential Linear Unit activation layer

### PR DESCRIPTION
**Pull request by rilut**
Hi,

This is my first PR and still work in progress. I'm trying to implement [PELU](https://arxiv.org/abs/1605.09332) activation layer.

Will Keras need it?
Would anyone from Keras team be kind to assist me or comment on this?

Thanks!

### CODE REVIEW

**Comment by rilut** [comment]
Breaks on tensorflow backend

**Comment by rilut** [comment]
Breaks on tensorflow backend. I guess it's because of `K.switch`?

**Comment by rilut** [comment]
Also I'm not sure about the correct `alpha_init` and `beta_init`

**Comment by xingdi-eric-yuan** [comment]
try this:
```python
    def call(self, x, mask=None):
        pos = self.alphas / self.betas * x
        pos *= K.cast(K.greater_than(x, 0), K.floatx())
        neg = self.alphas * (K.exp(x / self.betas) - 1)
        neg *= K.cast(K.less_than(x, 0), K.floatx())
        return pos + neg
```
and you need to add `greater_than` and `less_than` into both theano and tf backend:
```python
# theano backend
def greater_than(x, y):
    return T.gt(x, y)

def less_than(x, y):
    return T.lt(x, y)
```
```python
# tf backend
def greater_than(x, y):
    return tf.greater(x, y)

def less_than(x, y):
    return tf.less(x, y)
```

**Comment by asmith26** [comment]
Instead of creating new `greater_than`, `less_than` functions in the backend, I recommend using the `K.relu(x)` for x>=0 and `(x - abs(x))` for x<0 techniques the other advanced activations have used; e.g.:

```python
def call(self, x, mask=None):
    pos = K.relu(x)
    neg = (x - abs(x)) * 0.5
    return (self.alphas / self.betas) * pos + self.alphas * (K.exp(neg / self.betas) - 1.)
```

Regarding what `alpha_init` and `beta_init` to use, looking at [the graphs on page 16 of the paper](https://arxiv.org/pdf/1605.09332v2.pdf#page=16), at epoch 1 it appears both `alpha_init=1.0` and `alpha_init / beta_init = 1.0` (so `beta_init=0`).

**Comment by rilut** [comment]
@asmith26 Thanks! Also wouldn't that make `beta_init` be 1.0?

**Comment by asmith26** [comment]
No problem, and yep it should be 1.0 (sorry for the typo - corrected above now, thanks).

**Pull request closed without merging**
