### PR TITLE
Integrate with cntk 2.3.1

### PR DESCRIPTION
**Pull request by souptc**
1. Update with cntk 2.3.1
2. Fix the dropout in recurrent layer.

### CODE REVIEW

**Comment by souptc** [comment]
@fchollet , the current generate dropout mask code in recurrent cell require the backend to support shape as a tensor, which is not support in cntk and also not in our shot-time plan. So i update it a little bit with the ones_like method. The recurrent cell still self-contain after this update. Please let me know if you have any concern for that.

**Comment by fchollet** [comment]
I think the method consisting of getting the shape and instantiating a new ones tensor from it would be a lot cheaper than reshaping a potentially large tensor then instantiating a ones tensor from it. Getting the shape is free, reshaping a large tensor will involve a memory copy and somme compute.

Do you see any timing difference with TF with large inputs?

**Comment by souptc** [comment]
Yes, I do agree current with getting shape and instantiating a new ones tensor will be much cheaper, and I do hope I could do this for cntk, but it turn out not that easy... did a simple experiment, with batch size and dimension as 1000, current code average cost is around 0.004s while my code will cost around 0.009s. 
How about this: for TF we still following current way to generate mask, while for cntk we keep the old way with ones_like?

**Comment by fchollet** [comment]
Ok, we can have a backend check and do one or the other.

**Pull request merged**
