### PR TITLE
add support for larger dimensional tensors and SharedDense Layer

### PR DESCRIPTION
**Pull request by charlesollion**
Outputs from RNNs have a 3 dimensional shape: 
(nb_sample, time, output_dim)

- Added support in predict_proba and predict_classes for a 3 dimensional output.
- Added a SharedDense Layer ( a dense layer applied to each output of the time dimension ).

I wanted to do a more general Layer that applies the next Layer to each element of the time dimension, but couldn't figure out how to without destroying the architecture.

### CODE REVIEW

**Comment by fchollet** [comment]
I'd merge the shape generalization change if it were in a separate PR. Can you please submit separate PRs for each change?

Regarding the SharedDense layer, I see a few issues: 
- the name is ambiguous, since "shared" is a reserved keyword in Theano development. 
- ideally, we would the usage of the layer to be obvious from its name. Maybe TimeSharedDense would be better? Any ideas?
- this layer takes a 3D input but its input attribute is a matrix. That's a bug (will crash if the layer is goes first in a model). 
- I think the idea of a meta-layer that takes as parameter a layer and applies it to every timestep is interesting and should be given more thought. What is your issue with the architecture?

**Comment by charlesollion** [comment]
Ok good points. I'll send you a PR for the first change.

As for the Layer, I tried to make a meta layer but I can't easily access the function for the inner layer to pass it to scan. I believe it would involve some minor changes in any layer, but maybe there are better ways.

Would you like me to do a PR with the TimeSharedDense (or TimeDistributedDense ?) & corrected issues or rather think of a meta layer solution before ?

Cheers

**Comment by fchollet** [comment]
I see I had forgotten to reply to this, sorry about that! 

I think we should definitely go with a TimeDistributedDense layer. We already have a time_distributed_softmax activation function, so we're starting to see a pattern : )

**Comment by charlesollion** [comment]
Ok!
I've sent you another pull request so that you can close this one.
Best,
Charles

**Pull request closed without merging**
