### PR TITLE
bAbI: Doubling the FB LSTM baseline :)

### PR DESCRIPTION
**Pull request by farizrahman4u**
A simple hack.

### CODE REVIEW

**Comment by farizrahman4u** [comment]
I have only run it on the first 2 challenges.

**Comment by fchollet** [comment]
Ok, cool.

**Comment by mkaze** [comment]
I can also verify that the claimed results are not reproducible as @gidonro , @masabdi and @stefanm91 suggested. Here are [the result of training the current model on QA1 task](https://gist.github.com/mkaze/2cef590a452a0b3781018eba679cf927#file-babi-qa1-txt) (which reaches ~50% test accuracy, and not 100% as claimed) and [the result on QA2 task](https://gist.github.com/mkaze/2cef590a452a0b3781018eba679cf927#file-babi-qa2-txt) (which reaches ~30% test accuracy, and not 50% as claimed). @farizrahman4u Could you please clarify how did you obtain your claimed results?

Further, after this PR, the two variables `SENT_HIDDEN_SIZE` and `QUERY_HIDDEN_SIZE` are never used in the code. @fchollet @farizrahman4u I am willing to fix this example, however I don't know exactly how should I go about it?! e.g. reverting back to previous version, or keeping the changes and just run all the tasks and modify/correct the reported accuracy numbers as needed (they have not been updated for QA3-20 after the modifications made in this PR)?

**Comment by farizrahman4u** [comment]
@mkaze This PR is 2+ years old.. I don't remember the details but I am sure I messed up somewhere. Please go ahead and fix whatever is broken :)

**Pull request merged**
