### PR TITLE
Parameter names

### PR DESCRIPTION
**Pull request by rodrigob**
Address issue #635, now each layer can have a name, or a default one will be assigned.

```
python3.4 check_parameter_names.py 

Testing default parameter names (for sequential model)
Layer1_Dense_W
Layer1_Dense_b
Layer3_Convolution2D_W
Layer3_Convolution2D_b
Layer5_Dense_W
Layer5_Dense_b

Testing default parameter names (for graph model)
dense1_W
dense1_b
dense2_W
dense2_b
dense3_W
dense3_b

Testing when all nodes are named
first_seq_dense_W
first_seq_dense_b
Layer2_Graph_dense1_W
Layer2_Graph_dense1_b
Layer2_Graph_dense2_W
Layer2_Graph_dense2_b
Layer2_Graph_dense3_W
Layer2_Graph_dense3_b
last_seq_dense_W
last_seq_dense_b

Testing when some nodes have names, and others do not
first_seq_sense_W
first_seq_sense_b
Layer2_Dense_W
Layer2_Dense_b
Layer3_Convolution2D_W
Layer3_Convolution2D_b
Layer4_Graph_dense1_W
Layer4_Graph_dense1_b
Layer4_Graph_dense2_W
Layer4_Graph_dense2_b
Layer4_Graph_dense3_W
Layer4_Graph_dense3_b
last_seq_dense_W
last_seq_dense_b
```

up to code review, this pull request seems good to merge on my side.

### CODE REVIEW

**Comment by rodrigob** [comment]
Up to issue related to PR #650 all auto unit tests pass.

**Comment by fchollet** [comment]
I'm very interested in adding this feature, and as I feel this is a significant change I will take a little bit to review this PR. I hope you don't mind.

**Comment by rodrigob** [comment]
no problem !

**Comment by fchollet** [comment]
Just a heads-up: I think this is a great PR, but we are going to post-pone adding this feature a bit, because variable naming is going to interact significantly with our upcoming goal of abstracting the Keras backend away from Theano.

Specifically, I don't think initialization functions should handle the naming. Instead we are probably going to have a `Variable` constructor that could take either a numpy value (making it similar to `floatX`) or a `init` function and an `input_shape`. This constructor would be handling the naming. Under the hood it would be calling Theano/etc.

**Comment by raingo** [comment]
What's the recommend way to inspect weights without this PR? I am using Sequential() and Recurrent Net. Because the output is wield, I would like to check what the learned weights for specific layers.

Thanks!

**Pull request closed without merging**
