### PR TITLE
Allow dynamic shape for repeat_elements

### LINKED ISSUE #7410: Variable-length Upsampling
I want to add an `UpSampling1D` but it seems it only accepts fixed-length input. Is there any chance to get it to work for variable-length input? Other layers work perfectly for my model.

Part of my model:

```
inp = Input(shape=(None,161),name="in")
zeropadded = ZeroPadding1D(padding=1)(inp)
upsampled = UpSampling1D(length=2)(zeropadded)
```

I get the following error:

```
ValueError: Axis 1 of input tensor should have a defined dimension, but is None. Full tensor shape: (None, None, 161). Typically you need to pass a fully-defined `input_shape` argument to your first layer.
```

### PR DESCRIPTION
**Pull request by milani**
Fixes #7410 
Correctly handle dynamic shape to be passed to `repeat_elements` in tensorflow backend. Before this commit, it raised error if the axis to be repeated was None.

### CODE REVIEW

**Comment by fchollet** [comment]
- Change should be tested (in `backend_tests`)
- Unit tests are failing

**Comment by milani** [comment]
@fchollet I fixed the errors and changed the tests. Now they pass. I'm just wondering what kind of new test should I add?

**Comment by milani** [comment]
This implementation needs double the time of the old one. I'm not sure if there is another way to do it with better performance.

**Comment by fchollet** [comment]
> This implementation needs double the time of the old one to run. I'm not sure if there is another way to do it with better performance.

Consider using the faster implementation when possible (static shape) and the slower one when there is no other choice.

**Comment by milani** [comment]
@fchollet Look at this simple benchmark: https://gist.github.com/milani/68c17ffe35f8c84c4cd362d517dbceb0

Running on GPU, both implementations perform the same. But on CPU, the story is different. So should I branch to cover the CPU case or is this PR good enough?

**Comment by fchollet** [comment]
Should be simple:

- if static axis, old implementation
- else, new implementation

**Comment by milani** [comment]
Done

**Pull request merged**
