### PR TITLE
LambdaCallback

### PR DESCRIPTION
**Pull request by carlthome**
# Proposal
In keeping with the style of having LambdaLayer it could be nice to have a LambdaCallback as well for being able to create inline callbacks without having to breakout into a Class block.

E.g. something like:

```python
my_callback = LambdaCallback(on_epoch_end=lambda epoch, logs: print(logs))
model.fit(..., callbacks=[my_callback])
```

Thoughts?

### CODE REVIEW

**Comment by carlthome** [comment]
@fchollet, thoughts?

**Comment by fchollet** [comment]
Any third-party opinions on this feature?

**Comment by jocicmarko** [comment]
+1 for this feature. Although I like the reusability when defining your own callback (via Callback class), this should make it easier to define trivial callbacks (for one-time use).
This PR is also well-documented.

**Comment by jfsantos** [comment]
I agree with @jocicmarko. This is a really handy feature.

**Comment by carlthome** [comment]
@fchollet, reconsidered?

**Comment by fchollet** [comment]
LGTM

**Pull request merged**
