### PR TITLE
Add get_initial_state method to Recurrent

### LINKED ISSUE #1181: add get_initial_states to Recurrent
GRU, LSTM and other conventional RNNs have well defined initial state sizes that can be calculated from output_dim, but NTMs, convolutional rnn (I'm working on that) don't. Instead of hard coding the initial states inside `get_output` I propose an extra method called get_initial_states.

### PR DESCRIPTION
**Pull request by EderSantana**
With this method, I believe no other recurrent method will need to overwrite
get_output.

Fix #1181

### CODE REVIEW

**Comment by EderSantana** [comment]
@olegsinyavskiy how do I run tests on my local machine to reproduce what travis expects? I tried py.test and it didn't work:
```py.test: error: unrecognized arguments: -n --cov-report term-missing --cov=keras```

**Comment by EderSantana** [comment]
btw, this get_initial_states method also helps to debug recurrent methods better.

**Comment by olegsinyavskiy** [comment]
I think you're missing pytest-xdist and coverage. Please install them like travis yaml does:
pip install pytest-cov python-coveralls pytest-xdist

**Comment by EderSantana** [comment]
@olegsinyavskiy tkx for the quick reply

**Comment by fchollet** [comment]
I think the steps required to run tests locally are non-obvious at this point, we need to compile a contributor's guide with this type of information.

**Pull request merged**
