### PR TITLE
Shared layer enhancements

### PR DESCRIPTION
**Pull request by farizrahman4u**
* Allow shared layers to be first layers in models
* Enable shared `Embedding` layer (impossible before, because of `int32` vs `floatX` issues)

### CODE REVIEW

**Comment by farizrahman4u** [comment]
ping @fchollet

**Comment by fchollet** [comment]
Shouldn't we let the type of the input be configurable by the user, instead of hard-coding it into `if Embedding...`?

**Comment by farizrahman4u** [comment]
Sorry, I didn't get you. To clarify, any layer can be added as a shared layer.. but  there was a bug when   adding a shared Embedding  layer. So there is  condition `if embedding then  do some stuff `..

**Comment by farizrahman4u** [comment]
@fchollet I have made a small change..  now the input type is inferred from the layer itself.

**Comment by farizrahman4u** [comment]
Having a tough time fixing tensorflow issues. Slicing isn't as easy as theano. `X[0][0]` and `X[0, 0]` do not work. Can not reshape if there are unknown dims in the reshape tensor. Crappy. To make things worse, i am on Windows and do not have TF installed, so have to rely on Travis to test my code :(

**Comment by pasky** [comment]
Is this PR still relevant? I'm [using Embedding as the first shared node](https://github.com/brmson/dataset-sts/blob/master/pysts/kerasts/blocks.py#L17) without any trouble.

**Comment by fchollet** [comment]
Closing outdated PRs following the release of Keras 1.0.

**Pull request closed without merging**
