### PR TITLE
Early stopping in fit with KeyboardInterrupt

### PR DESCRIPTION
**Pull request by lukedeo**
Allow users to stop the `Sequential.fit(...)` method with a `KeyboardInterrupt` and still return the training history.

### CODE REVIEW

**Comment by lukedeo** [comment]
Good for users prototyping in iPython, etc.

**Comment by fchollet** [comment]
I see how this can be valuable, but I think try / except should be reserved for exceptions (which should be exceptional), not regular control flow. Try / excepting the entire main loop seems a bit heavy-handed. 

Have you looked into using an interrupt handler to achieve the same result? https://docs.python.org/2/library/signal.html

**Comment by lukedeo** [comment]
Hmmm, I've seen this used a bunch, but I can understand that it's not the most semantically consistent trick. 

How would you feel about incorporating a class like [this](https://gist.github.com/lukedeo/4b872c7a2d5bd1c5d951) into `utils/generic_utils.py`?

Then, we can do something like:

```python
with TrainingHandler() as training_loop:
    for epoch in range(nb_epoch):
        ...
        if training_loop.interrupted:
            print('blah')
            break
```

**Comment by faroit** [comment]
@lukedeo @fchollet any particular reason why this was closed out? I think this would be highly useful and I don't see that this could be implemented using keras callbacks so it would need to go into the main training loop.

**Comment by faroit** [comment]
is there maybe a way to implement this in a custom generator fed into fit_generator?

**Pull request closed without merging**
