### PR TITLE
Return model output during training

### PR DESCRIPTION
**Pull request by wouterbulten**
This pull request is an implementation of #8468.

**Design document:**  https://docs.google.com/a/mai-ai.org/document/d/1AIcofCD4jV6iQyoLKpoS7xWgI5ImFfDcar2S9Oz84bc/edit?usp=sharing
**Google groups post**: https://groups.google.com/forum/#!topic/keras-users/6wAE6ZTDApw

This pull request was created to show the feasibility of the feature request and as a proposed implementation. 

**Main changes:**

- Add a new flag `return_model_output` to compile() that signals whether the train and test function should return model output.
- Changed the functions that make the train and test functions to add the model output to the list of outputs.
- Added a parameter to the training_config used in save/load to set the correct value of  `return_model_output`  during compile().

As the API changes are small I'm not sure whether a new test case needs to be added for this feature. If so, please let me know. Suggestions on other ways of handling new the flag are also welcome.

### CODE REVIEW

**Comment by ozabluda** [comment]
The design document is not public.

**Comment by wouterbulten** [comment]
My apologies, it was set to organization-only. It should be public now.

Op do 23 nov. 2017 om 20:50 schreef Oleg Zabluda <notifications@github.com>:

**Comment by fchollet** [comment]
This is too niche (and sufficiently consistent with the rest of the API) to become part of the core API. 

To cover your own use case, I suggest that you set `model.train_function` and `model.test_function` yourself after `compile`. They are settable. This makes your use case work with the existing API.

**Comment by wouterbulten** [comment]
@fchollet Thanks for your response. I do think it is an important feature to get the network output. It is pretty straightforward to implement using TF or Lasagne, so its unfortunate that it would require so much work using Keras. Of course, setting the train functions manually would work but that, in my opinion, conflicts with the simple-to-use model API of Keras.

Do you have any suggestions on how to make this implementation more consistent with the rest of the API? I would happily change the implementation and update the pull request.

I came up with this specific implementation (i.e. adding the flag to the compile function) to not break any backwards compatibility. However, is there any reason why train/test_on_batch couldn't return outputs by default? It seems like a sensible addition when explicitly training or validating on single batches. If the outputs are returned by default then we wouldn't need a flag all together and the change would be more consistent with the rest of the Keras API.

**Comment by tch3141** [comment]
I'm just beginning to use Keras. But I find it baffling that trying to see the output, without doing a unnecessary feed forward is considered 'niche'. Very frustrating.

**Pull request closed without merging**
