### PR TITLE
replace_row backend

### PR DESCRIPTION
**Pull request by udibr**

### CODE REVIEW

**Comment by xingdi-eric-yuan** [comment]
It would be better if the `row` also supports list as type

**Comment by fchollet** [comment]
Unclear to me why this needs to be included in the backend...?

**Comment by udibr** [comment]
you can ask the same about any other backend function.
they help write tensor expressions that works on both theano and tf.

**Comment by fchollet** [comment]
- Pretty much all backend functions are in use in the Keras source code. A new backend function needs a justification.
- `replace_rows` is a non-standard function (i.e. it has no direct equivalent in Numpy, TF or Theano). We try to avoid such functions.

**Comment by xingdi-eric-yuan** [comment]
so that's another `keras-extras` function I guess

**Comment by udibr** [comment]
I disagree. It is a small feature ~8 lines of code. It does dont modify any existing code in any way (unlike forcing LSTMBN into LSTM) and it can be even kept undocumented, either you find it and use it or you dont... so I really dont see what is to loose here

**Pull request closed without merging**
