### PR TITLE
Update latest test changes

### PR DESCRIPTION
**Pull request by tleeuwenburg**
The test coverage is expanded.

Note, there are some failing tests due to changes to the master repo which broke some of the api expectations in already-existing tests. It looks like people aren't running the tests before accepting merge requests or commiting to the repo.

I would suggest taking this request anyway  and then continuing to iterate on the test compliance.

### CODE REVIEW

**Comment by fchollet** [comment]
What's up with the removal of some key doc files?

**Comment by tleeuwenburg** [comment]
That's weird... hang on let me investigate?

**Comment by fchollet** [comment]
Also, rather than merging many commits, could you rebase from master and simply PR the test file you're adding (in one commit)?

**Comment by tleeuwenburg** [comment]
I think the apparent file deletions are thing that have happened in your branch, my directory listing is the same in your repo as my fork. That said, I'll do a rebase anyway so it's clearer what's going on.

**Comment by tleeuwenburg** [comment]
I'll make a new pull request when that's done.

**Pull request closed without merging**
