### PR TITLE
FTML optimizer

### PR DESCRIPTION
**Pull request by szhengac**
An implementation of deep learning optimizer [FTML](http://www.cse.ust.hk/~szhengac/papers/icml17.pdf)

Thanks.

### CODE REVIEW

**Comment by fchollet** [comment]
Hi, thanks for the PR. It seems like a good fit for `keras-contrib` (read CONTRIBUTING.md for more information). I suggest that you direct the PR there instead.

**Comment by the-moliver** [comment]
@szhengac Yes, please do submit to https://github.com/farizrahman4u/keras-contrib
I've already read through your code so I'll be able to merge it quickly.

**Comment by szhengac** [comment]
@the-moliver Hi, I'm new to the github. I'm not sure how to submit it to https://github.com/farizrahman4u/keras-contrib, as I see that optimizer folder in its master branch is empty. Thanks.

**Comment by the-moliver** [comment]
@szhengac To keep things manageable we're putting each new function in its own file. Just add a self contained ftml.py file and update the __init__.py file. You can look in the losses directory for an example of the general format. That make sense? Let me know if you have any other questions.

**Comment by szhengac** [comment]
@the-moliver Thanks, I have submitted it to https://github.com/farizrahman4u/keras-contrib.

**Pull request closed without merging**
