### PR TITLE
added random_shear() to random_transform

### PR DESCRIPTION
**Pull request by tpsatish95**
added the random_shear transformation for images.

### CODE REVIEW

**Comment by fchollet** [comment]
Please:
- add the new parameter to the documentation
- add the parameter to the test in `preprocessing/test_image.py` (which does not verify correctness, btw)
- provide some images of the transforms made by the shear function, to serve as a sanity check

**Comment by tpsatish95** [comment]
some sample images of random _shear,
**before:**
test_image_before
**after:**
`random_shear(imread("test_image.png"),0.5)`
test_image_after1
`random_shear(imread("test_image.png"),-0.2)`
test_image_after2

**Comment by fchollet** [comment]
Thanks. You can squash your 3 commits into one and I will merge.

**Comment by tpsatish95** [comment]
The Travis check fail doesn't seem to be related to any modifications I made.

**Comment by vfdev-5** [comment]
Just wandering why [shear matrix](https://github.com/keras-team/keras/blob/master/keras/preprocessing/image.py#L128) is defined as 
```
[1 -sin(shear) 0]
[0 cos(shear)  0]
[0      0      1]
```
instead of 
```
[1 m 0]
[0 1 0]
[0 0 1]
```
following for example [wiki](https://en.wikipedia.org/wiki/Shear_mapping)

Thanks

**Comment by tpsatish95** [comment]
@vfdev-5 Yes, that is yet another format that can be used to define a shear matrix. 
But, computing shear matrix using the shear angle in radians (counter-clockwise direction), is more intuitive and is the standard in other image processing libraries as well. Refer [scikit-image](https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_geometric.py#L755).

**Pull request merged**
