### PR TITLE
Created Maxout layer

### PR DESCRIPTION
**Pull request by lukedeo**
Let me know what you think -- really simple Maxout implementation using a tensor dot. 

You can modify the MNIST example to be something like

```python
model = Sequential()
model.add(Maxout(784, 128, n_features=20))
model.add(Dropout(0.2))
model.add(Maxout(128, 64, n_features=20))
model.add(Dropout(0.2))
model.add(Dense(64, 10))
model.add(Activation('softmax'))

rms = RMSprop()
model.compile(loss='categorical_crossentropy', optimizer=rms)
```

Here's how it does with all the same parameters. I made some learning curves for accuracy...

maxout-acc
 ...and loss...
maxout-loss

Let me know what you think. If you like it, I can start writing up docs.

### CODE REVIEW

**Comment by fchollet** [comment]
This looks really cool! I think maxout is a much needed addition.

One thought: maxout is intended as a regularization technique, much like Dropout. In theory it could be applicable to any layer. Here, it's tied together with the Dense layer.

So I think we should do one of the following...
- rename the layer to `MaxoutDense`
- include maxout as an option in the Dense layer, through a keyword argument such as `maxout_features` -> this minimizes the redundancy introduced by `MaxoutDense`
- develop a new layer that takes as input a basic layer, and applies maxout to it. Essentially it would apply the basic layer several times and return the max of the result. -> this option has maximum generality; I'm not sure how feasible it really is?

What do you think? Personally I'd favor the last option, in particular because I'm hearing maxout is useful after convolutional layers.

Something like `model.add(Maxout(Dense(128, 128), nb_feature=4))`.

**Comment by lukedeo** [comment]
Good thoughts!  Though the third option is nice from a semantic standpoint, I'd actually argue for number 1. Some thoughts:

* As someone who does a lot of weight visualization, I think option 1 would ensure users know *exactly* what layer topology they're looking at. I agree that it does add some redundancy, but I think having `MaxoutDense` and `MaxoutConvolution2D` as two seperate things wouldn't be a bad idea. 

* I think from a model standpoint, maxout does things very different than a normal layer (conv, fc, etc) -- I think that the separation also ensures that people (such as myself) who use `get_weights()` and then transfer them to other code / languages would benefit from the classes being as unambiguous as possible. 

* Perhaps in the long term something like `model.add(Maxout(Dense(128, 128), nb_feature=4))` would be useful, but I think this would actually lose a lot of key functionality.

**Comment by fchollet** [comment]
I don't mind adding `MaxoutDense` for now; we can look into implementing a generic version later, which will replace `MaxoutDense`. 

I'm curious, what functionality would a generic version lose? In terms of weight saving/visualization, a generic `Maxout` layer would let you access a list of weights of size `len(weights) == nb_feature * len(layer.params)`, where the weights for layer `i` would be at `weights[len(layer.params)*i:len(layer.params)*(i+1)]`.

**Comment by fchollet** [comment]
If you add the documentation paragraph in `layers/core.md`, I'll merge it (unless you want to investigate a more generic version right now...).

**Comment by lukedeo** [comment]
Awesome! I'll get this done today. then we can start thinking about making this generic...

**Comment by lukedeo** [comment]
Finished the docs...  let me know what you think!

**Comment by fchollet** [comment]
Merged!

**Comment by ddofer** [comment]
Any chance of an updated code example? Currently on MNIST this doesn't quite work for me 


"
model = Sequential()
# model.add(Dense(32*6*6, 784, init='orthogonal'))
model.add(MaxoutDense(784, 128, nb_feature=20))
model.add(Dropout(0.2))
model.add(MaxoutDense(128, 64, nb_feature=20))
model.add(Dropout(0.2))
model.add(Dense(64, 10))
model.add(Activation('softmax'))


rms = RMSprop()
model.compile(loss='categorical_crossentropy', optimizer=rms)

"

(I saw that in the keras.doc there's a dense layer added before the MAxOutDense; but I don't understand how that might help. Nor does it..)


>>>
"TypeError: ('Bad input argument to theano function with name "build\\bdist.win-amd64\\egg\\keras\\models.py:106"  at index 0(0-based)', 'Wrong number of dimensions: expected 2, got 4 with shape (1000L, 1L, 28L, 28L).')"


Thanks!

**Comment by lukedeo** [comment]
If you take a look at http://keras.io/layers/core/#maxoutdense, the `MaxoutDense` layer needs inputs with shape `(nb_samples, input_dim)`. So, for MNIST, you'll need to reshape your inputs so they have shape `(1000, 784)` instead of `(1000, 1, 28, 28)`.

**Comment by ddofer** [comment]
1000 being the mini batch size?
I.e should I use "reshape" or something else? Thanks!

**Comment by lukedeo** [comment]
I would take a look at [this](https://github.com/fchollet/keras/blob/master/examples/mnist_nn.py#L25), which shows how to appropriately change the data shape. You can pass batch size into `.fit(...)`, or you can do it manually with `.train(...)`.

**Comment by ddofer** [comment]
Thank you very much!

(Somewhat nonintuitive transformation..)

**Comment by lukedeo** [comment]
Well, it's quite common that when you have images arranged like `(nb_images, nb_channels, nb_pixels_x, nb_pixels_y)` and ` nb_channels = 1` (grayscalelike MNIST) to transform to a `(nb_images, nb_pixels_x * nb_pixels_y)` array so it can be fed to a fully connected layer...

**Comment by penguin2121** [comment]
Hello, are there any plans still of adding a maxout for convolutions?  I think that would be very useful.  The original maxout paper demonstrated that they greatly improved upon ReLU.

**Comment by fchollet** [comment]
It should not be very difficult to create your own layer to do this, since you have access to the Keras code for the `Convolution2D` layer and the `MaxoutDense` layer...

**Pull request merged**
