### PR TITLE
tensorflow 0.12 fixes

### PR DESCRIPTION
**Pull request by kashif**
see #4805

### CODE REVIEW

**Comment by kashif** [comment]
🎅 all the test pass... I will test more locally... but happy to get these changes reviewed!

**Comment by pifelbo** [comment]
Thanks, but this doesn't fix the issue when using `clipnorm`. Interestingly, this reveals a lack of testing for the optimizers.

**Comment by kashif** [comment]
@pifelbo I added the clipnorm tests and do not seem to get any errors with tf 0.12... am I doing something wrong?

**Comment by pifelbo** [comment]
@kashif Strange. I do not get any error running your tests, but I get the error mentioned in the issue when using the same code for training a complicated LSTM network architecture with `clip_norm` (no error without `clip_norm`). I guess there's a subtle change somewhere else affecting specific types of architectures, but that only causes an issue when using `clip_norm`.

**Comment by pifelbo** [comment]
@kashif Strange. I do not get an error running your tests, but I get the error mentioned in the issue when using the same code for training a complicated LSTM network architecture with `clip_norm` (no error without `clip_norm`). I guess there's a subtle change somewhere else affecting specific types of architectures, but that only causes an issue when using `clip_norm`.

**Comment by pifelbo** [comment]
@kashif Could you please try running the following script and see if you get any errors? I've just rebuilded Tensorflow from the newest source and still get the error.

```
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'
import tensorflow as tf
print(tf.__version__)

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Embedding, LSTM, Input, Bidirectional
from keras.datasets import imdb
from keras.optimizers import Adam

max_features = 20000
maxlen = 100  # cut texts after this number of words (among top max_features most common words)
batch_size = 32

print('Loading data...')
(X_train, y_train), (X_test, y_test) = imdb.load_data(nb_words=max_features)
print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')

print("Pad sequences (samples x time)")
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)
y_train = np.array(y_train)
y_test = np.array(y_test)

model = Sequential()
model.add(Embedding(max_features, 128, input_length=maxlen))
model.add(Bidirectional(LSTM(64)))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

adam = Adam(clipnorm=1)
model.compile(adam, 'binary_crossentropy', metrics=['accuracy'])

print('Train...')
model.fit(X_train, y_train,
          batch_size=batch_size,
          nb_epoch=4,
          validation_data=[X_test, y_test])

```

**Comment by pifelbo** [comment]
Ah, the error became present when testing a network with an Embedding layer in 0.12. However, it's an old error that still needs to be fixed (https://github.com/fchollet/keras/issues/3859). Ignore it wrt. this PR.

**Comment by kashif** [comment]
ok @Itaydal i will have a look at #4864

**Comment by kashif** [comment]
@Itaydal I could... not sure if my other changes are backward compatible... are we supporting older TF versions?

**Comment by Itaydal** [comment]
@kashif I don't know for sure, I'm new to the keras contribution effort.
What would it take to adapt your changes to be backward compatible?
Maybe we should ask someone else?

**Comment by fchollet** [comment]
But are these changes backwards compatible with TF 0.11? It's still what most people have installed.

**Comment by kashif** [comment]
ok @fchollet I'll make them work with TF 0.11 as well...

**Comment by fchollet** [comment]
Looks reasonable to me, thanks! Re-running tests.

**Comment by kashif** [comment]
thank you too! @fchollet

**Pull request merged**
