### PR TITLE
Fixes set_learning_phase in CNTK

### PR DESCRIPTION
**Pull request by fran6co**
CNTK scalar constants need `shape=(1)` => https://docs.microsoft.com/en-us/cognitive-toolkit/Parameters-And-Constants

Was getting an error when calling

```
K.set_learning_phase(0)
```

### CODE REVIEW

**Comment by fchollet** [comment]
@souptc : any thoughts on this? Thanks!

**Comment by souptc** [comment]
@fran6co, thanks report this, actually cntk does support scale, the bug is in the "set_learning_phase" method in cntk_backend.py:
`def set_learning_phase(value):

    global _LEARNING_PHASE

    if value not in {0, 1}:

        raise ValueError('CNTK Backend: Set learning phase '

                         'with value %s is not supported, '

                         'expected 0 or 1.' % value)

    v = np.float32([value])

    _LEARNING_PHASE.value = v`

The 'v= np.float32([value])' should be replaced with 'v=np.asarray(value)'. That is a bug I missed when scan the code before submit. sorry about that.

**Comment by fran6co** [comment]
@souptc Done

**Comment by souptc** [comment]
@fran6co thanks!

**Pull request merged**
