### PR TITLE
Small speed up

### PR DESCRIPTION
**Pull request by nouiz**
by preventing transfer to CPU or copy on the CPU just to get the shape.

### CODE REVIEW

**Comment by carlthome** [comment]
About how much of a performance difference would you guess this translates into?

**Comment by fchollet** [comment]
Great, thank you.

**Comment by fchollet** [comment]
> About how much of a performance difference would you guess this translates into?

This method is only used as a one time call in optimizers, if I recall correctly.

**Comment by nouiz** [comment]
Not much speed difference. I think it will be only when building the graph.
No speed up during execution.

Le 30 août 2016 20:57, "François Chollet" <notifications@github.com> a
écrit :

**Pull request merged**
