### PR TITLE
Added possibility to supply lr_scalers to SGD optimizer.

### PR DESCRIPTION
**Pull request by jeanpijon**
According to https://github.com/fchollet/keras/issues/414, adding new SGD option to enable scaling LR with different scalers

### CODE REVIEW

**Comment by EderSantana** [comment]
What does this do that can't be done with the LearningRateScheduler callback? Do you have an example code?

**Comment by jeanpijon** [comment]
Purpose of this code is to enable different LR for different layers, SGD now is not implemented in such a way. LearningRateScheduler can just set global LR, not in layer-wise manner. 

Example:
```
...
model = Sequential()
model.add(Dense(tr.nn_input_size, init='glorot_uniform'))
model.add(Dense(1024, init='glorot_uniform', activation='tanh'))
model.add(Dense(tr.nn_output_size, init='glorot_uniform', activation='tanh'))

sgd = keras.optimizers.SGD(lr=0.008, lr_scalers={0:0.01}) #I want first layer be optimized with LR 0.00008
model.compile(loss=loss, optimizer=sgd)
...
```

**Comment by EderSantana** [comment]
I got you, thanks!

**Comment by EderSantana** [comment]
let us wait for @fchollet's opinion, but I'd also suggest some documentation and examples like this one you just gave me in the PR. The test also doesn't seem to capture what you are proposing. It only tests that the code runs right? What about some `assert` statements?

**Comment by jeanpijon** [comment]
Ok, will do some reasonable tests and OK, documentation can be extended... but you are right let's wait for @fchollet

**Comment by fchollet** [comment]
This API requires to provide a dict `lr_scalers` that maps *indices in the parameter list* to scalar weights. This is not an acceptable user-facing API for anything more complex than a 1-layer MLP.

Indices in the parameter list do not encode information (each layer generally contributes several indices, and in the case of graphs, the order is basically random as far as the user is concerned). They are not user-facing and they should not be used in such a fashion.

**Comment by jeanpijon** [comment]
OK, I understand. So what do you suggest? Should it really be a parameter of Layer ? (I still thinks, this is more Optimizer related, than Layer related) Or can we somehow address the layers via something sensible than *indexes*?

Cheers Jan

**Comment by perone** [comment]
It would be very nice to have this implemented. How is the current status of this ?

**Pull request closed without merging**
