### PR TITLE
Bug fix - Cos

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by fchollet** [comment]
It's not possible for me to ensure the correctness of the `tensordot` lines just by looking at the code. Can you point me to the unit test that ensure correctness here (I forget if there are any for this specific function...)?

**Comment by farizrahman4u** [comment]
You can use `np.tensordot` to verify the output shape. I am currently working on a set of tests for all layers written by me, this includes `Lambda`, `LambdaMerge`, 'dot` and `cos` modes, `Siamese` layer etc. But it will take time because each of these can be used in different ways and I have to cover all possibilities to get good coverage.

**Comment by fchollet** [comment]
> I am currently working on a set of tests for all layers written by me, this includes Lambda, LambdaMerge, dot and cos modes, Siamese layer etc. 

Great. It would be neat to have full coverage for all layers.

**Comment by lemuriandezapada** [comment]
I've had issues running cos with recurrent nets. Do you think this patch addresses the problem?

**Pull request merged**
