### PR TITLE
Fix test_vector_clf

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by fchollet** [comment]
I actually committed that change yesterday. Only got around to submit it now... https://github.com/fchollet/keras/commits/master

**Comment by farizrahman4u** [comment]
@fchollet That is not enough. You can only reach 0.89 val_acc in 15 epochs.

**Comment by farizrahman4u** [comment]
And just out of curiosity, can anyone explain to me why this happens?

**Comment by farizrahman4u** [comment]
@fchollet  This seem to be an on and off issue. Checkout #893. The test passed for once, and now its failing again

**Comment by farizrahman4u** [comment]
The least val_acc observed so far after 15 epochs is 0.89. So merging from this PR should solve the issue

**Comment by farizrahman4u** [comment]
@fchollet  That is not enough. You can reach only **0.89** `val_acc` in **15 epochs**.

**Comment by farizrahman4u** [comment]
Now it dropped to **0.885**. What is happening?

**Pull request closed without merging**
