### PR TITLE
add cumsum and cumprod ops

### PR DESCRIPTION
**Pull request by kracwarlock**
These operations exist in both backends now. It think it makes sense to provide access directly through Keras. See #3792

### CODE REVIEW

**Comment by kracwarlock** [comment]
It seems that travis uses `tensorflow-0.9.0` while the latest stable release is `tensorflow-0.10.0`. Do we have plans to upgrade?

**Comment by fchollet** [comment]
> It seems that travis uses tensorflow-0.9.0 while the latest stable release is tensorflow-0.10.0. Do we have plans to upgrade?

Yes, we should upgrade. I believe our CTC utils will stop working with 0.10, so we will have to fix that when we upgrade (in a way that is still compatible with 0.9.0). You could attempt to open a PR for this if you feel like it.

**Comment by DeNeutoy** [comment]
+1 for this functionality

**Comment by kracwarlock** [comment]
Tests pass for tensorflow-0.11.0

**Comment by kracwarlock** [comment]
@fchollet do you have time to review this?

**Pull request closed without merging**
