### PR TITLE
Bug Fix : Sequential model is ignoring trainable argument of child containers

### PR DESCRIPTION
**Pull request by farizrahman4u**
Found this issue while writing a vanilla GAN: Discriminator weights are changing even when trainable=False. Issue only when the final model is Sequential. 

```python
discriminator = Sequential()
discriminator.add(Dense(1, input_dim=10, activation='sigmoid'))

generator = Sequential()
generator.add(Dense(10, input_dim=10))

GAN = Sequential()
GAN.add(generator)

discriminator.trainable = False

GAN.add(discriminator)
GAN.compile(loss='mse', optimizer='sgd')

x = np.random.random((100, 10))
y = np.ones((100, 1))

discriminator_initial_weights = discriminator.get_weights()
GAN.fit(x, y)
assert np.all(discriminator.get_weights()[0] == discriminator_initial_weights[0]), 'Discriminator weights changed!'
```

### CODE REVIEW

**Comment by farizrahman4u** [comment]
@fchollet 

Important:

* Previously, if the trainable attribute of a Sequential model was False, calling fit would still tune the weights. Weights would be frozen for functional API models. Though this behavior of Sequential model was a bug, it facilitated training GANs with ease. If this bug did not exist, we would have re-compile the discriminator after each iteration.

*  With this PR, the trainable attribute of the model being compiled is ignored for both Sequential and Functional API models. (I am extending the bug to Functional API models). The trainable attribute of a model will have effect only when it is nested as a layer inside another model.

**Comment by fchollet** [comment]
> If this bug did not exist, we would have fad to re-compile the discriminator and generator after each iteration.

Not after each iteration. You just compile two models (which share weights) and train them alternatively.

You are right that there was a bug. I pushed a fix that makes things simpler: https://github.com/fchollet/keras/commit/c5cc96a4f4973c75e2eb533c3c88a234fbc333e4

Also added a test: https://github.com/fchollet/keras/commit/703d5a1298befcdcc2f87cbe3080f18fb866b63d

**Comment by farizrahman4u** [comment]
Still not good. Sequential model and functional api model still behaves differently. I think you are missing the fact that the internal model instance of a Sequential model is still trainable even the trainable attribute of the Sequential model is set to False.

**Comment by farizrahman4u** [comment]
#4509

**Comment by fchollet** [comment]
> Still not good. Sequential model and functional api model still behave differently.

They don't, see the unit test: https://github.com/fchollet/keras/blob/master/tests/test_dynamic_trainability.py#L58

If you see a case that's not covered, then please add a unit test for it.

> the internal model instance of a Sequential model is still trainable even the trainable attribute of the Sequential model is set to False.

The internal `model` property of a `Sequential` model is private and never accessed by the user. It is unimportant what its attributes may or may not be, the relevant attributes there are that of the `Sequential` parent. No one is supposed to know that this internal `model` attribute even exists.

**Comment by farizrahman4u** [comment]
@fchollet When you compile a Sequential model, the internal model gets compiled, which means you are collecting the trainable weights of the internal model, not the Sequential model. 

Try this:

```python
from keras.layers import *
from kerasmodels import *

x = np.random,random((100, 10))
y = np.random,random((100, 10))

# Functional
a = Input((10,))
b = Dense(10)(a)
func_model = Model(a, b)

test_trainable(func_model) # >>>OK

# Sequential

seq_model = Sequential()
seq_model.add(Dense(10, input_dim=10))

test_trainable(seq_model) # Error

def test_trainable(model):
    model.trainable = False
    model.compile(loss='mse', optimizer='sgd')
    initial_weights = model.get_weights()
    model.fit(x, y)
    assert np.all(model.get_weights()[0] == initial_weights[0]), 'Weights changed'
    print('OK')
```

**Pull request closed without merging**
