### PR TITLE
changed VAE sampling variance to 1

### PR DESCRIPTION
**Pull request by thangbui**
In discussion with Amar Shah @amarshah.

The loss/negative lower bound is now correct with this fix.

### CODE REVIEW

**Comment by lukovkin** [comment]
This value (0.01) was introduced last time in #3838. It appeared to produce better results.
This value (epsilon_std) has been changed back and forth multiple times, I think we should stick to something finally ;)

**Comment by thangbui** [comment]
The standard reparameterisation technique works with variance = 1. If it is not 1, the bound as computed in the code is no longer the variational lower bound. To check this, try 0.01 and latent dim to 20, the objective given by the code is ~60, which is way lower than what it should be for MNIST (should be around 90-100).

**Comment by tboquet** [comment]
@thangbui yes I changed the other example so that we have the same parameters in both script. The 0.01 was introduced with the deconv example. If we want to stick to the paper it should be 1.

**Comment by amarshah** [comment]
An alternative to fixing epsilon_std to 1 would simply be to incorporate epsilon_std in the KL loss term

**Comment by fchollet** [comment]
So what's the consensus on this value?

**Comment by tboquet** [comment]
+1 to match the paper and get the variational lower bound right. In #3838, I only copied this parameter from the first version of the deconv example to the variationnal autoencoder example.

**Pull request merged**
