### PR TITLE
logging module instead of print()s

### PR DESCRIPTION
**Pull request by wuaalb**
Changed all print() calls in the package (not examples, tests) to use Python's built-in logging module.
In my case because I wanted to log all output of Keras to a file.

Added a package-global logger to keras/__init__.py, with some code to setup the logger to behave like print() by default without the user having to do anything.
Then all calls to print() where changed logger.info() calls.
Changed string formatting to % in all cases, although logging functions also support formatting string with remaining passed arguments.

### CODE REVIEW

**Comment by fchollet** [comment]
Very easy for a user needing this to set that up (you could set verbose to 0 everywhere and either call logging in your own code or from a custom callback). 

It would be terrible UX and it breaks the default verbosity mode.

**Comment by fchollet** [comment]
> In my case because I wanted to log all output of Keras to a file.

For this specific use case, have you considered just dumping stdout to a file?

**Comment by wuaalb** [comment]
Fair enough. Thanks!

I'll leave a little code snippet here for if anyone has the same problem
```python
import sys

class Logger(object):
    def __init__(self, stream=sys.stdout, filename='logfile.log', mode='w'):
        self.stream = stream
        self.file = open(filename, mode)

    def __del__(self):
        self.file.close()

    def write(self, message):
        self.stream.write(message)
        self.stream.flush()
        self.file.write(message)  
        self.file.flush()

sys.stdout = Logger()
```

**Comment by phreeza** [comment]
> It would be terrible UX and it breaks the default verbosity mode.
How so, if you pipe the log output to stdout, shouldn't it have the same behaviour as before? I think organising output this way is very clean and useful, especially for debug output which should not be displayed in standard operations.

**Pull request closed without merging**
