### PR TITLE
Bug fix: model.summary is ignoring model.trainable

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by isaacgerg** [comment]
I just saw you added this. I wrote a small test program to verify in #4514.

**Comment by fchollet** [comment]
It's called `count_params`, and `Param #`, respectively. Nothing about it is supposed to be "trainable params only". It should report just trainable weighs, and it shouldn't change based on the `trainable` layer property. Fixed in https://github.com/fchollet/keras/commit/57f2f1100586bf55000490b86c8af25107d5447a

**Comment by farizrahman4u** [comment]
For clarity, why not let model.summary print separate counts for trainable and non trainable weights?

**Comment by isaacgerg** [comment]
@fchollet It would be really useful for debugging to know how many weights are trainable and how many are not.

**Pull request closed without merging**
