### PR TITLE
Coveralls Tag

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by phreeza** [comment]
:+1:

**Comment by fchollet** [comment]
We'll wait until we pass 85%. Currently we're at 77%.

**Comment by farizrahman4u** [comment]
OK. I will leave it open.

**Comment by fchollet** [comment]
We're at 84% now. If you improve coverage 1-2% further we'll add the badge ;-)

**Comment by fchollet** [comment]
Coveralls hasn't been working in a while.

**Pull request closed without merging**
