### PR TITLE
Added averaging support in merge and a TimeDistributedMerge layer

### PR DESCRIPTION
**Pull request by jmhessel**
- Average support for merge
- TimeDistributedMerge

### CODE REVIEW

**Comment by fchollet** [comment]
Looks good. Can you add a quick test (short and faster to run), in the spirit of the existing layer tests?

**Comment by jmhessel** [comment]
ive been very busy in the last few days, I will be able to do this asap though

**Comment by jmhessel** [comment]
Okay, I added a 2 line auto test... should I add a different one?

**Comment by fchollet** [comment]
Ok, looks good!

**Pull request merged**
