### PR TITLE
tensordot and batch_tensordot

### PR DESCRIPTION
**Pull request by xingdi-eric-yuan**
add tensordot and batch_tensordot into keras backend

### CODE REVIEW

**Comment by farizrahman4u** [comment]
Are you aware of the `batxh_dot` function?

**Comment by xingdi-eric-yuan** [comment]
@farizrahman4u 
No I thought it does same thing as T.batched_dot(). Thanks, I'll check it !

**Comment by xingdi-eric-yuan** [comment]
@farizrahman4u I have a question, if the 0th dimension is not batch dimension, i.e. if I want to do something like T.tensordot(), then the batch_dot will fail, right?

**Comment by farizrahman4u** [comment]
In keras, there is always a batch dimesnsion right? This is what i recomend you to do:  K.batch_dot can handle only integer axes, whereas the underlying T.batched_tensordot supports tuple axes. This is so because tensorflow can not handle tuple axes. If you can enable multiple axes dot in tensorflow (hard), and allow it in theano backend (easy), that would be great.

**Pull request closed without merging**
