### PR TITLE
"Epoch %d out of %d"

### PR DESCRIPTION
**Pull request by rodrigob**
Print "Epoch %d out of %d" instead of just "Epoch %d"

### CODE REVIEW

**Comment by fchollet** [comment]
I'd go with 
```python
print('Epoch %d/%d' % (epoch + 1, self.nb_epoch + 1))
```
(`/` to save space, 1-indexing because 0-indexing looks weird here)

**Comment by rodrigob** [comment]
done.

**Comment by fchollet** [comment]
Oops sorry, I was distracted. It should actually be `(epoch + 1, self.nb_epoch)`, so as to have e.g. 
1/10
...
10/10

**Comment by rodrigob** [comment]
double done.

**Comment by fchollet** [comment]
👍

**Pull request merged**
