### PR TITLE
allow the wheel format

### PR DESCRIPTION
**Pull request by stonebig**

### CODE REVIEW

**Comment by stonebig** [comment]
and now:
````
python setup.py sdist bdist_wheel  --universal
twine upload dist/*
````

**Comment by fchollet** [comment]
What's the context on this?

**Comment by stonebig** [comment]
It's easier and border-effect less to include a package provided as a wheel into a distribution like WinPython.
It's also helping moving the default python packaging system out of dark ages.

**Comment by fchollet** [comment]
Closing because I still don't understand what's the value of this PR ("helping moving the default python packaging system out of dark ages" is pretty abstract).

**Comment by stonebig** [comment]
There is pep-0427 reading alsi, which may be a little more factual. Sorry I didn't convince you.

https://www.python.org/dev/peps/pep-0427/#rationale

**Pull request closed without merging**
