### PR TITLE
Fix a issue when only specify one dot_axes for in the Merge layer in the dot mode

### PR DESCRIPTION
**Pull request by kemaswill**
@farizrahman4u Just wonder if there is a bug in line 1225. When there is only one dot_axes specified in the Merge layer in the dot mode, should not we change the dot_axes = [dot_axes, dot_axes] just as done in line 1147-1148? After the this fix, the following code can be ran correctly(only specify one dot_axes) otherwise will fail:
```
model_word = Sequential()
model_word.add(Embedding(1e4, 300, input_length=1))
model_word.add(Reshape((1,300)))
models.append(model_word)

model_context = Sequential()
model_context.add(Embedding(1e4, 300, input_length=5))
model_context.add(Reshape((5,300)))
models.append(model_context)

model = Sequential()
# Both dot_axes = 2 and dot_axes = [2, 2] will work now, otherwise only [2,2] will work
model.add(Merge(models, mode='dot', dot_axes = 2))
print model.layers[-1].output_shape
model.add(Reshape((5,)))
print model.layers[-1].output_shape
model.add(Dense(5))
model.add(Activation('sigmoid'))
model.compile(loss='mean_squared_error', optimizer='sgd')
```

### CODE REVIEW

**Comment by kemaswill** [comment]
One question about pull request, why this pull request shows so many previous commit? I have synced my remote with the latest keras master branch, so I think this pull request should have only the last commit... Orz...

**Comment by fchollet** [comment]
> One question about pull request, why this pull request shows so many previous commit? I have synced my remote with the latest keras master branch, so I think this pull request should have only the last commit... Orz...

That's not a concern, all commits will be squashed into a single one anyway.

**Comment by fchollet** [comment]
@farizrahman4u what do you think about this?

**Comment by farizrahman4u** [comment]
The `if dot_axes < 0:` check seems unnecessary to me.
Just
```python
if type(dot_axes) == int:
    dot_axes = [dot_axes] * 2
```
would do.

**Comment by kemaswill** [comment]
I have submit a new commit, which remove 
```
if type(self.dot_axes) == int:		
    self.dot_axes = [self.dot_axes, ] * 2
```
in the ```__init__(self)``` function of class Merge to keep code simple and unduplicated. Since it's ```_arguments_validation()```'s responsibility to check the validation of the arguments and convert them if necessary.

To achieve this, I have replaced variable ```dot_axes``` in ```_arguments_validation()``` to ```self.dot_axes``` so that this conversion can be seen in the other function of the Merge class, such as in line 1369, 1370 of ```get_output_shape_for()```.


@farizrahman4u 
Seems that we can not directly remove the ```if dot_axes < 0:```, since removing it will cause "IndexError: tuple index out of range" Exception due to line 1230.

**Comment by fchollet** [comment]
LGTM

**Pull request merged**
