### PR TITLE
adding densenet on cifar10 implementation

### PR DESCRIPTION
**Pull request by roatienza**
Example implementation of DenseNet on CIFAR10. Example is 100-Layer DenseNet-BC (k=12). Growth rate is 12.

### CODE REVIEW

**Comment by titu1994** [comment]
DenseNet, DenseNet-BC and DenseNetFCN (Tiramisu DenseNet) are all part of Keras Contrib - https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/applications/densenet.py

DenseNet / DenseNet-BC also several pretrained weights for certain configurations. 

@fchollet Perhaps the DenseNet models (not FCN type) should be added to core Keras since they offer more functionality?

**Comment by fchollet** [comment]
> Perhaps the DenseNet models (not FCN type) should be added to core Keras since they offer more functionality?

In what way do you think of adding them?

**Comment by titu1994** [comment]
@fchollet Adding them as an application, similar to the MobileNet application. 

DenseNets and DenseNet-BC are models with several configurations. They were kept in Contrib because the accompanying weights for certain configurations from the paper weren't available in Keras, but now that the weights are available, it would be better to add them to core Keras.

Considering that DenseNets we're the SotA model for ImageNet in 2016, it would be beneficial to have them in the core repository for easy access. Contrib has far fewer users than Keras overall, if the number of PRs and star ratings are an indicator. 

However, that would make this PR somewhat redundant.

**Comment by roatienza** [comment]
If and when the contrib DenseNet makes into keras/applications, I can make changes and a new PR. For the meantime, end users might want to see how densenet is implemented in keras on a dataset like cifar10 that can be easily understood and ready to run. This PR would be useful in that case.

**Comment by ahundt** [comment]
I'd recommend keeping DenseNet in keras-contrib until a memory efficient implementation is supported by tensorflow. https://github.com/tensorflow/tensorflow/issues/12948

**Comment by ahundt** [comment]
Also, if any version is to be merged I'd recommend the keras-contrib version. It is very well written, supports ImageNet weights, and has been tested and debugged by several people over a period of at least 6 months. Sorry about that @roatienza.

**Comment by fchollet** [comment]
> I recommend keeping DenseNet in keras-contrib only until a memory efficient implementation is supported by tensorflow as described in tensorflow/tensorflow#12948.

> Also, if any DenseNet implementation is to be merged, I recommend the keras-contrib version. It is very well written, supports ImageNet weights, and has been tested and debugged by several people over a period of at least 6 months. Sorry about that @roatienza.

Both very reasonable suggestions.

**Comment by titu1994** [comment]
I've been hoping for a shared tensor allocation to properly implement the memory efficient DenseNet. Hopefully the TF devs respond. I too agree that the contrib models be kept in Contrib for the time being. 

Once cuDNN 7 is used in the next TF version, hopefully both shared allocations and grouped convolutions will be supported in TF.

**Comment by roatienza** [comment]
conclusion: use densenet in contrib

**Pull request closed without merging**
