### PR TITLE
Create mnist_reinforce_generator.py

### PR DESCRIPTION
**Pull request by EderSantana**
The combo: functional api + fit_generators is defenitively one of Keras' biggest strengths.
Here we show how to quickly create a custom generator for a multi-ouput Model. (How to do this is surprisingly hidden in Keras, but let me know if this is because I failed to properly read the docs)

Also, we show how easy it is do REINFORCE using a little automatic differentiation trick (bring on RL kids!!!).

### CODE REVIEW

**Comment by EderSantana** [comment]
@fchollet I didn't get the error. Is it a pep8 error?

btw, do you think this is useful?

**Comment by fchollet** [comment]
> @fchollet I didn't get the error. Is it a pep8 error?

Yes, there seems to be a PEP8 indentation issue in your code.

> btw, do you think this is useful?

I think a demonstration of REINFORCE would be great to have. Two remarks:
- `fit_generator` is not necessary here, `fit` would do a great job and would make things simpler
- I'm not convinced that MNIST classification is the best possible example for REINFORCE.

What do you think? Can you come up with a reinforcement learning example for REINFORCE (maybe something on top of `gym`)?

**Comment by EderSantana** [comment]
I can write something for `gym`. Do you want to have that here on examples?

My problem with the `fit_generator` was that it was not easy to figure how to use it for complex graphs. We should at least add something in the docs. So, should we cancel this PR and get part of the code from this example and make a quick note on the docs then?

**Comment by fchollet** [comment]
> I can write something for gym. Do you want to have that here on examples?

I think it would be neat to have!

> So, should we cancel this PR and get part of the code from this example and make a quick note on the docs then?

If you think the docs are not clear, then yes it would be best to update the docs. Btw using lists is not the only option, you could use dicts as well!

**Comment by EderSantana** [comment]
interesting... I tried dicts without success. Let me give another try

**Comment by EderSantana** [comment]
All right I'll close this for now

**Pull request closed without merging**
