### PR TITLE
Added recurrent convolution network

### PR DESCRIPTION
**Pull request by jeammimi**
Hello, I develop a recurent convolutionnal neural network.
According to  [Convolutional LSTM Network: A Machine Learning Approach for Precipitation Nowcasting](http://arxiv.org/pdf/1506.04214v1.pdf)

It is very close to the code for the regular recurrent network, and I found that there is a
new function which is called get_constants and I am not sure what it does.
I can follow the code and just copy it but if somebody could explain.

Here are two animation that show what it can do:

animatespheres8

animatespheres10

Here is the code to build the layers for this exemple:

```python
from keras.models import Sequential,Graph
from keras.layers.convolutional import Convolution2D,Convolution3D
from keras.layers.recurrent_convolutional import LSTMConv2D

seq = Sequential()
seq.add(LSTMConv2D(nb_filter=15, nb_row=3, nb_col=3, input_shape=(10,40,40,1),
                   border_mode="same",return_sequences=True))
seq.add(LSTMConv2D(nb_filter=15,nb_row=3, nb_col=3,
                   border_mode="same", return_sequences=True))
seq.add(LSTMConv2D(nb_filter=15, nb_row=3, nb_col=3,
                   border_mode="same", return_sequences=True))
seq.add(Convolution3D(nb_filter=1, kernel_dim1=1, kernel_dim2=3,
                      kernel_dim3=3, activation='sigmoid',
                   border_mode="same", dim_ordering="tf"))

seq.compile(loss="binary_crossentropy",optimizer="adadelta")
```

### CODE REVIEW

**Comment by fchollet** [comment]
I'm curious about this. Would this be any different from e.g.:

```python
model.add(TimeDistributed(Convolution2D(16, 3, 3)))
model.add(LSTM(32))
```

**Comment by EderSantana** [comment]
@fchollet it would, in ConvLSTM you have several RNNs around the image with shared parameters. All the connections, input-to-hid, hid-to-hid, etc are all convolutions. The hidden state is an image!!! With the code you wrote, you have one global LSTM that see the entire image representation at once. ConvLSTM is better if you have shift invariant temporal components. Which is usually the case in natural images videos.

**Comment by fchollet** [comment]
Ok, I get it. It's neat! Will try to make some time to check it out later this week.

**Comment by jasper95** [comment]
hi guys. I'm having a trouble using this. I'm just being desperate to experiment my data using this architecture.
```python
import numpy as np
from keras.models import Sequential
from keras.layers.convolutional import Convolution2D, Convolution3D
from keras.layers.recurrent_convolutional import LSTMConv2D

all_data = np.loadtxt('../final_weekly_data.txt')
sample_size = all_data.shape[0]
all_data = all_data.reshape((sample_size, 1, 107, 72))

filter_size = 3

SE = all_data[:, :, 107/2:, 0:72/2]

ts_data = np.ones((155, 3, 1, 54, 36))

for i in range(ts_data.shape[0]):
    ts_data[i, :, :, :, :] = SE[i:i+3]
X = ts_data[:, :-1, :, :, :]
Y = ts_data[:, 1:, :, :, :]

X_train = X[:X.shape[0]*.6]
Y_train = Y[:Y.shape[0]*.6]

print X_train.shape, Y_train.shape
model = Sequential()
model.add(LSTMConv2D(2, 3, 3, input_shape=(2, 1, 54, 36),
          border_mode='same', dim_ordering='th', return_sequences=True))
model.add(LSTMConv2D(2, 3, 3, border_mode='same',
          dim_ordering='th', return_sequences=True))
model.add(LSTMConv2D(2, 3, 3, border_mode='same',
          dim_ordering='th', return_sequences=True))
model.add(Convolution3D(nb_filter=1, kernel_dim1=1, kernel_dim2=3,
                        kernel_dim3=3, activation='sigmoid',
                        border_mode="same", dim_ordering="th"))
model.compile(loss='binary_crossentropy', optimizer='adadelta')
model.fit(X_train, Y_train, batch_size=32, verbose=1)
```

I'm getting the following error shown below.

> Using Theano backend.
(93, 2, 1, 54, 36) (93, 2, 1, 54, 36)
Epoch 1/100
Traceback (most recent call last):
  File "model_3.py", line 36, in <module>
    model.fit(X_train, Y_train, batch_size=32, verbose=1)
  File "/home/jasper/.virtualenvs/thesis/local/lib/python2.7/site-packages/keras/models.py", line 701, in fit
    shuffle=shuffle, metrics=metrics)
  File "/home/jasper/.virtualenvs/thesis/local/lib/python2.7/site-packages/keras/models.py", line 317, in _fit
    outs = f(ins_batch)
  File "/home/jasper/.virtualenvs/thesis/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 446, in __call__
    return self.function(*inputs)
  File "/home/jasper/.virtualenvs/thesis/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/jasper/.virtualenvs/thesis/local/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/jasper/.virtualenvs/thesis/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[1] = 2, input[1].shape[1] = 1)
Apply node that caused the error: Elemwise{Composite{((i0 * log(i1)) + (i2 * log(i3)))}}(<TensorType(float32, 5D)>, Elemwise{clip,no_inplace}.0, Elemwise{sub,no_inplace}.0, Elemwise{sub,no_inplace}.0)
Toposort index: 518
Inputs types: [TensorType(float32, 5D), TensorType(float32, 5D), TensorType(float32, 5D), TensorType(float32, 5D)]
Inputs shapes: [(32, 2, 1, 54, 36), (32, 1, 2, 54, 36), (32, 2, 1, 54, 36), (32, 1, 2, 54, 36)]
Inputs strides: [(15552, 7776, 7776, 144, 4), (15552, 15552, 7776, 144, 4), (15552, 7776, 7776, 144, 4), (15552, 15552, 7776, 144, 4)]
Inputs values: ['not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Sum{axis=[1, 2, 3, 4], acc_dtype=float64}(Elemwise{Composite{((i0 * log(i1)) + (i2 * log(i3)))}}.0)]]
HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.


I installed keras 0.3.3, manually created a recurrent_convolutional.pyc and copied with the .py file to the keras/layers on my virtualenv. Any thoughts? @jeammimi @fchollet

**Comment by EderSantana** [comment]
@jasper95 if nothing else works, try the version we have on Seya. This test shows how to use it a ConvGRU https://github.com/EderSantana/seya/blob/master/tests/test_conv_rnn.py#L35-L50

I hope it works for you.

**Comment by jasper95** [comment]
thanks @EderSantana will try it. :+1:

**Comment by jasper95** [comment]
@EderSantana what's the proper way to install it?

**Comment by jeammimi** [comment]
Hi.
To debug this can of layer one way is first to check if
it can predict something and what is the shape.

when I run your layer on
ts_data = np.ones((155, 2, 1, 54, 36))

print model.predict(ts_data).shape
return a shape of (155, 1, 2, 54, 36)

By reading the Doc of Conv3D and LSTMConv, it seems that you should put
the channel value at the end and use tf mode for both, because the th mode
ar not defined in the same way.






2016-04-04 5:27 GMT+02:00 jasper95 <notifications@github.com>:

**Comment by jasper95** [comment]
thanks @jeammimi 
To clarify, the mistake you're pointing out is the ordering of my dimensions

```python 
model.add(LSTMConv2D(2, 3, 3, input_shape=(2, 1, 54, 36),
          border_mode='same', dim_ordering='th', return_sequences=True)) 
```
and I should use 'tf' for all dim_ordering?

**Comment by jeammimi** [comment]
The problem is that the LSTMConv and Conv3d are not using the same ordering
of dimension in th mode.
(But they are using the same convention in tf mode)
so it will be easier for you to put your channel dimension at the end (
input_shape=(2, 54, 36,1))
and use tf mode for LSTMConv2D and Conv3d.



2016-04-04 12:43 GMT+02:00 jasper95 <notifications@github.com>:

**Comment by jasper95** [comment]
@jeammimi got it running thx. I'm just curious how did you choose the number of filters for ConvLSTM2D. is it based on your original video length?

**Comment by jeammimi** [comment]
I am sorry I didn't use it much for real application.
But I think the number of filter depends more on the complexity of your
system than on the length of your video.

2016-04-04 17:30 GMT+02:00 jasper95 <notifications@github.com>:

**Comment by jasper95** [comment]
hello @jeammimi If you don't mind, i just want to ask what is the format of your input and output data. Is it in the range (0,1) or exactly 0/1?

**Comment by EderSantana** [comment]
are we still looking into merging this? what is the dev state?

**Comment by fchollet** [comment]
@EderSantana this PR is too old, but adding a Recurrent-Convolutional layer sounds good to me. It's definitely a useful layer, and getting more mainstream.

**Comment by jeammimi** [comment]
I updated the layer to work with keras v1.
Here is a working exemple:
https://github.com/imodpasteur/keras/blob/recconvV1/examples/TestConv2DLSTM.ipynb
I can do a new pull request with this version


2016-09-20 5:33 GMT+02:00 François Chollet <notifications@github.com>:

**Comment by EderSantana** [comment]
@jeammimi I just wrote a new ConvRNN as well, so you can update your PR and let me know wherever you need help

**Comment by carlthome** [comment]
@jeammimi, yes please update this pr with a CNN-LSTM layer.

**Comment by fchollet** [comment]
Actually, better to open a new PR and close this one, so you'll be on top of the pile...

**Comment by carlthome** [comment]
@jeammimi, ETA on a new pr? Just curious! :smiley:

**Pull request closed without merging**
