### PR TITLE
Epoch is 0 indexed, add one to match from fit

### PR DESCRIPTION
**Pull request by smgt**
Output from callbacks include epoch, but the epoch is index 0 format. It shows up when callbacks output information about the epoch.

Example:

```
Epoch 1/100
2300/2300 [==============================] - 462s - loss: 3.6914 - acc: 0.7710 - val_loss: 3.7383 - val_acc: 0.7681
Epoch 2/100
2300/2300 [==============================] - 457s - loss: 3.6921 - acc: 0.7709 - val_loss: 3.7442 - val_acc: 0.7677
Epoch 3/100
2299/2300 [============================>.] - ETA: 0s - loss: 3.6904 - acc: 0.7710
Epoch 00002: reducing learning rate to 9.999999747378752e-06.
```

Notice how the lr reduction is showing epoch 2 instead of the correct epoch 3.

The callback `ModelCheckpoint` will also save checkpoints with the correct epoch number in the filename.

### CODE REVIEW

**Comment by fchollet** [comment]
Please fix PEP8 style.

**Comment by smgt** [comment]
Sorry, should have checked Travis results. Added a new commit with PEP8 fixes.

**Comment by montanalow** [comment]
This change introduces an off by 1 error in a callbacks that use the epochs from CheckpointModel, as indicated by the change to the spec. It would be nicer in the future to preserve the original behavior, and make improvements opt-in until promoting them in a minor version bump, as opposed to a patch.  i.e. patches in public projects shouldn't change specs.

**Comment by hko-gh** [comment]
Isn't this introducing more problems then it solves? I am using my own callbacks additionally and now the epoch values do not match the files stored by the ModelCheckpoint anymore! For me this resulted in silently using the wrong weights for evaluation.

**Pull request merged**
