### PR TITLE
Fix json serialization in merge layer

### LINKED ISSUE #2818: TypeError: Not JSON Serializable
There is a sample code that will reproduce the error:
https://gist.github.com/henry0312/c5e37cf219498a692520ddc01d2e41ba

Run: `python keras_save_json_bug.py `

```
Traceback (most recent call last):
  File "keras_save_json_bug.py", line 59, in <module>
    json_string = net.to_json()
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/engine/topology.py", line 2373, in to_json
    return json.dumps(model_config, default=get_json_type, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/engine/topology.py", line 2366, in get_json_type
    raise TypeError('Not JSON Serializable')
TypeError: Not JSON Serializable
```

### PR DESCRIPTION
**Pull request by henry0312**
Fix #2818

### CODE REVIEW

**Comment by fchollet** [comment]
So this fixes your issue?

**Comment by henry0312** [comment]
Yes, howerver, another issue occurs:

```
In [2]: model = model_from_json(open('my_model_architecture.json').read())
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-4ab679c0f9db> in <module>()
----> 1 model = model_from_json(open('my_model_architecture.json').read())

/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/models.py in model_from_json(json_string, custom_objects)
     34     from keras.utils.layer_utils import layer_from_config
     35     config = json.loads(json_string)
---> 36     return layer_from_config(config, custom_objects=custom_objects)
     37
     38

/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/utils/layer_utils.py in layer_from_config(config, custom_objects)
     33         layer_class = get_from_module(class_name, globals(), 'layer',
     34                                       instantiate=False)
---> 35     return layer_class.from_config(config['config'])
     36
     37

/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/engine/topology.py in from_config(cls, config, custom_objects)
   2234
   2235         for layer_data in config['layers']:
-> 2236             process_layer(layer_data)
   2237
   2238         name = config.get('name')

/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/engine/topology.py in process_layer(layer_data)
   2231                         layer(input_tensors[0])
   2232                     else:
-> 2233                         layer(input_tensors)
   2234
   2235         for layer_data in config['layers']:

/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/engine/topology.py in __call__(self, inputs, mask)
   1263                                        node_indices, tensor_indices)
   1264             self.built = True
-> 1265             self.add_inbound_node(layers, node_indices, tensor_indices)
   1266
   1267             outputs = self.inbound_nodes[-1].output_tensors

/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/engine/topology.py in add_inbound_node(self, inbound_layers, node_indices, tensor_indices)
    541         # creating the node automatically updates self.inbound_nodes
    542         # as well as outbound_nodes on inbound layers.
--> 543         Node.create_node(self, inbound_layers, node_indices, tensor_indices)
    544
    545     def get_output_shape_for(self, input_shape):

/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/engine/topology.py in create_node(cls, outbound_layer, inbound_layers, node_indices, tensor_indices)
    165                             '"" should return one shape tuple per '
    166                             'output tensor of the layer. Found: ' +
--> 167                             str(output_shapes))
    168         if len(output_tensors) != len(output_masks):
    169             raise Exception('The `compute_mask` method of layer "' +

Exception: The `get_output_shape_for` method of layer "merge_1"" should return one shape tuple per output tensor of the layer. Found: [None, 64]
```

**Comment by henry0312** [comment]
for json serialization, the PR will fix the issue.

**Comment by henry0312** [comment]
what's wrong with `output_shape` in `merged_vector = merge([y1, y2], mode=lambda x: x[0] - x[1], output_shape=(None, 64))`?
(cf. https://gist.github.com/henry0312/c5e37cf219498a692520ddc01d2e41ba#file-keras_save_json_bug-py-L31)

**Comment by fchollet** [comment]
It should be `(64,)`. It doesn't include the batch size. This is explained in the docs.

**Comment by henry0312** [comment]
yeah, I think so, but the below error occurs:

```
Traceback (most recent call last):
  File "keras_save_json_bug.py", line 58, in <module>
    model, net = create_model()
  File "keras_save_json_bug.py", line 32, in create_model
    output = Dense(10, activation='sigmoid')(merged_vector)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/engine/topology.py", line 458, in __call__
    self.build(input_shapes[0])
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/Keras-1.0.3-py3.5.egg/keras/layers/core.py", line 589, in build
    assert len(input_shape) == 2
AssertionError
```

**Comment by henry0312** [comment]
a standalone sample is here: https://gist.github.com/henry0312/9c1aee0a4330c860ff7b2bb139acbb15

**Comment by fchollet** [comment]
You should open an issue, this PR is not the place to discuss this.

I have noticed a problem with the code. I will push a fix.

**Comment by henry0312** [comment]
OK!

**Pull request merged**
