### PR TITLE
Unrollable RNN

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by fchollet** [comment]
So what is the performance impact of unrolling with Theano? Wouldn't scan be faster, especially for long sequences?

**Comment by farizrahman4u** [comment]
Quoting from http://deeplearning.net/software/theano/library/scan.html#minimizing-scan-usage:

>Scan makes it possible to define simple and compact graphs that can do the same work as much larger and more complicated graphs. However, it comes with a significant overhead. As such, when performance is the objective, a good rule of thumb is to perform as much of the computation as possible outside of Scan. This may have the effect of increasing memory usage but can also reduce the overhead introduces by using Scan.

**Comment by farizrahman4u** [comment]
For long sequences, scan should be used anyway. Else the graph will be too big.

**Comment by pasky** [comment]
Wouldn't it be appropriate to include some of this in the description of the flag, helping people to choose when to enable it? Say

    unroll: boolean. If True, the rnn will be unrolled, making it faster,
            but consuming a lot more memory in case of long sequences.

**Comment by fchollet** [comment]
Problems with this PR:

- documentation is not helpful or descriptive. Currently: 

> unroll: Has no effect when using tensorflow backend.

- no tests to verify that the unrolled version behaves exactly like the scan version
- introducing layer-level arguments that only apply to one backend is problematic, and will be increasingly problematic going forward (as we add new backends).
- the claim that the unrolled version is faster is not backed by any concrete numbers. Is it faster, by how much, under which conditions?

**Comment by fchollet** [comment]
Closing outdated PRs following the release of Keras 1.0.

**Pull request closed without merging**
