### PR TITLE
Add barrel transform in preprocessing/image.py

### PR DESCRIPTION
**Pull request by erilyth**
A suitable range for alpha is from 0.1 to 0.25. Based on the intensity the value of alpha is set.
Sample output:
barrelorig
barrel

### CODE REVIEW

**Comment by fchollet** [comment]
A Python-side pixel-by-pixel iteration loop seems like a tremendously costly way to implement this. A better approach would be to use the fast primitives offered by `np.ndimage.interpolation`: https://docs.scipy.org/doc/scipy-0.14.0/reference/ndimage.html#module-scipy.ndimage.interpolation

Additionally, note that all Keras image transformations operate on Numpy arrays, not PIL images.

**Comment by erilyth** [comment]
@fchollet Used the geometric interpolation primitive offered by scipy. This also performs interpolation of pixels from the input which was not done earlier in the manual array iteration approach.

**Comment by erilyth** [comment]
Any updates on this?

**Comment by fchollet** [comment]
Closing outdated PR. If you still care about the content of the PR, please submit a new PR to `master`, updated for the Keras 2.0 API.

**Pull request closed without merging**
