### PR TITLE
Seqseq example: Use symbolic loop for inference

### PR DESCRIPTION
**Pull request by farizrahman4u**
https://twitter.com/farizrahman4u/status/914609159596859392

### CODE REVIEW

**Comment by fchollet** [comment]
This is interesting, but also a lot more involved than the original version. In particular it leverages features than aren't quite private but aren't really to be found in regular use cases, like `K.rnn` or `layer.call`. Part of the goal of the example is too show that s2s in Keras is *simple*, and I think this looks rather complicated.

At the same time, it's good to make it available for reference. Make as a comment or something?

**Comment by farizrahman4u** [comment]
Couple of advantages of using symbolic loop:

* Faster prediction when batch size > 1
*  `decode_sequence` method is now simpler, since we have a single "end to end" inference model.

What do you mean by make as a comment? Please elaborate.

**Comment by fchollet** [comment]
> What do you mean by make as a comment? Please elaborate.

Sorry, I meant: could we make this available as a comment? Ideally, we would add it as an alternative code snippet in the associated tutorial on the Keras blog, together with some explanations of what it does.

The primary reason for not merging it here is that it involves niche features (which I generally wouldn't recommend using other than as a workaround) and isn't as straightforward as the base version -- our goal is to make examples as simple and obvious as possible, possibly at the cost of performance.

**Comment by VallabhMahajan1** [comment]
I was trying to use the above code to eliminate the use of while loop in decode_sequence function(). But, I couldn't figure out what is "encoder" while defining the inference model.

image

**Pull request closed without merging**
