### PR TITLE
Add fast_compile to Theano 

### PR DESCRIPTION
**Pull request by Dref360**

### CODE REVIEW

**Comment by farizrahman4u** [comment]
Can't believe this wasn't already done!

**Comment by Dref360** [comment]
Doesn't seem to work though :(

**Comment by Dref360** [comment]
Maybe Theano doesn't need to be run for certains module?
* keras.application
* keras.datasets
* keras.utils
* keras.preprocessing

**Comment by fchollet** [comment]
Maybe we can set this mode for `keras.applications` only?

You're right that the following modules don't need Theano-specific tests:

> keras.datasets
> keras.utils
> keras.preprocessing

**Comment by Dref360** [comment]
Will close for now since there seems to be problem when putting it on Travis.

**Pull request closed without merging**
