### PR TITLE
Bug fix: K.batch_dot(); tf backend

### PR DESCRIPTION
**Pull request by farizrahman4u**
#6173

### CODE REVIEW

**Comment by Dref360** [comment]
Could you add the code that created the issue in the test for legacy purposes?
`from keras import backend as K

x = K.ones(shape=(100,20))
y = K.ones(shape=(100,30,20))
xy = K.batch_dot(x,y,axes=(1,2))`

**Comment by fchollet** [comment]
This will need unit tests (in backend tests)

**Comment by farizrahman4u** [comment]
ping @fchollet

**Comment by fchollet** [comment]
LGTM, thanks

**Pull request merged**
