### PR TITLE
csv logger improvements

### PR DESCRIPTION
**Pull request by kretes**
- will not add multiple headers
- ability to add static values to output file

### CODE REVIEW

**Comment by kretes** [comment]
The reason for this improvements is to use the file as a 'experiment-results' for a various of net configurations and so on.

I use it like this:

```
model_id = "in160-32-32-64-conv3-fc-sgd-lr-0_01-decay-0_01"
csvc = keras.callbacks.CSVLogger('models/train/results.csv', separator=',', append=True, additional_columns={'model_id':model_id})
```

and I can track multiple networks in one file for further analysis

**Comment by kretes** [comment]
Can I do something to get this merged? Maybe we should discuss this feature first?

**Comment by kretes** [comment]
Could you least briefly explain why it shouldn't hit master?

The most important part of this PR was not the unnecessary header in the csv file but the ability to pass an additional fields to the results file - making it possible to keep a single file with all the results when someone is doing multiple experiments.

After merging https://github.com/fchollet/keras/pull/4426 this PR would need a refresh - I can do that provided it is worth the effort.

**Comment by tx1985** [comment]
fyi I suggest a PR which includes your feature "ability to add static values to output file" - for me it works well, maybe others find it helpful, too: #12266

**Pull request closed without merging**
