### PR TITLE
Added filter_size option for Convolution2D and tests of this new feature

### PR DESCRIPTION
**Pull request by jeammimi**
Added a filter_size option to Convolution2D
By default [None,None] it keeps the filter_size to nb_row,nb_col,
but now you can specify a different filter size.

The filter size option can be understood there:

http://cs231n.github.io/convolutional-networks/

### CODE REVIEW

**Comment by fchollet** [comment]
?

**Comment by jeammimi** [comment]
When you apply a convolution network, the filters can have a size different
from the original image.
If your original image has a size [9,9] , you can apply filter of size
[2,2] , [3,3] or whatever size you want.
In your default set-up the filter size was set to [9,9]

2015-07-29 10:08 GMT+02:00 François Chollet <notifications@github.com>:

**Comment by jeammimi** [comment]
Hi,
Sorry to disturb you again,
but you do not want to merge because you don't think that the filter size
should be flexible?


2015-07-29 10:16 GMT+02:00 François Chollet <notifications@github.com>:

**Comment by fchollet** [comment]
What you mean by "filter size" is in fact configurable via the nb_row and nb_col parameters.

**Comment by jeammimi** [comment]
Oh sorry.
I was thinking that it was the size of the input image.


2015-07-29 10:24 GMT+02:00 François Chollet <notifications@github.com>:

**Pull request closed without merging**
