### PR TITLE
Add Swish activation function

### PR DESCRIPTION
**Pull request by rilut**
Do we need this (and Swish-β) activation function? Thanks.

### CODE REVIEW

**Comment by fchollet** [comment]
Let's skip it for now. It's really easy for people to drop `x * K.sigmoid(x)` in their code if they need it right now, and we don't know yet whether the new activation will get any traction in the next 6 months.

So let's revisit in a few months. If it gets some traction, we will add it.

**Comment by ekerazha** [comment]
@rilut Maybe it could be added to https://github.com/farizrahman4u/keras-contrib

**Comment by edmondja** [comment]
Btw, here is the SELU-like scaled version :
from keras import backend as K
def scaledSwish(x):
    return  1.78718727865 * ( x * K.sigmoid(x)  - 0.20662096414)
From :
https://www.reddit.com/r/MachineLearning/comments/773epu/r_swish_a_selfgated_activation_function_google/doj24ps/

**Comment by mmolero** [comment]
Hi All
Does Anyone know how we can save a model using for example this custom activation function.
When I'm trying to parse it in json (model.to_json()) I got the following:

````
AttributeError: 'Activation' object has no attribute '__name__'`
````
I did the definition making use of

```
def swish(x):

    return (K.sigmoid(x) * x)

get_custom_objects().update({'swish': Activation(swish )})
```

thanks!!

**Pull request closed without merging**
