### PR TITLE
Added 1D Convolution and Pooling

### PR DESCRIPTION
**Pull request by pranv**
This was the best I could come up with, and its working.

### CODE REVIEW

**Comment by pranv** [comment]
Expected something better?

**Comment by fchollet** [comment]
We're still thinking about how to handle this, including whether or not we should separate temporal convolutions and spatial convolutions. It might be a few days until we make a decision.

**Comment by jasonwbw** [comment]
I try convolution by the same way, but a common interface may be more artistic. There are so many repetitive codes.

**Comment by fchollet** [comment]
We still don't have any immediate plans for how to handle new types of convolutions, so I can definitely merge this in the meantime. First I'll have to make this compatible with the recent changes we made to the layer API.

**Comment by jramapuram** [comment]
Any update on this merge?

**Pull request merged**
