### PR TITLE
Add custom output function and file filter to DirectoryIterator

### PR DESCRIPTION
**Pull request by davidvetrano**
This PR adds a new class mode, `custom` which may be used with `flow_from_directory`. When specified, a callback function is invoked for each sample image. The PR also adds a mechanism by which files can be excluded from the dataset via a predicate similarly invoked for each sample image.

This is a follow-up to #5152.

### CODE REVIEW

**Comment by fchollet** [comment]
I believe this is too advanced and would not benefit a sufficiently large fraction of the user base. Every new function argument has a cost: it complicates the API and complicates the codebase. The cost must be clearly worth it.

**Comment by aditya17a** [comment]
@fchollet I'm sorry but I disagree. This is not an advanced requirement at all. Yes, classification problems are more common than regression problems in neural networks but that's changing fast. A lot of end-to-end networks these days rely heavily on regression (autonomous vehicles is one such example). The main reason behind the popularity of Keras has been the fact that it can be used to quickly implement a wide variety of ideas, and hence I would say it is totally worth investing in this piece of functionality (if not the exact code submitted in this PR).

**Comment by KeithWM** [comment]
I think this approach would also be useful if training a classification network on more than one type of class. In particular, I'm looking to train a network to recognize both the 'genre' and 'style' of a paining in the Kaggle Painter by Numbers case. Rather than splitting my images over class directories, I can use this to tell the network which 'genre' and 'style' a painting belongs to by looking up the file name in the database.

(Currently I find the image filenames from the database and then load them with Pillow/PIL, but I think this is very slow compared to using .flow_from_directory().)

**Comment by jrjbertram** [comment]
I'll also throw in that I'm using regression on an image problem and am looking for a way to train a regression nnet with batches of images at a time.

**Comment by KiransHub** [comment]
This is useful even for beginners like me! I'm currently trying to train an autoencoder model on large images. I'm quickly running out of memory as my datasets are quite large. 

Having more memory would give me more of a hyper parameter range to play with using the keras tuner.

**Pull request closed without merging**
